using System;

namespace ScopeX.Hardware.Driver
{
    //This File is Auto Generated By FPGAViewerSimpleness.exe At Computer[D508-LCHY] ,2025.10.23 15:05:42
    //Source File Name = F:\00_FPGA_Proj_2025\0_script\0_Register_Generate\Register_Gen_10bit_V1_0\gen_register\hdl_verilog\pcie_registers.v
    //Source File Last Auto GeneratedTime=2025-08-27 16:22:32
    //Source File LastWritedTime = 2025.08.27 16:22:32


    ///<see href="file:///F:\00_FPGA_Proj_2025\0_script\0_Register_Generate\FPGAViewerSimpleness\pcie_registers\JPO6000_Doc_SoftwareRegister_PcieBd.html"></see>
    ///<see href="file:///F:\00_FPGA_Proj_2025\0_script\0_Register_Generate\FPGAViewerSimpleness\pcie_registers\images\pcie_registers.png "></see>

    /// <summary>
    ///共有[206]个寄存器，其中写寄存器[145]个，没有用到的共[0]，读寄存器[61个]，没有用到的共[0]个.
    ///FPGA中还有[0]个定义的寄存器在软件中没有使用。
    ///在本文件中出现[todo...]字样的地方需要注意使用，并尽量与硬件人员一起完善。
    /// </summary>
    internal partial class PcieBdReg
    {
        /// <summary>
        ///共有[145]个,其中[0]没有使用.
        /// </summary>
        public enum W
        {
            #region====================Adc=[共1个寄存器]======================================

            /// <summary>
            /// REG_ADC_RECIEVE_ISERDESE_RST_PCIE[write]
            /// abs-addr:0X10190; none
            /// reg_hw_name:reg_adc_recieve_iserdese_rst_pcie
            /// bit-width:16 ;  adc数据接收iserdes复位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X190),0x10190")]
            Adc_RecieveIserdeseRstPcie     = 0X10000 | (0X190),
            #endregion Adc

            #region====================AnalogChCtrl=[共17个寄存器]============================

            /// <summary>
            /// REG_READPROBEINFOFROMMCU_CHANNELNO[write]
            /// abs-addr:0X100AC; 发送读取指定通道所对应的探头的信息,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_rd_probe_info_mcu_ch_no
            /// bit-width:16 ;  通道编号，从1开始
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0AC),0x100AC")]
            AnalogChCtrl_ReadProbeInfoFromMCU_ChannelNo = 0X10000 | (0X0AC),

            /// <summary>
            /// REG_READPROBEINFOFROMMCU_ENABLE[write]
            /// abs-addr:0X100B0; none
            /// reg_hw_name:reg_rd_probe_info_mcu_en
            /// bit-width:16 ;  上升沿有效，上升沿发生时，fpga通过spi向通道的mcu发送读取命令
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0B0),0x100B0")]
            AnalogChCtrl_ReadProbeInfoFromMCU_Enable = 0X10000 | (0X0B0),

            /// <summary>
            /// REG_READPROBEINFOFROMFPGA_ADDRESS[write]
            /// abs-addr:0X100B4; none
            /// reg_hw_name:reg_rd_probe_info_from_fpga_addr
            /// bit-width:16 ;  读取探头信息的地址，从0开始，每加1表示移动一个字节
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0B4),0x100B4")]
            AnalogChCtrl_ReadProbeInfoFromFPGA_Address = 0X10000 | (0X0B4),

            /// <summary>
            /// REG_READPROBEINFOFROMFPGA_ENABLE[write]
            /// abs-addr:0X100B8; none
            /// reg_hw_name:reg_rd_probe_info_from_fpga_en
            /// bit-width:1 ;  读取的探头信息指定字节位置的一个字节的使能
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0B8),0x100B8")]
            AnalogChCtrl_ReadProbeInfoFromFPGA_Enable = 0X10000 | (0X0B8),

            /// <summary>
            /// REG_PROBE_LED[write]
            /// abs-addr:0X100BC; none
            /// reg_hw_name:reg_probe_led
            /// bit-width:16 ;  位控：1表示点亮，0表示关闭，低位到高位分别表示通道1、通道2.也就是最多支持8个通道
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0BC),0x100BC")]
            AnalogChCtrl_ProbeLed          = 0X10000 | (0X0BC),

            /// <summary>
            /// REG_CH_SHIFTEREG_DATA_H32[write]
            /// abs-addr:0X100C0; 使能后将传给4094的64位数据 之高32位，最低8位控制通道的高低阻态和直通衰减，参照模拟通道控制文档,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_shiftereg_data_h32
            /// bit-width:32 ;  high_32bits_of_64bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0C0),0x100C0")]
            AnalogChCtrl_4094Data_H32      = 0X10000 | (0X0C0),

            /// <summary>
            /// REG_CH_SHIFTEREG_DATA_L32[write]
            /// abs-addr:0X100C4; 使能后将传给4094的64位数据 之低32位，最低8位控制通道的高低阻态和直通衰减，参照模拟通道控制文档,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_shiftereg_data_l32
            /// bit-width:32 ;  low_32bits_of_64bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0C4),0x100C4")]
            AnalogChCtrl_4094Data_L32      = 0X10000 | (0X0C4),

            /// <summary>
            /// REG_CH_SHIFTEREG_EN[write]
            /// abs-addr:0X100C8; 使能后将传给4094的40位数据传递给通道板的单片机 延时要满足通过SPI将40位的数据传输完毕，与传输该数据的SPI的Clock有关。先发送40位的数据给FPGA，然后拉高，延时足够的时间，然后拉低。为上升沿有效。,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_shiftereg_en
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0C8),0x100C8")]
            AnalogChCtrl_4094TransStart    = 0X10000 | (0X0C8),

            /// <summary>
            /// REG_CH_DSA_DATA[write]
            /// abs-addr:0X100CC; 设置模拟通道衰减值,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_dsa_data
            /// bit-width:32 ;  8bit,衰减器数据值，需配合ch_dsa_en使用
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0CC),0x100CC")]
            AnalogChCtrl_CH_DSA_DATA       = 0X10000 | (0X0CC),

            /// <summary>
            /// REG_CH_DSA_EN[write]
            /// abs-addr:0X100D0; 设置模拟通道衰减值使能信号,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_dsa_en
            /// bit-width:32 ;  8bit,衰减器数据使能信号，独热码控制各通道
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0D0),0x100D0")]
            AnalogChCtrl_CH_DSA_EN         = 0X10000 | (0X0D0),

            /// <summary>
            /// REG_CH_DAC_DATA[write]
            /// abs-addr:0X100D4; 配置给DAC的数据，是按照位域拼合成的。ConfigWord = 0x00030000u | (Port << 12);ConfigWord <<= 8;ConfigWord |= Data << 4;,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_dac_data
            /// bit-width:32 ;  32bits_data
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0D4),0x100D4")]
            AnalogChCtrl_DAC_ConfigData    = 0X10000 | (0X0D4),

            /// <summary>
            /// REG_CH_DAC_SEL[write]
            /// abs-addr:0X100D8; 不同DAC的选择,同时还需要配置不同的端口，偏值电压、基线移动、参考电平、等模拟触发电平需要选择不同的DAC，参照模拟通道控制文档。,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_dac_sel
            /// bit-width:32 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0D8),0x100D8")]
            AnalogChCtrl_DAC_Sel           = 0X10000 | (0X0D8),

            /// <summary>
            /// REG_CH_POWER_CTRL[write]
            /// abs-addr:0X100DC; 高八位为0xff时才能生效，因此，控制通道上下电时需要把高八位置成0xff再发送低8bit上下电控制,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_power_ctrl
            /// bit-width:32 ;  [15:8]:0xff表示发送使能 ; [7:0]：0x01表示通道上电，0x00表示通道下电
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0DC),0x100DC")]
            AnalogChCtrl_channelpower_ctrl = 0X10000 | (0X0DC),

            /// <summary>
            /// REG_CH_DAC_EN[write]
            /// abs-addr:0X100E0; 上升沿开始传输。然后根据SPI的传输速度传输32位数据等待足够的时间，然后拉低。需要与DAC_Enable_CS一起联动。,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_dac_en
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0E0),0x100E0")]
            AnalogChCtrl_DAC_TransStart    = 0X10000 | (0X0E0),

            /// <summary>
            /// REG_CH_DSA_DATA_8G[write]
            /// abs-addr:0X10174; 设置模拟通道衰减值,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ch_dsa_data_8g
            /// bit-width:16 ;  16bit,衰减器数据值，需配合ch_dsa_en使用
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X174),0x10174")]
            AnalogChCtrl_reg_ch_dsa_data_8g = 0X10000 | (0X174),

            /// <summary>
            /// CH_SERIAL_COM_SEL[write]
            /// abs-addr:0X10228; DBI_通道串口组选择信号，CH1/2为一组，CH3/4为一组,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:ch_serial_com_sel
            /// bit-width:1 ;  0：选择第一组::dbi20g为ch1/ch2   1:选择第二组::dbi20g为ch3/ch4
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X228),0x10228")]
            AnalogChCtrl_serial_com_sel    = 0X10000 | (0X228),

            /// <summary>
            /// CH_POWER_CTRL_DBI[write]
            /// abs-addr:0X1022C; DBI通道底板电源控制,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:ch_power_ctrl_dbi
            /// bit-width:1 ;  0：默认关闭通道电源  1：打开通道电源
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X22C),0x1022C")]
            AnalogChCtrl_CH_power_ctrl_dbi = 0X10000 | (0X22C),
            #endregion AnalogChCtrl

            #region====================BoardSync=[共13个寄存器]===============================

            /// <summary>
            /// REG_SERDES_PATTERN_SHIFT_ADDR_PCIE[write]
            /// abs-addr:0X10078; bit之间延迟校正的地址,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_serdes_pattern_shift_addr_pcie
            /// bit-width:16 ;  [7]:控制reg_serdes_pattern_shift_value_acq值装载(高有效) ; [6:0]:pattern_shift_acq装载地址
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X078),0x10078")]
            BoardSync_Pattern_Shift_Addr   = 0X10000 | (0X078),

            /// <summary>
            /// REG_SERDES_PATTERN_SHIFT_VALUE_PCIE[write]
            /// abs-addr:0X1007C; 多对Lane之间的对齐操作,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_serdes_pattern_shift_value_pcie
            /// bit-width:16 ;  [7:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X07C),0x1007C")]
            BoardSync_Pattern_Shift_Value  = 0X10000 | (0X07C),

            /// <summary>
            /// REG_IO_RESET_PCIE[write]
            /// abs-addr:0X10080; 高有效，持续时间20ns，先发0，再发1，复位完成后发0,否,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_io_reset_pcie
            /// bit-width:1 ;  1bit
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X080),0x10080")]
            BoardSync_IO_Reset             = 0X10000 | (0X080),

            /// <summary>
            /// REG_TAP_START_PCIE[write]
            /// abs-addr:0X10084; 扫窗的起始tap值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_tap_start_pcie
            /// bit-width:16 ;  目前使用[8:0]：范围可以覆盖0~511
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X084),0x10084")]
            BoardSync_Tap_Start            = 0X10000 | (0X084),

            /// <summary>
            /// REG_TAP_GAP_PCIE[write]
            /// abs-addr:0X10088; 扫窗的步进gap值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_tap_gap_pcie
            /// bit-width:16 ;  目前使用[8:0]：范围可以覆盖0~511
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X088),0x10088")]
            BoardSync_Tap_Gap              = 0X10000 | (0X088),

            /// <summary>
            /// REG_TAP_STOP_PCIE[write]
            /// abs-addr:0X1008C; 扫窗的终止tap值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_tap_stop_pcie
            /// bit-width:16 ;  目前使用[8:0]：范围可以覆盖0~511
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X08C),0x1008C")]
            BoardSync_Tap_Stop             = 0X10000 | (0X08C),

            /// <summary>
            /// REG_SCAN_START_PCIE[write]
            /// abs-addr:0X10090; 扫窗开始的控制信号，正脉冲有效,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_scan_start_pcie
            /// bit-width:1 ;  1bit
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X090),0x10090")]
            BoardSync_Scan_Start           = 0X10000 | (0X090),

            /// <summary>
            /// REG_RAM_RD_EN_PCIE[write]
            /// abs-addr:0X10094; 扫窗结果存储RAM的读使能信号,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ram_rd_en_pcie
            /// bit-width:1 ;  1bit
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X094),0x10094")]
            BoardSync_Ram_Rd_En            = 0X10000 | (0X094),

            /// <summary>
            /// REG_PATTERN_SEL_PCIE[write]
            /// abs-addr:0X10098; 测试模式选择： ; 0：板间传输为正常信号 ; 1：板间传输为Pattern信号,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pattern_sel_pcie
            /// bit-width:16 ;  [0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X098),0x10098")]
            BoardSync_Pattern_Sel          = 0X10000 | (0X098),

            /// <summary>
            /// REG_RAM_RD_ADDR_PCIE[write]
            /// abs-addr:0X1009C; 扫窗结果存储RAM的读地址： ; 0xxx_xxxx_xxxx：代表数据信号线,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_ram_rd_addr_pcie
            /// bit-width:16 ;  [11:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X09C),0x1009C")]
            BoardSync_Ram_Rd_Addr          = 0X10000 | (0X09C),

            /// <summary>
            /// REG_IO_DELAY_VALUE_PCIE[write]
            /// abs-addr:0X100A0; 软件计算稳定的delay值，与reg_io_delay_addr_pro成对使用，先发送地址reg_io_delay_addr_pro，再发送数据reg_io_delay_value_pro,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_io_delay_value_pcie
            /// bit-width:16 ;  [8:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0A0),0x100A0")]
            BoardSync_Io_Delay_Value       = 0X10000 | (0X0A0),

            /// <summary>
            /// REG_IO_DELAY_LOAD_EN_PCIE[write]
            /// abs-addr:0X100A4; 板间传输IODelay延迟值装载使能，跟Io_Delay_Value以及Io_Delay_Addr为一组控制寄存器，首先发送Io_Delay_Value，再发送Io_Delay_Addr，最后发送Io_Delay_Ld_En，先发1，等待1us后，发送0完成配置,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_io_delay_load_en_pcie
            /// bit-width:1 ;  [0]:高电平有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0A4),0x100A4")]
            BoardSync_Io_Delay_Ld_En       = 0X10000 | (0X0A4),

            /// <summary>
            /// REG_IO_DELAY_ADDR_PCIE[write]
            /// abs-addr:0X100A8; 软件计算稳定的delay值对应的lane地址，与reg_io_delay_value_pro成对使用,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_io_delay_addr_pcie
            /// bit-width:16 ;  [7:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0A8),0x100A8")]
            BoardSync_Io_Delay_Addr        = 0X10000 | (0X0A8),
            #endregion BoardSync

            #region====================CaseFanCtrl=[共13个寄存器]=============================

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY[write]
            /// abs-addr:0X10018; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty
            /// bit-width:16 ;  以机箱正面为方向,机箱外壳右侧，下风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X018),0x10018")]
            CaseFanCtrl_Case_Fan_PWM_Duty  = 0X10000 | (0X018),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY1[write]
            /// abs-addr:0X1012C; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty1
            /// bit-width:16 ;  以机箱正面为方向,机箱外壳左侧，下风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X12C),0x1012C")]
            CaseFanCtrl_Case_Fan_PWM_Duty1 = 0X10000 | (0X12C),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY2[write]
            /// abs-addr:0X10130; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty2
            /// bit-width:16 ;  adc3/adc4风扇同时控制，给adc3和adc4发同样的值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X130),0x10130")]
            CaseFanCtrl_Case_Fan_PWM_Duty2 = 0X10000 | (0X130),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY3[write]
            /// abs-addr:0X10134; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty3
            /// bit-width:16 ;  adc3/adc4风扇同时控制，给adc3和adc4发同样的值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X134),0x10134")]
            CaseFanCtrl_Case_Fan_PWM_Duty3 = 0X10000 | (0X134),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY4[write]
            /// abs-addr:0X10138; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty4
            /// bit-width:16 ;  pro fpga的风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X138),0x10138")]
            CaseFanCtrl_Case_Fan_PWM_Duty4 = 0X10000 | (0X138),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY5[write]
            /// abs-addr:0X1013C; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty5
            /// bit-width:16 ;  acq2 fpga的风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X13C),0x1013C")]
            CaseFanCtrl_Case_Fan_PWM_Duty5 = 0X10000 | (0X13C),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY6[write]
            /// abs-addr:0X10140; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty6
            /// bit-width:16 ;  adc1/adc2风扇同时控制，给adc1和adc2发同样的值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X140),0x10140")]
            CaseFanCtrl_Case_Fan_PWM_Duty6 = 0X10000 | (0X140),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY7[write]
            /// abs-addr:0X10144; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty7
            /// bit-width:16 ;  adc1/adc2风扇同时控制，给adc1和adc2发同样的值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X144),0x10144")]
            CaseFanCtrl_Case_Fan_PWM_Duty7 = 0X10000 | (0X144),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY8[write]
            /// abs-addr:0X10148; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty8
            /// bit-width:16 ;  pcie fpga的风扇，hg08h v2版本没有通道风扇接口，暂时给通道风扇控制使用
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X148),0x10148")]
            CaseFanCtrl_Case_Fan_PWM_Duty8 = 0X10000 | (0X148),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY9[write]
            /// abs-addr:0X1014C; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty9
            /// bit-width:16 ;  acq1 fpga的风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X14C),0x1014C")]
            CaseFanCtrl_Case_Fan_PWM_Duty9 = 0X10000 | (0X14C),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY10[write]
            /// abs-addr:0X10150; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty10
            /// bit-width:16 ;  hg08h v3版本通道风扇控制
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X150),0x10150")]
            CaseFanCtrl_Case_Fan_PWM_Duty10 = 0X10000 | (0X150),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY11[write]
            /// abs-addr:0X10154; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty11
            /// bit-width:16 ;  以机箱正面为方向,机箱外壳右侧，上风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X154),0x10154")]
            CaseFanCtrl_Case_Fan_PWM_Duty11 = 0X10000 | (0X154),

            /// <summary>
            /// REG_CASE_FAN_PWM_DUTY12[write]
            /// abs-addr:0X10170; 机箱风扇控制占空比，主频20KHz,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_case_fan_pwm_duty12
            /// bit-width:16 ;  以机箱正面为方向,机箱外壳左侧，上风扇
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X170),0x10170")]
            CaseFanCtrl_Case_Fan_PWM_Duty12 = 0X10000 | (0X170),
            #endregion CaseFanCtrl

            #region====================CoefficientsTable=[共3个寄存器]========================

            /// <summary>
            /// REG_PCIE_COEFFICIENTSTABLE_RESET[write]
            /// abs-addr:0X1004C; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_coefficientstable_reset
            /// bit-width:16 ;  复位，上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X04C),0x1004C")]
            CoefficientsTable_Reset        = 0X10000 | (0X04C),

            /// <summary>
            /// REG_PCIE_COEFFICIENTSTABLE_ACTION_CODE[write]
            /// abs-addr:0X10050; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_coefficientstable_action_code
            /// bit-width:16 ;  干什么|什么系数：低4位表示什么系数，1=afc系数；高4位表示干什么，1=写入；2=读回
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X050),0x10050")]
            CoefficientsTable_ActionCode   = 0X10000 | (0X050),

            /// <summary>
            /// REG_PCIE_COEFFICIENTSTABLE_ACTION_START[write]
            /// abs-addr:0X10054; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_coefficientstable_action_start
            /// bit-width:16 ;  操作开始，上升沿有效，其状态通过pcie的寄存器读取
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X054),0x10054")]
            CoefficientsTable_ActionStart  = 0X10000 | (0X054),
            #endregion CoefficientsTable

            #region====================DBI=[共34个寄存器,3个子组]======================================== =
            #region====================LO=[共12寄存器]=================================================

            /// <summary>
            /// DBI_BIN_DATA_CH1[write]
            /// abs-addr:0X101C0; none
            /// reg_hw_name:dbi_bin_data_ch1
            /// bit-width:16 ;  混频板(本振/衰减值)数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1C0),0x101C0")]
            DBI_LO_DBI_bin_data_ch1        = 0X10000 | (0X1C0),

            /// <summary>
            /// DBI_BIN_DATA_CH2[write]
            /// abs-addr:0X101C4; none
            /// reg_hw_name:dbi_bin_data_ch2
            /// bit-width:16 ;  第二块混频板(本振/衰减值)数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1C4),0x101C4")]
            DBI_LO_DBI_bin_data_ch2        = 0X10000 | (0X1C4),

            /// <summary>
            /// DBI_BIN_EN_CH1[write]
            /// abs-addr:0X101C8; none
            /// reg_hw_name:dbi_bin_en_ch1
            /// bit-width:1 ;  发送控制字开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1C8),0x101C8")]
            DBI_LO_DBI_bin_en_ch1          = 0X10000 | (0X1C8),

            /// <summary>
            /// DBI_BIN_EN_CH2[write]
            /// abs-addr:0X101CC; none
            /// reg_hw_name:dbi_bin_en_ch2
            /// bit-width:1 ;  第二块发送控制字开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1CC),0x101CC")]
            DBI_LO_DBI_bin_en_ch2          = 0X10000 | (0X1CC),

            /// <summary>
            /// DBI_BIN_WEN_CH1[write]
            /// abs-addr:0X101D0; none
            /// reg_hw_name:dbi_bin_wen_ch1
            /// bit-width:1 ;  混频板(本振/衰减值)数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1D0),0x101D0")]
            DBI_LO_DBI_bin_wen_ch1         = 0X10000 | (0X1D0),

            /// <summary>
            /// DBI_BIN_WEN_CH2[write]
            /// abs-addr:0X101D4; none
            /// reg_hw_name:dbi_bin_wen_ch2
            /// bit-width:1 ;  第二块混频板(本振/衰减值)数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1D4),0x101D4")]
            DBI_LO_DBI_bin_wen_ch2         = 0X10000 | (0X1D4),

            /// <summary>
            /// DBI_BIN_DATA_CH3[write]
            /// abs-addr:0X101F8; none
            /// reg_hw_name:dbi_bin_data_ch3
            /// bit-width:16 ;  第3块混频板(本振/衰减值)数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1F8),0x101F8")]
            DBI_LO_DBI_bin_data_ch3        = 0X10000 | (0X1F8),

            /// <summary>
            /// DBI_BIN_DATA_CH4[write]
            /// abs-addr:0X101FC; none
            /// reg_hw_name:dbi_bin_data_ch4
            /// bit-width:16 ;  第4块混频板(本振/衰减值)数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1FC),0x101FC")]
            DBI_LO_DBI_bin_data_ch4        = 0X10000 | (0X1FC),

            /// <summary>
            /// DBI_BIN_EN_CH3[write]
            /// abs-addr:0X10200; none
            /// reg_hw_name:dbi_bin_en_ch3
            /// bit-width:1 ;  第3块发送控制字开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X200),0x10200")]
            DBI_LO_DBI_bin_en_ch3          = 0X10000 | (0X200),

            /// <summary>
            /// DBI_BIN_EN_CH4[write]
            /// abs-addr:0X10204; none
            /// reg_hw_name:dbi_bin_en_ch4
            /// bit-width:1 ;  第4块发送控制字开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X204),0x10204")]
            DBI_LO_DBI_bin_en_ch4          = 0X10000 | (0X204),

            /// <summary>
            /// DBI_BIN_WEN_CH3[write]
            /// abs-addr:0X10208; none
            /// reg_hw_name:dbi_bin_wen_ch3
            /// bit-width:1 ;  第3块混频板(本振/衰减值)数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X208),0x10208")]
            DBI_LO_DBI_bin_wen_ch3         = 0X10000 | (0X208),

            /// <summary>
            /// DBI_BIN_WEN_CH4[write]
            /// abs-addr:0X1020C; none
            /// reg_hw_name:dbi_bin_wen_ch4
            /// bit-width:1 ;  第4块混频板(本振/衰减值)数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X20C),0x1020C")]
            DBI_LO_DBI_bin_wen_ch4         = 0X10000 | (0X20C),
            #endregion 
            #region====================SOURCE=[共6寄存器]==============================================

            /// <summary>
            /// DBI_BIN_DATA_SRC[write]
            /// abs-addr:0X10210; none
            /// reg_hw_name:dbi_bin_data_src
            /// bit-width:16 ;  信号源数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X210),0x10210")]
            DBI_SOURCE_DBI_bin_data_src    = 0X10000 | (0X210),

            /// <summary>
            /// DBI_BIN_EN_SRC[write]
            /// abs-addr:0X10214; none
            /// reg_hw_name:dbi_bin_en_src
            /// bit-width:1 ;  信号源发送控制字开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X214),0x10214")]
            DBI_SOURCE_DBI_bin_en_src      = 0X10000 | (0X214),

            /// <summary>
            /// DBI_BIN_WEN_SRC[write]
            /// abs-addr:0X10218; none
            /// reg_hw_name:dbi_bin_wen_src
            /// bit-width:1 ;  信号源数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X218),0x10218")]
            DBI_SOURCE_DBI_bin_wen_src     = 0X10000 | (0X218),

            /// <summary>
            /// DBI_BIN_DATA_SRC_2[write]
            /// abs-addr:0X1021C; none
            /// reg_hw_name:dbi_bin_data_src_2
            /// bit-width:16 ;  信号源数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X21C),0x1021C")]
            DBI_SOURCE_DBI_bin_data_src_2  = 0X10000 | (0X21C),

            /// <summary>
            /// DBI_BIN_EN_SRC_2[write]
            /// abs-addr:0X10220; none
            /// reg_hw_name:dbi_bin_en_src_2
            /// bit-width:1 ;  信号源发送控制字开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X220),0x10220")]
            DBI_SOURCE_DBI_bin_en_src_2    = 0X10000 | (0X220),

            /// <summary>
            /// DBI_BIN_WEN_SRC_2[write]
            /// abs-addr:0X10224; none
            /// reg_hw_name:dbi_bin_wen_src_2
            /// bit-width:1 ;  信号源数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X224),0x10224")]
            DBI_SOURCE_DBI_bin_wen_src_2   = 0X10000 | (0X224),
            #endregion 
            #region====================atten=[共16寄存器]==============================================

            /// <summary>
            /// DBI_SPI_DATA_CH1[write]
            /// abs-addr:0X101A0; none
            /// reg_hw_name:dbi_spi_data_ch1
            /// bit-width:8 ;  衰减器adrf5720的衰减值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1A0),0x101A0")]
            DBI_atten_DBI_SPI_data_ch1     = 0X10000 | (0X1A0),

            /// <summary>
            /// DBI_SPI_DATA_CH2[write]
            /// abs-addr:0X101A4; none
            /// reg_hw_name:dbi_spi_data_ch2
            /// bit-width:8 ;  第二块衰减器adrf5720的衰减值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1A4),0x101A4")]
            DBI_atten_DBI_SPI_data_ch2     = 0X10000 | (0X1A4),

            /// <summary>
            /// DBI_SPI_EN_CH1[write]
            /// abs-addr:0X101A8; none
            /// reg_hw_name:dbi_spi_en_ch1
            /// bit-width:1 ;  衰减器adrf5720数据发送开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1A8),0x101A8")]
            DBI_atten_DBI_SPI_en_ch1       = 0X10000 | (0X1A8),

            /// <summary>
            /// DBI_SPI_EN_CH2[write]
            /// abs-addr:0X101AC; none
            /// reg_hw_name:dbi_spi_en_ch2
            /// bit-width:1 ;  第二块衰减器adrf5720数据发送开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1AC),0x101AC")]
            DBI_atten_DBI_SPI_en_ch2       = 0X10000 | (0X1AC),

            /// <summary>
            /// DBI_SPI_WEN_CH1[write]
            /// abs-addr:0X101B0; none
            /// reg_hw_name:dbi_spi_wen_ch1
            /// bit-width:1 ;  衰减器adrf5720数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1B0),0x101B0")]
            DBI_atten_DBI_SPI_wen_ch1      = 0X10000 | (0X1B0),

            /// <summary>
            /// DBI_SPI_WEN_CH2[write]
            /// abs-addr:0X101B4; none
            /// reg_hw_name:dbi_spi_wen_ch2
            /// bit-width:1 ;  第二块衰减器adrf5720数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1B4),0x101B4")]
            DBI_atten_DBI_SPI_wen_ch2      = 0X10000 | (0X1B4),

            /// <summary>
            /// DBI_THROUGH_SEL_CH1[write]
            /// abs-addr:0X101B8; none
            /// reg_hw_name:dbi_through_sel_ch1
            /// bit-width:1 ;  衰减器adrf5720直通（1）、衰减（0）选择
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1B8),0x101B8")]
            DBI_atten_DBI_through_sel_ch1  = 0X10000 | (0X1B8),

            /// <summary>
            /// DBI_THROUGH_SEL_CH2[write]
            /// abs-addr:0X101BC; none
            /// reg_hw_name:dbi_through_sel_ch2
            /// bit-width:1 ;  衰减器adrf5720直通（1）、衰减（0）选择
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1BC),0x101BC")]
            DBI_atten_DBI_through_sel_ch2  = 0X10000 | (0X1BC),

            /// <summary>
            /// DBI_SPI_DATA_CH3[write]
            /// abs-addr:0X101D8; none
            /// reg_hw_name:dbi_spi_data_ch3
            /// bit-width:8 ;  第3块衰减器adrf5720的衰减值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1D8),0x101D8")]
            DBI_atten_DBI_SPI_data_ch3     = 0X10000 | (0X1D8),

            /// <summary>
            /// DBI_SPI_DATA_CH4[write]
            /// abs-addr:0X101DC; none
            /// reg_hw_name:dbi_spi_data_ch4
            /// bit-width:8 ;  第4块衰减器adrf5720的衰减值
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1DC),0x101DC")]
            DBI_atten_DBI_SPI_data_ch4     = 0X10000 | (0X1DC),

            /// <summary>
            /// DBI_SPI_EN_CH3[write]
            /// abs-addr:0X101E0; none
            /// reg_hw_name:dbi_spi_en_ch3
            /// bit-width:1 ;  第3块衰减器adrf5720数据发送开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1E0),0x101E0")]
            DBI_atten_DBI_SPI_en_ch3       = 0X10000 | (0X1E0),

            /// <summary>
            /// DBI_SPI_EN_CH4[write]
            /// abs-addr:0X101E4; none
            /// reg_hw_name:dbi_spi_en_ch4
            /// bit-width:1 ;  第4块衰减器adrf5720数据发送开始使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1E4),0x101E4")]
            DBI_atten_DBI_SPI_en_ch4       = 0X10000 | (0X1E4),

            /// <summary>
            /// DBI_SPI_WEN_CH3[write]
            /// abs-addr:0X101E8; none
            /// reg_hw_name:dbi_spi_wen_ch3
            /// bit-width:1 ;  第3块衰减器adrf5720数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1E8),0x101E8")]
            DBI_atten_DBI_SPI_wen_ch3      = 0X10000 | (0X1E8),

            /// <summary>
            /// DBI_SPI_WEN_CH4[write]
            /// abs-addr:0X101EC; none
            /// reg_hw_name:dbi_spi_wen_ch4
            /// bit-width:1 ;  第4块衰减器adrf5720数据写使能：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1EC),0x101EC")]
            DBI_atten_DBI_SPI_wen_ch4      = 0X10000 | (0X1EC),

            /// <summary>
            /// DBI_THROUGH_SEL_CH3[write]
            /// abs-addr:0X101F0; none
            /// reg_hw_name:dbi_through_sel_ch3
            /// bit-width:1 ;  第3块衰减器adrf5720直通（1）、衰减（0）选择
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1F0),0x101F0")]
            DBI_atten_DBI_through_sel_ch3  = 0X10000 | (0X1F0),

            /// <summary>
            /// DBI_THROUGH_SEL_CH4[write]
            /// abs-addr:0X101F4; none
            /// reg_hw_name:dbi_through_sel_ch4
            /// bit-width:1 ;  第4块衰减器adrf5720直通（1）、衰减（0）选择
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X1F4),0x101F4")]
            DBI_atten_DBI_through_sel_ch4  = 0X10000 | (0X1F4),
            #endregion 
            #endregion DBI

            #region====================DBI_FAN=[共1个寄存器]==================================

            /// <summary>
            /// DBI_FAN_ENABLE[write]
            /// abs-addr:0X1019C; none
            /// reg_hw_name:pcie_fan_enable
            /// bit-width:1 ;  风扇使能，用来使能12v供电给混频板：高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X19C),0x1019C")]
            DBI_FAN_DBI_fan_enable         = 0X10000 | (0X19C),
            #endregion DBI_FAN

            #region====================DMADataSource=[共2个寄存器]============================

            /// <summary>
            /// REG_PCIE_FAST_TRANS_EN[write]
            /// abs-addr:0X100E8; 只有1位的状态控制， ; 置1表示使能快速传输,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_fast_trans_en
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0E8),0x100E8")]
            DMADataSource_DdrEnable        = 0X10000 | (0X0E8),

            /// <summary>
            /// REG_PCIE_DPX_EN[write]
            /// abs-addr:0X100EC; 只有1位的状态控制， ; 置1表示打开dpx功能,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_dpx_en
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0EC),0x100EC")]
            DMADataSource_DpxEnable        = 0X10000 | (0X0EC),
            #endregion DMADataSource

            #region====================DataPath=[共1个寄存器]=================================

            /// <summary>
            /// REG_PCIE_LINKDEMUX_SEL[write]
            /// abs-addr:0X100E4; 数据类型选择： ; 0:正常时域数据， ; 1:DPO映射时域数据， ; 2:协议解码数据， ; 3:频域数据， ; 4:快传数据， ; 5:LA数据 ; 默认态:正常时域数据,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_linkdemux_sel
            /// bit-width:16 ;  3bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0E4),0x100E4")]
            DataPath_pcie_linkdemux_select = 0X10000 | (0X0E4),
            #endregion DataPath

            #region====================FPGAFlashUpdater=[共5个寄存器]=========================

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_READSTART[write]
            /// abs-addr:0X10004; none
            /// reg_hw_name:reg_pcie_config_flash_readstart
            /// bit-width:1 ;  启动接收flash的数据，等待时间与spiclock有关。先启动，等待，读数，然后关闭
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X004),0x10004")]
            FPGAFlashUpdater_ReadStart     = 0X10000 | (0X004),

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_SPICLOCK_DIV[write]
            /// abs-addr:0X10008; none
            /// reg_hw_name:reg_pcie_config_flash_spiclock_div
            /// bit-width:16 ;  独热码，指定spi的时钟的分频比
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X008),0x10008")]
            FPGAFlashUpdater_SpiClock      = 0X10000 | (0X008),

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_SS[write]
            /// abs-addr:0X1000C; none
            /// reg_hw_name:reg_pcie_config_flash_ss
            /// bit-width:1 ;  通过spi总线往来传输数据时为1，关闭spi总线时为0，参照flash命令时序图
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X00C),0x1000C")]
            FPGAFlashUpdater_SS            = 0X10000 | (0X00C),

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_WRITEDATA[write]
            /// abs-addr:0X10010; none
            /// reg_hw_name:reg_pcie_config_flash_writedata
            /// bit-width:16 ;  传向flash的数据，每次8bit
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X010),0x10010")]
            FPGAFlashUpdater_WriteData     = 0X10000 | (0X010),

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_WRITESTART[write]
            /// abs-addr:0X10014; none
            /// reg_hw_name:reg_pcie_config_flash_writestart
            /// bit-width:1 ;  启动先flash的数据传输，每次8bit，等待的时间与spiclock有关。先writedata，然后启动传输，之后关闭
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X014),0x10014")]
            FPGAFlashUpdater_WriteStart    = 0X10000 | (0X014),
            #endregion FPGAFlashUpdater

            #region====================FanCtrlPwm=[共5个寄存器]===============================

            /// <summary>
            /// REG_PWM_DUTY_CYCLE[write]
            /// abs-addr:0X10178; PWM波占空比,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pwm_duty_cycle
            /// bit-width:16 ;  pwm波占空比
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X178),0x10178")]
            FanCtrlPwm_RegPwmDutyCycle     = 0X10000 | (0X178),

            /// <summary>
            /// REG_FAN_CTRL_PWM[write]
            /// abs-addr:0X1017C; PWM复位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_fan_ctrl_pwm_rst_pcie
            /// bit-width:16 ;  pwm复位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X17C),0x1017C")]
            FanCtrlPwm_RegFanCtrlPwmRstPcie = 0X10000 | (0X17C),

            /// <summary>
            /// REG_PWM_DUTY_CYCLE_STAIC_PCIE[write]
            /// abs-addr:0X10180; none
            /// reg_hw_name:reg_pwm_duty_cycle_staic_pcie
            /// bit-width:16 ;  20241225:cij 机箱风扇控制，1有效代表开启工控机，0代表开启默认转速
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X180),0x10180")]
            FanCtrlPwm_RegPwmDutyCycleStaicPcie = 0X10000 | (0X180),

            /// <summary>
            /// REG_PWM_CTRL_TX_EN_PCIE[write]
            /// abs-addr:0X10184; none
            /// reg_hw_name:reg_pwm_ctrl_tx_en_pcie
            /// bit-width:16 ;  20241225:cij机箱风扇转速控制使能开关，1有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X184),0x10184")]
            FanCtrlPwm_RegPwmCtrlTxEnPcie  = 0X10000 | (0X184),

            /// <summary>
            /// REG_PWM_THRESHOLD_PCIE[write]
            /// abs-addr:0X10188; none
            /// reg_hw_name:reg_pwm_threshold_pcie
            /// bit-width:16 ;  20241225:cij机箱风扇转速百分比：0~100
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X188),0x10188")]
            FanCtrlPwm_RegPwmThresholdPcie = 0X10000 | (0X188),
            #endregion FanCtrlPwm

            #region====================FifoCtrl=[共4个寄存器]=================================

            /// <summary>
            /// REG_PCIE_CHANNEL_MODE[write]
            /// abs-addr:0X100F0; 通道模式选择，控制pcie板FIFO的满标志判断逻辑,,否,否,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_channel_mode
            /// bit-width:32 ;  3bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0F0),0x100F0")]
            FifoCtrl_ChannelMode           = 0X10000 | (0X0F0),

            /// <summary>
            /// REG_PCIE_RXFIFO_PROGFULL_THRESH[write]
            /// abs-addr:0X100F4; 给pcie_fifo预满数据量， ; 最大为32768，初始化值为28672,,否,是,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_rxfifo_progfull_thresh
            /// bit-width:32 ;  14bits，num_of_pts
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0F4),0x100F4")]
            FifoCtrl_FullProgDepth         = 0X10000 | (0X0F4),

            /// <summary>
            /// REG_PCIE_DATA_RXFIFO_EMPTY_THRESH[write]
            /// abs-addr:0X100F8; 给pcie_fifo空数据量,,否,否,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_data_rxfifo_empty_thresh
            /// bit-width:32 ;  14bits，num_of_pts
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0F8),0x100F8")]
            FifoCtrl_ProgEmpty             = 0X10000 | (0X0F8),

            /// <summary>
            /// REG_PCIE_READ_FIFO_LEN[write]
            /// abs-addr:0X100FC; DMA读取pcie每个FIFO的 ; 数据量,初始化值为16000,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_read_fifo_len
            /// bit-width:32 ;  14bits，num_of_pts
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0FC),0x100FC")]
            FifoCtrl_ReadFromFIFO_Num      = 0X10000 | (0X0FC),
            #endregion FifoCtrl

            #region====================FlashOperator=[共8个寄存器]============================

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_SYS_RST[write]
            /// abs-addr:0X1002C; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_flash_operator_sys_rst
            /// bit-width:16 ;  上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X02C),0x1002C")]
            FlashOperator_ActionReset      = 0X10000 | (0X02C),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_FLASH_WHICH_FLASH[write]
            /// abs-addr:0X10030; none
            /// reg_hw_name:reg_pcie_flash_operator_flash_which_flash
            /// bit-width:16 ;  对只有一块flash的fpga来讲，该值没有意义，赋值为0；对tmc来讲，可能有两个固件要通过一个fpga来烧写，0=fpga本身的固件；1=3014mcu的固件
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X030),0x10030")]
            FlashOperator_WhichFlash       = 0X10000 | (0X030),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_START_ADDR_L16[write]
            /// abs-addr:0X10034; none
            /// reg_hw_name:reg_pcie_flash_operator_start_addr_l16
            /// bit-width:16 ;  操作flash起始地址，,低16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X034),0x10034")]
            FlashOperator_StartAddress_L16 = 0X10000 | (0X034),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_START_ADDR_H16[write]
            /// abs-addr:0X10038; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_flash_operator_start_addr_h16
            /// bit-width:16 ;  操作lash起始地址，,高16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X038),0x10038")]
            FlashOperator_StartAddress_H16 = 0X10000 | (0X038),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_END_ADDR_L16[write]
            /// abs-addr:0X1003C; none
            /// reg_hw_name:reg_pcie_flash_operator_end_addr_l16
            /// bit-width:16 ;  操作flash结束地址,低16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X03C),0x1003C")]
            FlashOperator_EndAddress_L16   = 0X10000 | (0X03C),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_END_ADDR_H16[write]
            /// abs-addr:0X10040; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_flash_operator_end_addr_h16
            /// bit-width:16 ;  操作flash结束地址,高16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X040),0x10040")]
            FlashOperator_EndAddress_H16   = 0X10000 | (0X040),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_ACTION_CODE[write]
            /// abs-addr:0X10044; none
            /// reg_hw_name:reg_pcie_flash_operator_action_code
            /// bit-width:16 ;  业务操作定义：1=读flashid;2=擦除，3=烧写；4=回读。读flashid，通过软件延时读取；其他的操作状态，通过pcie的寄存器读取
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X044),0x10044")]
            FlashOperator_ActionCode       = 0X10000 | (0X044),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_FLASH_ACTION_START[write]
            /// abs-addr:0X10048; Spi16本次后传的数据量（字节数）,高16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_flash_operator_flash_action_start
            /// bit-width:16 ;  上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X048),0x10048")]
            FlashOperator_ActionStart      = 0X10000 | (0X048),
            #endregion FlashOperator

            #region====================Level2Transmit=[共8个寄存器]===========================

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_WHICHSPI[write]
            /// abs-addr:0X10058; none
            /// reg_hw_name:reg_pcie_level2transmit_whichspi
            /// bit-width:16 ;  通过与pcie连接的哪根spi进行传输，各个fpga与cpie的哪个spi相连，硬件确定后，通过软件查找表来做对应
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X058),0x10058")]
            Level2Transmit_WhichSpi        = 0X10000 | (0X058),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_DDR_START_ADDRESS_L16[write]
            /// abs-addr:0X1005C; 0=PCIE,1=PROC,BIT2~BIT7=1,23,4,5,6,7,8Acq板插槽号,从1开始;bit8~bit9,1=TMC的fpga，2=TMC的3014,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_level2transmit_ddr_start_address_l16
            /// bit-width:16 ;  读写pcie的ddr的开始地址，必须是256的整数倍
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X05C),0x1005C")]
            Level2Transmit_DDR_StartAddress_L16 = 0X10000 | (0X05C),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_DDR_START_ADDRESS_H16[write]
            /// abs-addr:0X10060; 0=PCIE,1=PROC,BIT2~BIT7=1,23,4,5,6,7,8Acq板插槽号,从1开始;bit8~bit9,1=TMC的fpga，2=TMC的3014,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_level2transmit_ddr_start_address_h16
            /// bit-width:16 ;  读写pcie的ddr的开始地址，必须是256的整数倍
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X060),0x10060")]
            Level2Transmit_DDR_StartAddress_H16 = 0X10000 | (0X060),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_DDR_TOTAL_BYTES_L16[write]
            /// abs-addr:0X10064; 软件获取FlashID_L16，在读FlashID命令执行完成(ActionStart)后读取,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_level2transmit_ddr_total_bytes_l16
            /// bit-width:16 ;  读写pcie的ddr的总字节数，必须是256的整数倍
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X064),0x10064")]
            Level2Transmit_DDR_TotalBytes_L16 = 0X10000 | (0X064),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_DDR_TOTAL_BYTES_H16[write]
            /// abs-addr:0X10068; 软件获取FlashID_L16，在读FlashID命令执行完成(ActionStart)后读取,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_level2transmit_ddr_total_bytes_h16
            /// bit-width:16 ;  读写pcie的ddr的总字节数，必须是256的整数倍
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X068),0x10068")]
            Level2Transmit_DDR_TotalBytes_H16 = 0X10000 | (0X068),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_DO_WHAT[write]
            /// abs-addr:0X1006C; 软件获取FlashID_H16,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_level2transmit_do_what
            /// bit-width:16 ;  1=烧写flash，2=回读flash,3=传输系数表
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X06C),0x1006C")]
            Level2Transmit_DoWhat          = 0X10000 | (0X06C),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_RESET[write]
            /// abs-addr:0X10070; none
            /// reg_hw_name:reg_pcie_level2transmit_reset
            /// bit-width:1 ;  传输的复位，上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X070),0x10070")]
            Level2Transmit_Reset           = 0X10000 | (0X070),

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_ACTION_START[write]
            /// abs-addr:0X10074; none
            /// reg_hw_name:reg_pcie_level2transmit_action_start
            /// bit-width:1 ;  操作开始，上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X074),0x10074")]
            Level2Transmit_ActionStart     = 0X10000 | (0X074),
            #endregion Level2Transmit

            #region====================PowerManager=[共4个寄存器]=============================

            /// <summary>
            /// REG_PRO_BD_POWER_EN[write]
            /// abs-addr:0X1001C; 处理板上电控制，初始化时发送1上电，0下电,是,,是,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pro_bd_power_en
            /// bit-width:1 ;  1bit，active high ; bit0：power_load_en
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X01C),0x1001C")]
            PowerManager_ProcBoard_Power   = 0X10000 | (0X01C),

            /// <summary>
            /// REG_ACQ_BD_POWER_EN[write]
            /// abs-addr:0X10020; 采集板上电控制，独热码控制对应采集板上电，目前7000X项目只使用了ACQ3，因此发送0x04上电，0x00下电,,,是,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_acq_bd_power_en
            /// bit-width:16 ;  4bit，active high ; bit0：acq1_power_en ; bit1：acq2_power_en ; bit2：acq3_power_en ; bit3：acq4_power_en
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X020),0x10020")]
            PowerManager_AcqBoard_Power    = 0X10000 | (0X020),

            /// <summary>
            /// REG_PCIE_LA_POWER_EN[write]
            /// abs-addr:0X10168; LA上电控制，初始化时发送1上电，0下电,是,,是,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_la_power_en
            /// bit-width:1 ;  pcie板la上电，1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X168),0x10168")]
            PowerManager_LA_Power          = 0X10000 | (0X168),

            /// <summary>
            /// REG_PCIE_EXTTRIG_POWER_EN[write]
            /// abs-addr:0X1016C; 外触发上电控制，初始化时发送1上电，0下电,是,,是,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_exttrig_power_en
            /// bit-width:1 ;  pcie板外触发上电，1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X16C),0x1016C")]
            PowerManager_ExtTrig_Power     = 0X10000 | (0X16C),
            #endregion PowerManager

            #region====================RST_CTRL=[共1个寄存器]=================================

            /// <summary>
            /// REG_PCIE_RESET[write]
            /// abs-addr:0X10100; pcie板卡复位，不输出到处理板， ; 初始化时复位，上升沿有效,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_reset
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X100),0x10100")]
            RST_CTRL_PcieReset             = 0X10000 | (0X100),
            #endregion RST_CTRL

            #region====================RegMonitor=[共1个寄存器]===============================

            /// <summary>
            /// PCIE_READ_WREG_ADDR[write]
            /// abs-addr:0X10024; 读回下发寄存器的值,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_read_wreg_addr
            /// bit-width:16 ;  read back write-register
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X024),0x10024")]
            RegMonitor_RegAddress          = 0X10000 | (0X024),
            #endregion RegMonitor

            #region====================SysInfo=[共1个寄存器]==================================

            /// <summary>
            /// PCIE_REG_READ_BACK[write]
            /// abs-addr:0X10FF8; 16位数据，由此寄存器写入，再由此寄存器读出，两者数据一致，表明上电OK。,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_reg_read_back
            /// bit-width:16 ;  16bits_data
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0XFF8),0x10FF8")]
            SysInfo_WorkOKTest             = 0X10000 | (0XFF8),
            #endregion SysInfo

            #region====================SysMon=[共7个寄存器]===================================

            /// <summary>
            /// REG_PCIE_CT_1820_DRIVER_RST_N[write]
            /// abs-addr:0X10104; ct1820采集板温度传感器模块复位,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_ct_1820_driver_rst_n
            /// bit-width:1 ;  ct1820板上温度传感器模块复位，1bit，低有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X104),0x10104")]
            SysMon_Ct_1820_Driver_Rst_N_pcie = 0X10000 | (0X104),

            /// <summary>
            /// REG_PCIE_SYSMON_RST[write]
            /// abs-addr:0X10108; PCIe卡FPGA温度检测模块复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_sysmon_rst
            /// bit-width:1 ;  pcie卡fpga温度检测模块复位，1bit，高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X108),0x10108")]
            SysMon_Sysmon_Rst              = 0X10000 | (0X108),

            /// <summary>
            /// REG_PRO_CT_1820_DRIVER_RST_N[write]
            /// abs-addr:0X1010C; ct1820采集板温度传感器模块复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pro_ct_1820_driver_rst_n
            /// bit-width:1 ;  ct1820板上温度传感器模块复位，1bit，低有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X10C),0x1010C")]
            SysMon_Ct_1820_Driver_Rst_N_pro = 0X10000 | (0X10C),

            /// <summary>
            /// REG_ACQ1_CT_1820_DRIVER_RST_N[write]
            /// abs-addr:0X10158; ct1820采集板温度传感器模块复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_acq1_ct_1820_driver_rst_n
            /// bit-width:1 ;  ct1820板上温度传感器模块复位，1bit，低有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X158),0x10158")]
            SysMon_Ct_1820_Driver_Rst_N_acq1 = 0X10000 | (0X158),

            /// <summary>
            /// REG_ACQ2_CT_1820_DRIVER_RST_N[write]
            /// abs-addr:0X1015C; ct1820采集板温度传感器模块复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_acq2_ct_1820_driver_rst_n
            /// bit-width:1 ;  ct1820板上温度传感器模块复位，1bit，低有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X15C),0x1015C")]
            SysMon_Ct_1820_Driver_Rst_N_acq2 = 0X10000 | (0X15C),

            /// <summary>
            /// REG_ADC_R_CT_1820_DRIVER_RST_N[write]
            /// abs-addr:0X10160; ct1820采集板温度传感器模块复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_adc_r_ct_1820_driver_rst_n
            /// bit-width:1 ;  ct1820板上温度传感器模块复位，1bit，低有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X160),0x10160")]
            SysMon_Ct_1820_Driver_Rst_N_adc_r = 0X10000 | (0X160),

            /// <summary>
            /// REG_ADC_M_CT_1820_DRIVER_RST_N[write]
            /// abs-addr:0X10164; ct1820采集板温度传感器模块复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_adc_m_ct_1820_driver_rst_n
            /// bit-width:1 ;  ct1820板上温度传感器模块复位，1bit，低有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X164),0x10164")]
            SysMon_Ct_1820_Driver_Rst_N_adc_m = 0X10000 | (0X164),
            #endregion SysMon

            #region====================Test=[共1个寄存器]=====================================

            /// <summary>
            /// REG_PCIE_TEST_DATA_MODE[write]
            /// abs-addr:0X10194; none
            /// reg_hw_name:reg_pcie_test_data_mode
            /// bit-width:16 ;  [0]1-testmode
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X194),0x10194")]
            Test_PcieTestDataMode          = 0X10000 | (0X194),
            #endregion Test

            #region====================TrigCtrl=[共4个寄存器,1个子组]==================================== =
            #region====================viedo=[共4寄存器]===============================================

            /// <summary>
            /// VIDEO_TRI_SYNC_NUMBER[write]
            /// abs-addr:0X10110; 视频触发同步设置,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:video_tri_sync_number
            /// bit-width:16 ;  视频触发同步设置
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X110),0x10110")]
            TrigCtrl_viedo_SyncNumber      = 0X10000 | (0X110),

            /// <summary>
            /// VIDEO_TRI_CUSTOM_HORIZONTAL[write]
            /// abs-addr:0X10114; 视频触发同步设置,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:video_tri_custom_horizontal
            /// bit-width:16 ;  视频触发同步设置
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X114),0x10114")]
            TrigCtrl_viedo_CustomHorizontal = 0X10000 | (0X114),

            /// <summary>
            /// VIDEO_TRI_TRIG_MODE[write]
            /// abs-addr:0X10118; 视频触发模式控制,有奇偶场触发  固定行触发  任意行触发,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:video_tri_trig_mode
            /// bit-width:16 ;  0:任意行触发 1:指定行触发 2:偶场触发  3:奇场触发  4;任意触发
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X118),0x10118")]
            TrigCtrl_viedo_TrigMode        = 0X10000 | (0X118),

            /// <summary>
            /// VIDEO_TRI_VIDEO_MODE[write]
            /// abs-addr:0X1011C; 视频触发制式控制是输入信号制式  NTSC  PAL 等,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:video_tri_video_mode
            /// bit-width:16 ;  0:ntsc /480i  ;1:pal/secam /576i ;2:480p ;3:576p  ; 4:720p     5:custom    6: 1080i    7:1080p
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X11C),0x1011C")]
            TrigCtrl_viedo_VideoMode       = 0X10000 | (0X11C),
            #endregion 
            #endregion TrigCtrl

            #region====================Xdma=[共3个寄存器]=====================================

            /// <summary>
            /// REG_XDMA_IRQ_RESET[write]
            /// abs-addr:0X10028; Xdma的中断复位,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_xdma_irq_reset
            /// bit-width:1 ;  高电平有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X028),0x10028")]
            Xdma_XdmaIrqReset              = 0X10000 | (0X028),

            /// <summary>
            /// REG_SAMPLE_MODE_PCIE[write]
            /// abs-addr:0X10120; 采集模式控制,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_sample_mode_pcie
            /// bit-width:16 ;  [5:0] 6bit： ; [1:0]：00非插值；01插值；10 scan档 ; [4:2]：001 2.5g采样率；010 5g采样率； 100 10g采样率 ; [8:5]：独热码控制通道开关， ; [5]：ch1开 ; [6]：ch2开 ; [7]：ch3开 ; [8]：ch4开
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X120),0x10120")]
            Xdma_SamplingModePcie          = 0X10000 | (0X120),

            /// <summary>
            /// REG_PASS_FAIL_WARN[write]
            /// abs-addr:0X10128; 是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pass_fail_warn
            /// bit-width:1 ;  pass\fail测试结果告警警报
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X128),0x10128")]
            Xdma_PassFailWarn              = 0X10000 | (0X128),

            /// <summary>
            /// REG_PCIE_XDMA_FIFO_PROG_FULL_THRESH_H[write]
            /// abs-addr:0X10230; HCJ 20251229,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_xdma_fifo_prog_full_thresh_h
            /// bit-width:16 ;  xdma 内部fifo 可编程满设置[31:16]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X230),0x10230")]
            Xdma_FifoProgFullThreshH       = 0X10000 | (0X230),

            /// <summary>
            /// REG_PCIE_XDMA_FIFO_PROG_FULL_THRESH_L[write]
            /// abs-addr:0X10234; HCJ 20251229,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_xdma_fifo_prog_full_thresh_l
            /// bit-width:16 ;  xdma 内部fifo 可编程满设置[15:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X234),0x10234")]
            Xdma_FifoProgFullThreshL       = 0X10000 | (0X234),

            /// <summary>
            /// REG_XDMA_DATA_NUM[write]
            /// abs-addr:0X10238; HCJ 20251229,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_xdma_data_num
            /// bit-width:32 ;  pcie数据量，以32k为单位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X238),0x10238")]
            Xdma_DataNum                   = 0X10000 | (0X238),

            /// <summary>
            /// REG_XDMA_WR_REVERSE0[write]
            /// abs-addr:0X1023C; HCJ 20251229,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_xdma_wr_reverse0
            /// bit-width:32 ;  reverse write
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X23C),0x1023C")]
            Xdma_WrReverse0                = 0X10000 | (0X23C),
            #endregion Xdma

            #region====================awg=[共1个寄存器]======================================

            /// <summary>
            /// REG_AWG_PWR_CTRL[write]
            /// abs-addr:0X10124; AWG上电,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_awg_pwr_ctrl
            /// bit-width:16 ;  [0]: 高电平开启
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X124),0x10124")]
            awg_AwgPowerEn                 = 0X10000 | (0X124),
            #endregion awg

            #region====================ext_10m=[共1个寄存器]==================================

            /// <summary>
            /// REG_EXT_10M_SEL_PCIE[write]
            /// abs-addr:0X1018C; none
            /// reg_hw_name:reg_ext_10m_sel_pcie
            /// bit-width:16 ;  1-ext
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X18C),0x1018C")]
            ext_10m_SelectPcie             = 0X10000 | (0X18C),
            #endregion ext_10m

            #region====================test=[共1个寄存器]=====================================

            /// <summary>
            /// REG_TEST_DATA_SWITCH_PCIE[write]
            /// abs-addr:0X10198; none
            /// reg_hw_name:reg_test_data_switch_pcie
            /// bit-width:16 ;  pcie测试数据
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X198),0x10198")]
            test_TestDataSwitchPcie        = 0X10000 | (0X198),
            #endregion test

            #region====================DMA_Ctrl=[共5个寄存器]=================================

            /// <summary>
            /// USER_NUMBER[write]
            /// abs-addr:0X8050; 在每次DMA读之前，先发送，因为其他地方可能修改了此值。字节数，需为XXX的整数倍。需要根据业务情况而设置。,,,,,
            /// reg_hw_name:user_number
            /// bit-width:32 ;  32bits，num_of_pts
            /// </summary>
            [RegAttribute(Description = "0X0000 | (0X8050),0x8050")]
            ReadTotalBytes                 = 0X0000 | (0X8050),

            /// <summary>
            /// DMAWR_NUMBER[write]
            /// abs-addr:0X8054; 在每次DMA写之前，先发送，因为其他地方可能修改了此值。字节数，需为XXX的整数倍。需要根据业务情况而设置。,,,,,
            /// reg_hw_name:DmaWr_number
            /// bit-width:32 ;  32bits，num_of_pts
            /// </summary>
            [RegAttribute(Description = "0X0000 | (0X8054),0x8054")]
            WriteTotalBytes                = 0X0000 | (0X8054),

            /// <summary>
            /// INTERRUPT_CONTROL[write]
            /// abs-addr:0X8108; DMA中断控制信号，只有中断控制信号和中断请求信号同时为1的时候才能令中断状态信号为1，中断状态信号通过寄存器读回。,,,,,
            /// reg_hw_name:interrupt_control
            /// bit-width:32 ;  32bits，Active high
            /// </summary>
            [RegAttribute(Description = "0X0000 | (0X8108),0x8108")]
            InterruptControl               = 0X0000 | (0X8108),

            /// <summary>
            /// FRAMEIN_CONTROL0[write]
            /// abs-addr:0X8188; 需要根据业务情况而设置。目前只有0和1选择，其中0表示读采集板的数据，1表示读DPO的数据。,,,,,
            /// reg_hw_name:framein_control0
            /// bit-width:16 ;  16bits，0：ACQ_data，1：DPO_data
            /// </summary>
            [RegAttribute(Description = "0X0000 | (0X8188),0x8188")]
            ReadFromAcqOrDpo               = 0X0000 | (0X8188),

            /// <summary>
            /// FRAMEOUT_CONTROL0[write]
            /// abs-addr:0X81C8;,,,,,
            /// reg_hw_name:frameout_control0
            /// bit-width:16 ;  16bits，
            /// </summary>
            [RegAttribute(Description = "0X0000 | (0X81C8),0x81C8")]
            DMAFrameoutControl             = 0X0000 | (0X81C8),
            #endregion DMA_Ctrl
        }
        /// <summary>
        ///共有[61]个,其中[0]个没有使用。
        /// </summary>
        public enum R
        {

            #region====================AnalogChCtrl=[共8个寄存器]=============================

            /// <summary>
            /// REG_READPROBEINFOFROMFPGA_TOTALBYTECOUNT[read]
            /// abs-addr:0X1008C; none
            /// reg_hw_name:reg_rd_probe_info_from_fpga_byte_count
            /// bit-width:16 ;  探头信息的总字节数
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X08C),0x1008C")]
            AnalogChCtrl_ReadProbeInfoFromFPGA_TotalByteCount = 0X10000 | (0X08C),

            /// <summary>
            /// REG_READPROBEINFOFROMFPGA_DATA[read]
            /// abs-addr:0X10090; none
            /// reg_hw_name:reg_rd_probe_info_from_fpga_data
            /// bit-width:16 ;  读取的探头信息指定字节位置的一个字节
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X090),0x10090")]
            AnalogChCtrl_ReadProbeInfoFromFPGA_Data = 0X10000 | (0X090),

            /// <summary>
            /// REG_READCHANNELTEMPERATURE[read]
            /// abs-addr:0X10094; none
            /// reg_hw_name:reg_rd_ch_temperature
            /// bit-width:16 ;  读取通道的温度，其中低8位位第一个温度，高8位为第二温度
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X094),0x10094")]
            AnalogChCtrl_ReadChannelTemperature = 0X10000 | (0X094),

            /// <summary>
            /// REG_READPROBESTATUS[read]
            /// abs-addr:0X10098; none
            /// reg_hw_name:reg_rd_probe_status
            /// bit-width:16 ;  读取探头插入及按钮状态。高8位为按钮事件，0表示没有按下，1表示按下。低8位为探头的插入状态。0表示没有插入，1表示插入。低位到高位分别表示通道1、通道2.也就是最多支持8个通道
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X098),0x10098")]
            AnalogChCtrl_ReadProbeStatus   = 0X10000 | (0X098),

            /// <summary>
            /// RO_CH_TEMP_READ_L[read]
            /// abs-addr:0X100E4; 通道串口数据读取,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:ro_ch_temp_read_l
            /// bit-width:16 ;  通道串口数据回读低16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0E4),0x100E4")]
            AnalogChCtrl_CH_temp_L         = 0X10000 | (0X0E4),

            /// <summary>
            /// RO_CH_TEMP_READ_H[read]
            /// abs-addr:0X100E8; 通道串口数据读取,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:ro_ch_temp_read_h
            /// bit-width:16 ;  通道串口数据回读高16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0E8),0x100E8")]
            AnalogChCtrl_CH_temp_H         = 0X10000 | (0X0E8),


            #endregion AnalogChCtrl

            #region====================BoardSync=[共2个寄存器]================================

            /// <summary>
            /// REG_SCAN_RESULT_PCIE[read]
            /// abs-addr:0X10084; 扫窗结果的回读值，与pattern长度相关（处理板pattern长度为16）取数通常为“log2(patttern长度)+1“。当回读值为全1时，标明该状态扫窗失败，否则则表示当前扫窗成功，并且回读数为pattern移位的对应值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_scan_result_pcie
            /// bit-width:16 ;  [4:0]5bit：处理板用到[4:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X084),0x10084")]
            BoardSync_Scan_Result          = 0X10000 | (0X084),

            /// <summary>
            /// REG_SCAN_FINISH_PCIE[read]
            /// abs-addr:0X10088; 扫窗完成的标志位,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_scan_finish_pcie
            /// bit-width:1 ;  1bit
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X088),0x10088")]
            BoardSync_Scan_Finish          = 0X10000 | (0X088),
            #endregion BoardSync

            #region====================Debug=[共2个寄存器]====================================

            /// <summary>
            /// REG_PCIE_DATA_COUNT_H16[read]
            /// abs-addr:0X100B8; debug使用,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_data_count_h16
            /// bit-width:16 ;  pcie板数据记录高16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0B8),0x100B8")]
            Debug_PcieDataCountH16         = 0X10000 | (0X0B8),

            /// <summary>
            /// REG_PCIE_DATA_COUNT_L16[read]
            /// abs-addr:0X100BC; debug使用,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_data_count_l16
            /// bit-width:16 ;  pcie数据记录低16位
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0BC),0x100BC")]
            Debug_PcieDataCountL16         = 0X10000 | (0X0BC),
            #endregion Debug

            #region====================FPGAFlashUpdater=[共2个寄存器]=========================

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_READDATA[read]
            /// abs-addr:0X10004; none
            /// reg_hw_name:reg_pcie_config_flash_readdata
            /// bit-width:16 ;  flash返回的数据，每次8bit
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X004),0x10004")]
            FPGAFlashUpdater_ReadData      = 0X10000 | (0X004),

            /// <summary>
            /// REG_PCIE_CONFIG_FLASH_UPDATEFLAG[read]
            /// abs-addr:0X10008; 用与上位机区分Golden版本固件和update版本固件,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_config_flash_updateflag
            /// bit-width:16 ;  上电就发0xaa，代表update更新成功
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X008),0x10008")]
            FPGAFlashUpdater_UpdateFlag    = 0X10000 | (0X008),
            #endregion FPGAFlashUpdater

            #region====================FanCtrlPwm=[共1个寄存器]===============================

            /// <summary>
            /// RO_FAN_RUN_SPPED[read]
            /// abs-addr:0X100DC; 回读风扇转速,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:ro_fan_run_spped
            /// bit-width:32 ;  回读风扇转速
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0DC),0x100DC")]
            FanCtrlPwm_ReadFanRunSpped     = 0X10000 | (0X0DC),
            #endregion FanCtrlPwm

            #region====================FifoCtrl=[共1个寄存器]=================================

            /// <summary>
            /// REG_PCIE_DATA_RXFIFO_FULL[read]
            /// abs-addr:0X1009C; pcie缓存FIFO编程满标志,,否,否,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_data_rxfifo_full
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X09C),0x1009C")]
            FifoCtrl_FullFlag              = 0X10000 | (0X09C),
            #endregion FifoCtrl

            #region====================FlashOperator=[共3个寄存器]============================

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_FLASH_ACTION_STATUS[read]
            /// abs-addr:0X10074; none
            /// reg_hw_name:reg_pcie_flash_operator_flash_action_status
            /// bit-width:16 ;  操作状态。2bit:bit0=是否完成，1表示完成；bit1=是否有错，1=有错误
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X074),0x10074")]
            FlashOperator_ActionStatus     = 0X10000 | (0X074),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_FLASH_ID_L16[read]
            /// abs-addr:0X10078; 软件获取FlashID_L16，在读FlashID命令执行完成(ActionStart)后读取,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_flash_operator_flash_id_l16
            /// bit-width:16 ;  软件获取flashid_l16，在读flashid命令执行完成(actionstart)后读取
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X078),0x10078")]
            FlashOperator_FlashID_L16      = 0X10000 | (0X078),

            /// <summary>
            /// REG_PCIE_FLASH_OPERATOR_FLASH_ID_H16[read]
            /// abs-addr:0X1007C; 软件获取FlashID_H16,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_flash_operator_flash_id_h16
            /// bit-width:16 ;  软件获取flashid_h16
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X07C),0x1007C")]
            FlashOperator_FlashID_H16      = 0X10000 | (0X07C),
            #endregion FlashOperator

            #region====================Level2Transmit=[共1个寄存器]===========================

            /// <summary>
            /// REG_PCIE_LEVEL2TRANSMIT_ACTION_STATUS[read]
            /// abs-addr:0X10080; none
            /// reg_hw_name:reg_pcie_level2transmit_action_status
            /// bit-width:2 ;  查询本次2级传输以及后端处理的完成状态。bit1=有错误否，1表示有错误；bit0=完成否，1=完成
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X080),0x10080")]
            Level2Transmit_ActionStatus    = 0X10000 | (0X080),
            #endregion Level2Transmit

            #region====================RegMonitor=[共1个寄存器]===============================

            /// <summary>
            /// PCIE_READ_WREG_DATA[read]
            /// abs-addr:0X1000C; 读回下发寄存器的值,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_read_wreg_data
            /// bit-width:16 ;  read back write-register
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X00C),0x1000C")]
            RegMonitor_ReadbackValue       = 0X10000 | (0X00C),
            #endregion RegMonitor

            #region====================SysInfo=[共1个寄存器]==================================

            /// <summary>
            /// PCIE_REG_READ_BACK[read]
            /// abs-addr:0X10FF8; 16位数据，由此寄存器写入，再由此寄存器读出，两者数据一致，表明上电OK。,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_reg_read_back
            /// bit-width:16 ;  16bits_data
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0XFF8),0x10FF8")]
            SysInfo_WorkOKTest             = 0X10000 | (0XFF8),
            #endregion SysInfo

            #region====================SysMon=[共13个寄存器]==================================

            /// <summary>
            /// REG_PCIE_CT_1820_DRIVER_TEMP_DATA[read]
            /// abs-addr:0X100A0; 公式 temprature(℃) =temp_data*0.0625，temp_data为返回值，最高位表示温度的符号（并非符号位）,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_ct_1820_driver_temp_data
            /// bit-width:16 ;  ct1820板上温度传感器模块温度回读接口，当前11bit ; 1/0（正温或负温）zzz_z[xxx_xxxx_xxxx(温度值)]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0A0),0x100A0")]
            SysMon_Ct_1820_Driver_Temp_Data = 0X10000 | (0X0A0),

            /// <summary>
            /// REG_PCIE_SYSMON_TEMPERATURE[read]
            /// abs-addr:0X100A4; 公式 temprature(℃) = (ADC_CODE * 501.3743) / 1024 -273.6777 其中，ADC_CODE对应temprature寄存器中的值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_sysmon_temperature
            /// bit-width:16 ;  pcie卡fpga温度检测模块温度回读接口，当前为11bit，[10:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0A4),0x100A4")]
            SysMon_Sysmon_Temperature      = 0X10000 | (0X0A4),

            /// <summary>
            /// REG_PCIE_SYSMON_VCCINT[read]
            /// abs-addr:0X100A8; 公式vccint(V)   = ADC_CODE  / 1024 * 3 其中,ADC_CODE对应vccint寄存器中的值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_sysmon_vccint
            /// bit-width:16 ;  pcie卡fpga温度检测模块电压回读接口，当前为11bit，[10:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0A8),0x100A8")]
            SysMon_Sysmon_Vccint           = 0X10000 | (0X0A8),

            /// <summary>
            /// REG_PCIE_SYSMON_VCCAUX[read]
            /// abs-addr:0X100AC; 公式vccaux(V) = ADC_CODE  / 1024 * 3 其中,ADC_CODE对应vccaux寄存器中的值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_sysmon_vccaux
            /// bit-width:16 ;  pcie卡fpga温度检测模块电压回读接口，当前为11bit，[10:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0AC),0x100AC")]
            SysMon_Sysmon_Vccaux           = 0X10000 | (0X0AC),

            /// <summary>
            /// REG_PCIE_SYSMON_VCCBRAM[read]
            /// abs-addr:0X100B0; 公式vccbram(V)= ADC_CODE  / 1024 * 3 其中,ADC_CODE对应vccbram寄存器中的值,是,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_sysmon_vccbram
            /// bit-width:16 ;  pcie卡fpga温度检测模块电压回读接口，当前为11bit，[10:0]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0B0),0x100B0")]
            SysMon_Sysmon_Vccbram          = 0X10000 | (0X0B0),

            /// <summary>
            /// REG_PRO_CT_1820_DRIVER_TEMP_DATA[read]
            /// abs-addr:0X100B4; 公式 temprature(℃) =temp_data*0.0625，temp_data为返回值，最高位表示温度的符号（并非符号位）,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pro_ct_1820_driver_temp_data
            /// bit-width:16 ;  ct1820板上温度传感器模块温度回读接口，当前11bit ; 1/0（正温或负温）zzz_z[xxx_xxxx_xxxx(温度值)]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0B4),0x100B4")]
            SysMon_Ct_1820_Driver_Temp_Data_pro = 0X10000 | (0X0B4),

            /// <summary>
            /// REG_HARDWARE_VERSION[read]
            /// abs-addr:0X100C0; 硬件版本信息，V3,V4,V5,V6,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hardware_version
            /// bit-width:16 ;  硬件版本信息，bit[2:0]对应fpga引脚al29,am29,an29
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0C0),0x100C0")]
            SysMon_HardwareVersion         = 0X10000 | (0X0C0),

            /// <summary>
            /// REG_PCIE_PLL_LOCKED[read]
            /// abs-addr:0X100C4; 7044和7043锁定状态,[7:0]7044锁定，[15:8]7043锁定状态,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_pll_locked
            /// bit-width:16 ;  7044和7043锁定状态,[7:0]7044锁定，[15:8]7043锁定状态
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0C4),0x100C4")]
            SysMon_Pcie_Pll_Locked         = 0X10000 | (0X0C4),

            /// <summary>
            /// REG_ACQ1_CT_1820_DRIVER_TEMP_DATA[read]
            /// abs-addr:0X100C8; 公式 temprature(℃) =temp_data*0.0625，temp_data为返回值，最高位表示温度的符号（并非符号位）,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_acq1_ct_1820_driver_temp_data
            /// bit-width:16 ;  ct1820板上温度传感器模块温度回读接口，当前11bit ; 1/0（正温或负温）zzz_z[xxx_xxxx_xxxx(温度值)]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0C8),0x100C8")]
            SysMon_Ct_1820_Driver_Temp_Data_acq1 = 0X10000 | (0X0C8),

            /// <summary>
            /// REG_ACQ2_CT_1820_DRIVER_TEMP_DATA[read]
            /// abs-addr:0X100CC; 公式 temprature(℃) =temp_data*0.0625，temp_data为返回值，最高位表示温度的符号（并非符号位）,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_acq2_ct_1820_driver_temp_data
            /// bit-width:16 ;  ct1820板上温度传感器模块温度回读接口，当前11bit ; 1/0（正温或负温）zzz_z[xxx_xxxx_xxxx(温度值)]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0CC),0x100CC")]
            SysMon_Ct_1820_Driver_Temp_Data_acq2 = 0X10000 | (0X0CC),

            /// <summary>
            /// REG_ADC_R_CT_1820_DRIVER_TEMP_DATA[read]
            /// abs-addr:0X100D0; 公式 temprature(℃) =temp_data*0.0625，temp_data为返回值，最高位表示温度的符号（并非符号位）,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_adc_r_ct_1820_driver_temp_data
            /// bit-width:16 ;  ct1820板上温度传感器模块温度回读接口，当前11bit ; 1/0（正温或负温）zzz_z[xxx_xxxx_xxxx(温度值)]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0D0),0x100D0")]
            SysMon_Ct_1820_Driver_Temp_Data_adc_r = 0X10000 | (0X0D0),

            /// <summary>
            /// REG_ADC_M_CT_1820_DRIVER_TEMP_DATA[read]
            /// abs-addr:0X100D4; 公式 temprature(℃) =temp_data*0.0625，temp_data为返回值，最高位表示温度的符号（并非符号位）,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_adc_m_ct_1820_driver_temp_data
            /// bit-width:16 ;  ct1820板上温度传感器模块温度回读接口，当前11bit ; 1/0（正温或负温）zzz_z[xxx_xxxx_xxxx(温度值)]
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0D4),0x100D4")]
            SysMon_Ct_1820_Driver_Temp_Data_adc_m = 0X10000 | (0X0D4),

            /// <summary>
            /// REG_PCIE_INSTRUCTION_FIFO_EMPTY[read]
            /// abs-addr:0X100D8; PCIE板指令系统fifo空标志，高有效,是,,是,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_instruction_fifo_empty
            /// bit-width:1 ;  pcie板指令系统fifo空标志，高有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0D8),0x100D8")]
            SysMon_InstructionFifoEmpty    = 0X10000 | (0X0D8),
            #endregion SysMon

            #region====================VersionInfo=[共20个寄存器]=============================

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD0[read]
            /// abs-addr:0X10010; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word0
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X010),0x10010")]
            VersionInfo_CommentWord0       = 0X10000 | (0X010),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD1[read]
            /// abs-addr:0X10014; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word1
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X014),0x10014")]
            VersionInfo_CommentWord1       = 0X10000 | (0X014),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD10[read]
            /// abs-addr:0X10018; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word10
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X018),0x10018")]
            VersionInfo_CommentWord10      = 0X10000 | (0X018),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD11[read]
            /// abs-addr:0X1001C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word11
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X01C),0x1001C")]
            VersionInfo_CommentWord11      = 0X10000 | (0X01C),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD12[read]
            /// abs-addr:0X10020; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word12
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X020),0x10020")]
            VersionInfo_CommentWord12      = 0X10000 | (0X020),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD13[read]
            /// abs-addr:0X10024; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word13
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X024),0x10024")]
            VersionInfo_CommentWord13      = 0X10000 | (0X024),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD2[read]
            /// abs-addr:0X10030; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word2
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X030),0x10030")]
            VersionInfo_CommentWord2       = 0X10000 | (0X030),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD3[read]
            /// abs-addr:0X10034; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word3
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X034),0x10034")]
            VersionInfo_CommentWord3       = 0X10000 | (0X034),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD4[read]
            /// abs-addr:0X10038; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word4
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X038),0x10038")]
            VersionInfo_CommentWord4       = 0X10000 | (0X038),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD5[read]
            /// abs-addr:0X1003C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word5
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X03C),0x1003C")]
            VersionInfo_CommentWord5       = 0X10000 | (0X03C),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD6[read]
            /// abs-addr:0X10040; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word6
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X040),0x10040")]
            VersionInfo_CommentWord6       = 0X10000 | (0X040),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD7[read]
            /// abs-addr:0X10044; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word7
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X044),0x10044")]
            VersionInfo_CommentWord7       = 0X10000 | (0X044),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD8[read]
            /// abs-addr:0X10048; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word8
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X048),0x10048")]
            VersionInfo_CommentWord8       = 0X10000 | (0X048),

            /// <summary>
            /// PCIE_VERSION_COMMENT_WORD9[read]
            /// abs-addr:0X1004C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_comment_word9
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X04C),0x1004C")]
            VersionInfo_CommentWord9       = 0X10000 | (0X04C),

            /// <summary>
            /// PCIE_VERSION_DESIGNER_WORD0[read]
            /// abs-addr:0X10058; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_designer_word0
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X058),0x10058")]
            VersionInfo_DesignerWord0      = 0X10000 | (0X058),

            /// <summary>
            /// PCIE_VERSION_DESIGNER_WORD1[read]
            /// abs-addr:0X1005C; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_designer_word1
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X05C),0x1005C")]
            VersionInfo_DesignerWord1      = 0X10000 | (0X05C),

            /// <summary>
            /// PCIE_VERSION_DESIGNER_WORD2[read]
            /// abs-addr:0X10060; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_designer_word2
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X060),0x10060")]
            VersionInfo_DesignerWord2      = 0X10000 | (0X060),

            /// <summary>
            /// PCIE_VERSION_DESIGNER_WORD3[read]
            /// abs-addr:0X10064; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_designer_word3
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X064),0x10064")]
            VersionInfo_DesignerWord3      = 0X10000 | (0X064),

            /// <summary>
            /// PCIE_VERSION_VERSION_WORD0[read]
            /// abs-addr:0X10068; 版本信息，版本号,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_version_word0
            /// bit-width:16 ;  low_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X068),0x10068")]
            VersionInfo_VersionWord0       = 0X10000 | (0X068),

            /// <summary>
            /// PCIE_VERSION_VERSION_WORD1[read]
            /// abs-addr:0X1006C; 版本信息，版本号,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pcie_version_version_word1
            /// bit-width:16 ;  high_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X06C),0x1006C")]
            VersionInfo_VersionWord1       = 0X10000 | (0X06C),
            #endregion VersionInfo

            #region====================VersionInfo1=[共4个寄存器]=============================

            /// <summary>
            /// REG_PCIE_VERSION_COMMENT_WORD14[read]
            /// abs-addr:0X10028; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_version_comment_word14
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X028),0x10028")]
            VersionInfo1_CommentWord14     = 0X10000 | (0X028),

            /// <summary>
            /// REG_PCIE_VERSION_COMMENT_WORD15[read]
            /// abs-addr:0X1002C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_version_comment_word15
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X02C),0x1002C")]
            VersionInfo1_CommentWord15     = 0X10000 | (0X02C),

            /// <summary>
            /// REG_PCIE_VERSION_TIME_WORD0[read]
            /// abs-addr:0X10050; 版本信息，编译时间,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_version_time_word0
            /// bit-width:16 ;  low_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X050),0x10050")]
            VersionInfo1_CompileTimeWord0  = 0X10000 | (0X050),

            /// <summary>
            /// REG_PCIE_VERSION_TIME_WORD1[read]
            /// abs-addr:0X10054; 版本信息，编译时间,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_pcie_version_time_word1
            /// bit-width:16 ;  high_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X054),0x10054")]
            VersionInfo1_CompileTimeWord1  = 0X10000 | (0X054),
            #endregion VersionInfo1

            #region====================Xdma=[共1个寄存器]=====================================

            /// <summary>
            /// REG_XDMA_WR_FINISH[read]
            /// abs-addr:0X10070; Xdma的中断标识，用于查询XDMA数据是否存满,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_xdma_wr_finish
            /// bit-width:1 ;  高电平有效
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X070),0x10070")]
            Xdma_XdmaWrFinish              = 0X10000 | (0X070),
            #endregion Xdma

            #region====================ext_10m=[共1个寄存器]==================================

            /// <summary>
            /// RO_EXT_10M_LOCK_STATUS_PCIE[read]
            /// abs-addr:0X100E0; none
            /// reg_hw_name:ro_ext_10m_lock_status_pcie
            /// bit-width:16 ;  1-lock
            /// </summary>
            [RegAttribute(Description = "0X10000 | (0X0E0),0x100E0")]
            ext_10m_LockStatusReadPcie     = 0X10000 | (0X0E0),
            #endregion ext_10m
        }
    }
}

