#version 450
#extension GL_KHR_vulkan_glsl : enable
//glsl在计算时都是按vec4进行，小于vec4时，多余的部分会被抛弃
//比如计算float时，glsl实际是按vec4进行计算器，然后只返回第一个值
//就是说在此情况下时，显卡会浪费掉3/4的计算性能
layout(set=0,binding =0) buffer DataBuffer
{
    ivec4 Datas[]; 
};
layout(set=1,binding=0) uniform Info
{
    int Value;
    ivec3 Spare;
};
layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    Datas[index]= Datas[index]+Value;
}
