using System;

namespace ScopeX.Hardware.Driver
{
    //This File is Auto Generated By FPGAViewerSimpleness.exe At Computer[LAPTOP-VQA0GT4T] ,2025.03.13 09:21:26
    //Source File Name = C:\Users\Lenovo\Desktop\deleteMe\8000X_20250311_1517_NEW_TRIG\8000X_20250311_1517_NEW_TRIG\s6_registers.v
    //Source File Last Auto GeneratedTime=2025-03-11 15:17:47
    //Source File LastWritedTime = 2025.03.11 15:17:47


    ///<see href="file:///D:\wangcj\github\Work\WindowsFormsAppNetCore_ScopeX\ToolChain\FPGAViewerSimpleness\s6_registers\JPO6000_Doc_SoftwareRegister_S6Bd.html"></see>
    ///<see href="file:///D:\wangcj\github\Work\WindowsFormsAppNetCore_ScopeX\ToolChain\FPGAViewerSimpleness\s6_registers\images\s6_registers.png "></see>

    /// <summary>
    ///共有[55]个寄存器，其中写寄存器[24]个，没有用到的共[0]，读寄存器[31个]，没有用到的共[0]个.
    ///FPGA中还有[0]个定义的寄存器在软件中没有使用。
    ///在本文件中出现[todo...]字样的地方需要注意使用，并尽量与硬件人员一起完善。
    /// </summary>
    internal partial class S6BdReg
    {
        /// <summary>
        ///共有[24]个,其中[0]没有使用.
        /// </summary>
        public enum W
        {
            #region====================CoefficientsTable=[共3个寄存器]========================

            /// <summary>
            /// REG_S6_COEFFICIENTSTABLE_RESET[write]
            /// abs-addr:0X2002C; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_coefficientstable_reset
            /// bit-width:16 ;  复位，上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00B << 2),0x2002C")]
            CoefficientsTable_Reset        = 0X20000 | (0X00B << 2),

            /// <summary>
            /// REG_S6_COEFFICIENTSTABLE_ACTION_CODE[write]
            /// abs-addr:0X20030; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_coefficientstable_action_code
            /// bit-width:16 ;  干什么|什么系数：低4位表示什么系数，1=afc系数；高4位表示干什么，1=写入；2=读回
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00C << 2),0x20030")]
            CoefficientsTable_ActionCode   = 0X20000 | (0X00C << 2),

            /// <summary>
            /// REG_S6_COEFFICIENTSTABLE_ACTION_START[write]
            /// abs-addr:0X20034; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_coefficientstable_action_start
            /// bit-width:16 ;  操作开始，上升沿有效，其状态通过pcie的寄存器读取
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00D << 2),0x20034")]
            CoefficientsTable_ActionStart  = 0X20000 | (0X00D << 2),
            #endregion CoefficientsTable

            #region====================DCM_CTRL=[共1个寄存器]=================================

            /// <summary>
            /// REG_S6_DCM_RST[write]
            /// abs-addr:0X20038; 使能后发送的32位数据的低16位,,否,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_dcm_rst
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00E << 2),0x20038")]
            DCM_CTRL_s6_dcm_rst            = 0X20000 | (0X00E << 2),
            #endregion DCM_CTRL

            #region====================FlashOperator=[共8个寄存器]============================

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_SYS_RST[write]
            /// abs-addr:0X2000C; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_sys_rst
            /// bit-width:16 ;  上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X003 << 2),0x2000C")]
            FlashOperator_ActionReset      = 0X20000 | (0X003 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_WHICH_FLASH[write]
            /// abs-addr:0X20010; 2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_which_flash
            /// bit-width:16 ;  对只有一块flash的fpga来讲，该值没有意义，赋值为0；对tmc来讲，可能有两个固件要通过一个fpga来烧写，0=fpga本身的固件；1=3014mcu的固件
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X004 << 2),0x20010")]
            FlashOperator_WhichFlash       = 0X20000 | (0X004 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_START_ADDR_L16[write]
            /// abs-addr:0X20014; 2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_start_addr_l16
            /// bit-width:16 ;  操作flash起始地址，,低16位
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X005 << 2),0x20014")]
            FlashOperator_StartAddress_L16 = 0X20000 | (0X005 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_START_ADDR_H16[write]
            /// abs-addr:0X20018; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_start_addr_h16
            /// bit-width:16 ;  操作lash起始地址，,高16位
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X006 << 2),0x20018")]
            FlashOperator_StartAddress_H16 = 0X20000 | (0X006 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_END_ADDR_L16[write]
            /// abs-addr:0X2001C; 2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_end_addr_l16
            /// bit-width:16 ;  操作flash结束地址,低16位
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X007 << 2),0x2001C")]
            FlashOperator_EndAddress_L16   = 0X20000 | (0X007 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_END_ADDR_H16[write]
            /// abs-addr:0X20020; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_end_addr_h16
            /// bit-width:16 ;  操作flash结束地址,高16位
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X008 << 2),0x20020")]
            FlashOperator_EndAddress_H16   = 0X20000 | (0X008 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_ACTION_CODE[write]
            /// abs-addr:0X20024; 2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_action_code
            /// bit-width:16 ;  业务操作定义：1=读flashid;2=擦除，3=烧写；4=回读。读flashid，通过软件延时读取；其他的操作状态，通过pcie的寄存器读取
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X009 << 2),0x20024")]
            FlashOperator_ActionCode       = 0X20000 | (0X009 << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_FLASH_ACTION_START[write]
            /// abs-addr:0X20028; Spi16本次后传的数据量（字节数）,高16位,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_flash_action_start
            /// bit-width:16 ;  上升沿有效
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00A << 2),0x20028")]
            FlashOperator_ActionStart      = 0X20000 | (0X00A << 2),
            #endregion FlashOperator

            #region====================PllConfig=[共9个寄存器]================================

            /// <summary>
            /// REG_HMC7043_RESET[write]
            /// abs-addr:0X2003C; 7043复位写0-1-0 进行一次复位， ; 初始化前复位一次,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7043_reset
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00F << 2),0x2003C")]
            PllConfig_7043Reset            = 0X20000 | (0X00F << 2),

            /// <summary>
            /// REG_HMC7043_WRITE_DATA_H8[write]
            /// abs-addr:0X20040; SPI写数据（共24bit，分高低位） 低8位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7043_write_data_h8
            /// bit-width:16 ;  high_8bits_of_24bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X010 << 2),0x20040")]
            PllConfig_7043WriteData_H8     = 0X20000 | (0X010 << 2),

            /// <summary>
            /// REG_HMC7043_WRITE_DATA_L16[write]
            /// abs-addr:0X20044; SPI写数据（共24bit，分高低位） 低16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7043_write_data_l16
            /// bit-width:16 ;  low_16bits_of_24bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X011 << 2),0x20044")]
            PllConfig_7043WriteData_L16    = 0X20000 | (0X011 << 2),

            /// <summary>
            /// REG_HMC7043_CONFIGURABLE_EN[write]
            /// abs-addr:0X20048; 7043写使能，写0-1触发一次读写，也就是先写0， ; 之后写入数据，然后拉高完成一次读写,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7043_configurable_en
            /// bit-width:16 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X012 << 2),0x20048")]
            PllConfig_7043WriteDataEffect  = 0X20000 | (0X012 << 2),

            /// <summary>
            /// REG_HMC7044_RESET[write]
            /// abs-addr:0X2004C; 7044复位写0-1-0 进行一次复位， ; 初始化前复位一次,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7044_reset
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X013 << 2),0x2004C")]
            PllConfig_7044Reset            = 0X20000 | (0X013 << 2),

            /// <summary>
            /// REG_HMC7044_SYNC[write]
            /// abs-addr:0X20050; 7044 sync同步引脚,需要多次同步 ; 写0-1-0触发一次锁相环同步,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7044_sync
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X014 << 2),0x20050")]
            PllConfig_7044Sync             = 0X20000 | (0X014 << 2),

            /// <summary>
            /// REG_HMC7044_WRITE_DATA_H8[write]
            /// abs-addr:0X20054; SPI写数据（共24bit，分高低位） 高8位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7044_write_data_h8
            /// bit-width:16 ;  high_8bits_of_24bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X015 << 2),0x20054")]
            PllConfig_7044WriteData_H8     = 0X20000 | (0X015 << 2),

            /// <summary>
            /// REG_HMC7044_WRITE_DATA_L16[write]
            /// abs-addr:0X20058; SPI写数据（共24bit，分高低位） 低16位,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7044_write_data_l16
            /// bit-width:16 ;  low_16bits_of_24bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X016 << 2),0x20058")]
            PllConfig_7044WriteData_L16    = 0X20000 | (0X016 << 2),

            /// <summary>
            /// PLL_SEND_7044[write]
            /// abs-addr:0X2005C; 7044 sync同步引脚,需要多次同步 ; 写0-1-0触发一次锁相环同步,是,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:pll_send_7044
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X017 << 2),0x2005C")]
            PllConfig_7044WriteDataEffect  = 0X20000 | (0X017 << 2),
            #endregion PllConfig

            #region====================RegManager=[共1个寄存器]===============================

            /// <summary>
            /// REG_ACQ_ALL_WRITE_SELECT[write]
            /// abs-addr:0X20004; 复位内部DCM PLL,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_acq_all_write_select
            /// bit-width:1 ;  1bit，active high
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X001 << 2),0x20004")]
            RegManager_WriteToAllAcqBoardEnable = 0X20000 | (0X001 << 2),
            #endregion RegManager

            #region====================RegMonitor=[共1个寄存器]===============================

            /// <summary>
            /// S6_READ_WREG_ADDR[write]
            /// abs-addr:0X20008; 读回下发寄存器的值,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_read_wreg_addr
            /// bit-width:16 ;  read back write-register
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X002 << 2),0x20008")]
            RegMonitor_RegAddress          = 0X20000 | (0X002 << 2),
            #endregion RegMonitor

            #region====================SysInfo=[共1个寄存器]==================================

            /// <summary>
            /// S6_REG_READ_BACK[write]
            /// abs-addr:0X20FF8; none
            /// reg_hw_name:s6_reg_read_back
            /// bit-width:16 ;  16bits_data
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X3FE << 2),0x20FF8")]
            SysInfo_WorkOKTest             = 0X20000 | (0X3FE << 2),
            #endregion SysInfo
        }
        /// <summary>
        ///共有[31]个,其中[0]个没有使用。
        /// </summary>
        public enum R
        {

            #region====================FlashOperator=[共3个寄存器]============================

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_FLASH_ACTION_STATUS[read]
            /// abs-addr:0X20068; none
            /// reg_hw_name:reg_s6_flash_operator_flash_action_status
            /// bit-width:16 ;  操作状态。2bit:bit0=是否完成，1表示完成；bit1=是否有错，1=有错误
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X01A << 2),0x20068")]
            FlashOperator_ActionStatus     = 0X20000 | (0X01A << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_FLASH_ID_L16[read]
            /// abs-addr:0X2006C; 软件获取FlashID_L16，在读FlashID命令执行完成(ActionStart)后读取,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_flash_id_l16
            /// bit-width:16 ;  软件获取flashid_l16，在读flashid命令执行完成(actionstart)后读取
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X01B << 2),0x2006C")]
            FlashOperator_FlashID_L16      = 0X20000 | (0X01B << 2),

            /// <summary>
            /// REG_S6_FLASH_OPERATOR_FLASH_ID_H16[read]
            /// abs-addr:0X20070; 软件获取FlashID_H16,,,,,2024.10.31,赵勇,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_flash_operator_flash_id_h16
            /// bit-width:16 ;  软件获取flashid_h16
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X01C << 2),0x20070")]
            FlashOperator_FlashID_H16      = 0X20000 | (0X01C << 2),
            #endregion FlashOperator

            #region====================PllConfig=[共2个寄存器]================================

            /// <summary>
            /// REG_HMC7044_READ_DATA[read]
            /// abs-addr:0X20074; 锁相环HMC7044读回数据8bit,,,,,,,是,否,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7044_read_data
            /// bit-width:8 ;  8bits，readback_7044_data
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X01D << 2),0x20074")]
            PllConfig_HMC7044_SpiReadBackData = 0X20000 | (0X01D << 2),

            /// <summary>
            /// REG_HMC7043_READ_DATA[read]
            /// abs-addr:0X20078; 锁相环HMC7043读回数据8bit,,,,,,,是,否,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_hmc7043_read_data
            /// bit-width:8 ;  8bits，readback_7043_data
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X01E << 2),0x20078")]
            PllConfig_HMC7043_SpiReadBackData = 0X20000 | (0X01E << 2),
            #endregion PllConfig

            #region====================RegMonitor=[共1个寄存器]===============================

            /// <summary>
            /// S6_READ_WREG_DATA[read]
            /// abs-addr:0X20004; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_read_wreg_data
            /// bit-width:16 ;  read back write-register
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X001 << 2),0x20004")]
            RegMonitor_ReadbackValue       = 0X20000 | (0X001 << 2),
            #endregion RegMonitor

            #region====================SysInfo=[共1个寄存器]==================================

            /// <summary>
            /// S6_REG_READ_BACK[read]
            /// abs-addr:0X20FF8; none
            /// reg_hw_name:s6_reg_read_back
            /// bit-width:16 ;  16bits_data
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X3FE << 2),0x20FF8")]
            SysInfo_WorkOKTest             = 0X20000 | (0X3FE << 2),
            #endregion SysInfo

            #region====================VersionInfo=[共20个寄存器]=============================

            /// <summary>
            /// S6_VERSION_COMMENT_WORD0[read]
            /// abs-addr:0X20008; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word0
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X002 << 2),0x20008")]
            VersionInfo_CommentWord0       = 0X20000 | (0X002 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD1[read]
            /// abs-addr:0X2000C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word1
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X003 << 2),0x2000C")]
            VersionInfo_CommentWord1       = 0X20000 | (0X003 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD10[read]
            /// abs-addr:0X20010; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word10
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X004 << 2),0x20010")]
            VersionInfo_CommentWord10      = 0X20000 | (0X004 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD11[read]
            /// abs-addr:0X20014; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word11
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X005 << 2),0x20014")]
            VersionInfo_CommentWord11      = 0X20000 | (0X005 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD12[read]
            /// abs-addr:0X20018; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word12
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X006 << 2),0x20018")]
            VersionInfo_CommentWord12      = 0X20000 | (0X006 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD13[read]
            /// abs-addr:0X2001C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word13
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X007 << 2),0x2001C")]
            VersionInfo_CommentWord13      = 0X20000 | (0X007 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD2[read]
            /// abs-addr:0X20028; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word2
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00A << 2),0x20028")]
            VersionInfo_CommentWord2       = 0X20000 | (0X00A << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD3[read]
            /// abs-addr:0X2002C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word3
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00B << 2),0x2002C")]
            VersionInfo_CommentWord3       = 0X20000 | (0X00B << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD4[read]
            /// abs-addr:0X20030; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word4
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00C << 2),0x20030")]
            VersionInfo_CommentWord4       = 0X20000 | (0X00C << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD5[read]
            /// abs-addr:0X20034; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word5
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00D << 2),0x20034")]
            VersionInfo_CommentWord5       = 0X20000 | (0X00D << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD6[read]
            /// abs-addr:0X20038; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word6
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00E << 2),0x20038")]
            VersionInfo_CommentWord6       = 0X20000 | (0X00E << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD7[read]
            /// abs-addr:0X2003C; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word7
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X00F << 2),0x2003C")]
            VersionInfo_CommentWord7       = 0X20000 | (0X00F << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD8[read]
            /// abs-addr:0X20040; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word8
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X010 << 2),0x20040")]
            VersionInfo_CommentWord8       = 0X20000 | (0X010 << 2),

            /// <summary>
            /// S6_VERSION_COMMENT_WORD9[read]
            /// abs-addr:0X20044; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_comment_word9
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X011 << 2),0x20044")]
            VersionInfo_CommentWord9       = 0X20000 | (0X011 << 2),

            /// <summary>
            /// S6_VERSION_DESIGNER_WORD0[read]
            /// abs-addr:0X20050; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_designer_word0
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X014 << 2),0x20050")]
            VersionInfo_DesignerWord0      = 0X20000 | (0X014 << 2),

            /// <summary>
            /// S6_VERSION_DESIGNER_WORD1[read]
            /// abs-addr:0X20054; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_designer_word1
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X015 << 2),0x20054")]
            VersionInfo_DesignerWord1      = 0X20000 | (0X015 << 2),

            /// <summary>
            /// S6_VERSION_DESIGNER_WORD2[read]
            /// abs-addr:0X20058; 版本信息，设计者,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_designer_word2
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X016 << 2),0x20058")]
            VersionInfo_DesignerWord2      = 0X20000 | (0X016 << 2),

            /// <summary>
            /// S6_VERSION_DESIGNER_WORD3[read]
            /// abs-addr:0X2005C; 版本信息，编译时间,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_designer_word3
            /// bit-width:16 ;  64bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X017 << 2),0x2005C")]
            VersionInfo_DesignerWord3      = 0X20000 | (0X017 << 2),

            /// <summary>
            /// S6_VERSION_VERSION_WORD0[read]
            /// abs-addr:0X20060; 版本信息，版本号,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_version_word0
            /// bit-width:16 ;  low_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X018 << 2),0x20060")]
            VersionInfo_VersionWord0       = 0X20000 | (0X018 << 2),

            /// <summary>
            /// S6_VERSION_VERSION_WORD1[read]
            /// abs-addr:0X20064; 16位数据，由此寄存器写入，再由此寄存器读出，两者数据一致，表明上电OK。,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:s6_version_version_word1
            /// bit-width:16 ;  high_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X019 << 2),0x20064")]
            VersionInfo_VersionWord1       = 0X20000 | (0X019 << 2),
            #endregion VersionInfo

            #region====================VersionInfo1=[共4个寄存器]=============================

            /// <summary>
            /// REG_S6_VERSION_COMMENT_WORD14[read]
            /// abs-addr:0X20020; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_version_comment_word14
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X008 << 2),0x20020")]
            VersionInfo1_CommentWord14     = 0X20000 | (0X008 << 2),

            /// <summary>
            /// REG_S6_VERSION_COMMENT_WORD15[read]
            /// abs-addr:0X20024; 版本信息，备注,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_version_comment_word15
            /// bit-width:16 ;  256bits_info
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X009 << 2),0x20024")]
            VersionInfo1_CommentWord15     = 0X20000 | (0X009 << 2),

            /// <summary>
            /// REG_REG_S6_VERSION_TIME_WORD0[read]
            /// abs-addr:0X20048; 版本信息，编译时间,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_version_time_word0
            /// bit-width:16 ;  low_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X012 << 2),0x20048")]
            VersionInfo1_CompileTimeWord0  = 0X20000 | (0X012 << 2),

            /// <summary>
            /// REG_REG_S6_VERSION_TIME_WORD1[read]
            /// abs-addr:0X2004C; 版本信息，版本号,,,,,,,,,,,,,,,,,,,,,,,
            /// reg_hw_name:reg_s6_version_time_word1
            /// bit-width:16 ;  high_16bits_of_32bits
            /// </summary>
            [RegAttribute(Description = "0X20000 | (0X013 << 2),0x2004C")]
            VersionInfo1_CompileTimeWord1  = 0X20000 | (0X013 << 2),
            #endregion VersionInfo1
        }
    }
}

