using System;

namespace Uestc.Auto6.Dso.Hardware.Driver
{
    //This File is Auto Generated By FPGAViewerSimpleness.exe At Computer[DESKTOP-UO0U9D7] ,2022.07.18 15:10:56
    //Source File Name = D:\tmp\tmp\编辑3.v
    //Source File Last Auto GeneratedTime=
    //Source File LastWritedTime = 2022.07.18 15:10:30


    ///<see href="file:///D:\MyWork2022\Dso2021MergeHardware\FPGAViewerSimpleness\bin\Debug\编辑3\JPO6000_Doc_SoftwareRegister.html"></see>
    ///<see href="file:///D:\MyWork2022\Dso2021MergeHardware\FPGAViewerSimpleness\bin\Debug\编辑3\images\acq_registers.png "></see>

    /// <summary>
    ///共有[0]个寄存器，其中写寄存器[0]个，没有用到的共[0]，读寄存器[0个]，没有用到的共[0]个.
    ///FPGA中还有[0]个定义的寄存器在软件中没有使用。
    ///在本文件中出现[todo...]字样的地方需要注意使用，并尽量与硬件人员一起完善。
    /// </summary>
    internal partial class Reg
    {
    }
}

