namespace ScopeX.U2
{
    partial class Page7000X
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            BtnRunStop = new UserControls.ScopeXIconButton();
            BtnAutoset = new UserControls.ScopeXIconButton();
            BtnSingle = new UserControls.ScopeXIconButton();
            BtnNormal = new UserControls.ScopeXIconButton();
            BtnAuto = new UserControls.ScopeXIconButton();
            CircLevel = new CircularProgressBar();
            BtnMenu = new UserControls.ScopeXIconButton();
            BtnForce = new UserControls.ScopeXIconButton();
            BtnCursors = new UserControls.ScopeXIconButton();
            BtnUltraAcq = new UserControls.ScopeXIconButton();
            BtnMeas = new UserControls.ScopeXIconButton();
            BtnQuickMeas = new UserControls.ScopeXIconButton();
            BtnTouchLock = new UserControls.ScopeXIconButton();
            BtnUtility = new UserControls.ScopeXIconButton();
            BtnDefault = new UserControls.ScopeXIconButton();
            BtnAPP = new UserControls.ScopeXIconButton();
            BtnScreenshot = new UserControls.ScopeXIconButton();
            BtnClear = new UserControls.ScopeXIconButton();
            CircFunction = new CircularProgressBar();
            BtnGen = new UserControls.ScopeXIconButton();
            BtnDVM = new UserControls.ScopeXIconButton();
            CircHScale = new CircularProgressBar();
            CircHPosition = new CircularProgressBar();
            BtnMath = new UserControls.ScopeXIconButton();
            BtnRef = new UserControls.ScopeXIconButton();
            BtnDigital = new UserControls.ScopeXIconButton();
            BtnBus = new UserControls.ScopeXIconButton();
            CircVScale = new CircularProgressBar();
            CircVPosition = new CircularProgressBar();
            BtnC1 = new UserControls.ScopeXIconButton();
            BtnC2 = new UserControls.ScopeXIconButton();
            BtnC3 = new UserControls.ScopeXIconButton();
            BtnC4 = new UserControls.ScopeXIconButton();
            SuspendLayout();
            // 
            // BtnRunStop
            // 
            BtnRunStop.Adjustable = false;
            BtnRunStop.BackColor = System.Drawing.Color.Transparent;
            BtnRunStop.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRunStop.BorderThickness = 1;
            BtnRunStop.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnRunStop.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnRunStop.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnRunStop.CornerRadius = 8;
            BtnRunStop.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnRunStop.DaskArray = null;
            BtnRunStop.DoubleClickEnable = true;
            BtnRunStop.DropKey = System.Windows.Forms.Keys.Space;
            BtnRunStop.FineEnable = false;
            BtnRunStop.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRunStop.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnRunStop.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.Height = 40;
            BtnRunStop.Icon = null;
            BtnRunStop.IconOffset = 10;
            BtnRunStop.IconSize = new System.Drawing.Size(24, 24);
            BtnRunStop.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnRunStop.IsChoosed = false;
            BtnRunStop.IsIndicatorShow = false;
            BtnRunStop.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnRunStop.Location = new System.Drawing.Point(11, 32);
            BtnRunStop.Margin = new System.Windows.Forms.Padding(2);
            BtnRunStop.MouseinBackColor = System.Drawing.Color.Silver;
            BtnRunStop.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRunStop.MouseInBorderThickness = 1;
            BtnRunStop.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.Name = "BtnRunStop";
            BtnRunStop.PressedBackColor = System.Drawing.Color.Silver;
            BtnRunStop.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRunStop.PressedBorderThickness = 1;
            BtnRunStop.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.Size = new System.Drawing.Size(100, 40);
            BtnRunStop.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnRunStop.StylizeFlag = true;
            BtnRunStop.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRunStop.SVGPath = "";
            BtnRunStop.TabIndex = 18;
            BtnRunStop.Text = "RUN/Stop";
            BtnRunStop.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnRunStop.Click += BtnRunStop_Click;
            // 
            // BtnAutoset
            // 
            BtnAutoset.Adjustable = false;
            BtnAutoset.BackColor = System.Drawing.Color.Transparent;
            BtnAutoset.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAutoset.BorderThickness = 1;
            BtnAutoset.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnAutoset.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnAutoset.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnAutoset.CornerRadius = 8;
            BtnAutoset.DaskArray = null;
            BtnAutoset.DoubleClickEnable = true;
            BtnAutoset.DropKey = System.Windows.Forms.Keys.Space;
            BtnAutoset.Enabled = false;
            BtnAutoset.FineEnable = false;
            BtnAutoset.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAutoset.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnAutoset.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.Height = 40;
            BtnAutoset.Icon = null;
            BtnAutoset.IconOffset = 10;
            BtnAutoset.IconSize = new System.Drawing.Size(24, 24);
            BtnAutoset.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnAutoset.IsChoosed = false;
            BtnAutoset.IsIndicatorShow = false;
            BtnAutoset.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnAutoset.Location = new System.Drawing.Point(169, 32);
            BtnAutoset.Margin = new System.Windows.Forms.Padding(2);
            BtnAutoset.MouseinBackColor = System.Drawing.Color.Silver;
            BtnAutoset.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAutoset.MouseInBorderThickness = 1;
            BtnAutoset.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.Name = "BtnAutoset";
            BtnAutoset.PressedBackColor = System.Drawing.Color.Silver;
            BtnAutoset.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAutoset.PressedBorderThickness = 1;
            BtnAutoset.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.Size = new System.Drawing.Size(100, 40);
            BtnAutoset.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnAutoset.StylizeFlag = true;
            BtnAutoset.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAutoset.SVGPath = "";
            BtnAutoset.TabIndex = 19;
            BtnAutoset.Text = "Autoset";
            BtnAutoset.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnAutoset.Click += BtnAutoset_Click;
            // 
            // BtnSingle
            // 
            BtnSingle.Adjustable = false;
            BtnSingle.BackColor = System.Drawing.Color.Transparent;
            BtnSingle.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnSingle.BorderThickness = 1;
            BtnSingle.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnSingle.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnSingle.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnSingle.CornerRadius = 8;
            BtnSingle.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnSingle.DaskArray = null;
            BtnSingle.DoubleClickEnable = true;
            BtnSingle.DropKey = System.Windows.Forms.Keys.Space;
            BtnSingle.FineEnable = false;
            BtnSingle.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnSingle.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnSingle.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.Height = 40;
            BtnSingle.Icon = null;
            BtnSingle.IconOffset = 10;
            BtnSingle.IconSize = new System.Drawing.Size(24, 24);
            BtnSingle.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnSingle.IsChoosed = false;
            BtnSingle.IsIndicatorShow = false;
            BtnSingle.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnSingle.Location = new System.Drawing.Point(11, 112);
            BtnSingle.Margin = new System.Windows.Forms.Padding(2);
            BtnSingle.MouseinBackColor = System.Drawing.Color.Silver;
            BtnSingle.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnSingle.MouseInBorderThickness = 1;
            BtnSingle.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.Name = "BtnSingle";
            BtnSingle.PressedBackColor = System.Drawing.Color.Silver;
            BtnSingle.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnSingle.PressedBorderThickness = 1;
            BtnSingle.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.Size = new System.Drawing.Size(100, 40);
            BtnSingle.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnSingle.StylizeFlag = true;
            BtnSingle.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnSingle.SVGPath = "";
            BtnSingle.TabIndex = 20;
            BtnSingle.Text = "Single";
            BtnSingle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnSingle.Click += BtnSingle_Click;
            // 
            // BtnNormal
            // 
            BtnNormal.Adjustable = false;
            BtnNormal.BackColor = System.Drawing.Color.Transparent;
            BtnNormal.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnNormal.BorderThickness = 1;
            BtnNormal.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnNormal.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnNormal.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnNormal.CornerRadius = 8;
            BtnNormal.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnNormal.DaskArray = null;
            BtnNormal.DoubleClickEnable = true;
            BtnNormal.DropKey = System.Windows.Forms.Keys.Space;
            BtnNormal.FineEnable = false;
            BtnNormal.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnNormal.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnNormal.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.Height = 40;
            BtnNormal.Icon = null;
            BtnNormal.IconOffset = 10;
            BtnNormal.IconSize = new System.Drawing.Size(24, 24);
            BtnNormal.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnNormal.IsChoosed = false;
            BtnNormal.IsIndicatorShow = false;
            BtnNormal.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnNormal.Location = new System.Drawing.Point(169, 112);
            BtnNormal.Margin = new System.Windows.Forms.Padding(2);
            BtnNormal.MouseinBackColor = System.Drawing.Color.Silver;
            BtnNormal.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnNormal.MouseInBorderThickness = 1;
            BtnNormal.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.Name = "BtnNormal";
            BtnNormal.PressedBackColor = System.Drawing.Color.Silver;
            BtnNormal.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnNormal.PressedBorderThickness = 1;
            BtnNormal.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.Size = new System.Drawing.Size(100, 40);
            BtnNormal.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnNormal.StylizeFlag = true;
            BtnNormal.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnNormal.SVGPath = "";
            BtnNormal.TabIndex = 21;
            BtnNormal.Text = "Normal";
            BtnNormal.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnNormal.Click += BtnNormal_Click;
            // 
            // BtnAuto
            // 
            BtnAuto.Adjustable = false;
            BtnAuto.BackColor = System.Drawing.Color.Transparent;
            BtnAuto.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAuto.BorderThickness = 1;
            BtnAuto.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnAuto.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnAuto.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnAuto.CornerRadius = 8;
            BtnAuto.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnAuto.DaskArray = null;
            BtnAuto.DoubleClickEnable = true;
            BtnAuto.DropKey = System.Windows.Forms.Keys.Space;
            BtnAuto.FineEnable = false;
            BtnAuto.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAuto.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnAuto.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.Height = 40;
            BtnAuto.Icon = null;
            BtnAuto.IconOffset = 10;
            BtnAuto.IconSize = new System.Drawing.Size(24, 24);
            BtnAuto.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnAuto.IsChoosed = false;
            BtnAuto.IsIndicatorShow = false;
            BtnAuto.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnAuto.Location = new System.Drawing.Point(327, 112);
            BtnAuto.Margin = new System.Windows.Forms.Padding(2);
            BtnAuto.MouseinBackColor = System.Drawing.Color.Silver;
            BtnAuto.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAuto.MouseInBorderThickness = 1;
            BtnAuto.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.Name = "BtnAuto";
            BtnAuto.PressedBackColor = System.Drawing.Color.Silver;
            BtnAuto.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAuto.PressedBorderThickness = 1;
            BtnAuto.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.Size = new System.Drawing.Size(100, 40);
            BtnAuto.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnAuto.StylizeFlag = true;
            BtnAuto.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAuto.SVGPath = "";
            BtnAuto.TabIndex = 22;
            BtnAuto.Text = "Auto";
            BtnAuto.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnAuto.Click += BtnAuto_Click;
            // 
            // CircLevel
            // 
            CircLevel.GroundBackColor = System.Drawing.Color.DarkGray;
            CircLevel.Location = new System.Drawing.Point(298, 180);
            CircLevel.Name = "CircLevel";
            CircLevel.Progress = 0;
            CircLevel.ProgressBackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            CircLevel.ProgressColor = System.Drawing.Color.LimeGreen;
            CircLevel.Size = new System.Drawing.Size(80, 80);
            CircLevel.StartAngle = -90;
            CircLevel.TabIndex = 0;
            CircLevel.Thickness = 10;
            CircLevel.Click += CircLevel_Click;
            // 
            // BtnMenu
            // 
            BtnMenu.Adjustable = false;
            BtnMenu.BackColor = System.Drawing.Color.Transparent;
            BtnMenu.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMenu.BorderThickness = 1;
            BtnMenu.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnMenu.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnMenu.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnMenu.CornerRadius = 8;
            BtnMenu.DaskArray = null;
            BtnMenu.DoubleClickEnable = true;
            BtnMenu.DropKey = System.Windows.Forms.Keys.Space;
            BtnMenu.Enabled = false;
            BtnMenu.FineEnable = false;
            BtnMenu.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMenu.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnMenu.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.Height = 40;
            BtnMenu.Icon = null;
            BtnMenu.IconOffset = 10;
            BtnMenu.IconSize = new System.Drawing.Size(24, 24);
            BtnMenu.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnMenu.IsChoosed = false;
            BtnMenu.IsIndicatorShow = false;
            BtnMenu.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnMenu.Location = new System.Drawing.Point(11, 200);
            BtnMenu.Margin = new System.Windows.Forms.Padding(2);
            BtnMenu.MouseinBackColor = System.Drawing.Color.Silver;
            BtnMenu.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMenu.MouseInBorderThickness = 1;
            BtnMenu.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.Name = "BtnMenu";
            BtnMenu.PressedBackColor = System.Drawing.Color.Silver;
            BtnMenu.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMenu.PressedBorderThickness = 1;
            BtnMenu.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.Size = new System.Drawing.Size(80, 40);
            BtnMenu.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnMenu.StylizeFlag = true;
            BtnMenu.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMenu.SVGPath = "";
            BtnMenu.TabIndex = 23;
            BtnMenu.Text = "Menu";
            BtnMenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnMenu.Click += BtnMenu_Click;
            // 
            // BtnForce
            // 
            BtnForce.Adjustable = false;
            BtnForce.BackColor = System.Drawing.Color.Transparent;
            BtnForce.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnForce.BorderThickness = 1;
            BtnForce.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnForce.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnForce.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnForce.CornerRadius = 8;
            BtnForce.DaskArray = null;
            BtnForce.DoubleClickEnable = true;
            BtnForce.DropKey = System.Windows.Forms.Keys.Space;
            BtnForce.Enabled = false;
            BtnForce.FineEnable = false;
            BtnForce.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnForce.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnForce.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.Height = 40;
            BtnForce.Icon = null;
            BtnForce.IconOffset = 10;
            BtnForce.IconSize = new System.Drawing.Size(24, 24);
            BtnForce.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnForce.IsChoosed = false;
            BtnForce.IsIndicatorShow = false;
            BtnForce.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnForce.Location = new System.Drawing.Point(123, 200);
            BtnForce.Margin = new System.Windows.Forms.Padding(2);
            BtnForce.MouseinBackColor = System.Drawing.Color.Silver;
            BtnForce.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnForce.MouseInBorderThickness = 1;
            BtnForce.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.Name = "BtnForce";
            BtnForce.PressedBackColor = System.Drawing.Color.Silver;
            BtnForce.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnForce.PressedBorderThickness = 1;
            BtnForce.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.Size = new System.Drawing.Size(80, 40);
            BtnForce.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnForce.StylizeFlag = true;
            BtnForce.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnForce.SVGPath = "";
            BtnForce.TabIndex = 24;
            BtnForce.Text = "Force";
            BtnForce.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnForce.Click += BtnForce_Click;
            // 
            // BtnCursors
            // 
            BtnCursors.Adjustable = false;
            BtnCursors.BackColor = System.Drawing.Color.Transparent;
            BtnCursors.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnCursors.BorderThickness = 1;
            BtnCursors.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnCursors.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnCursors.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnCursors.CornerRadius = 8;
            BtnCursors.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnCursors.DaskArray = null;
            BtnCursors.DoubleClickEnable = true;
            BtnCursors.DropKey = System.Windows.Forms.Keys.Space;
            BtnCursors.FineEnable = false;
            BtnCursors.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnCursors.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnCursors.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.Height = 40;
            BtnCursors.Icon = null;
            BtnCursors.IconOffset = 10;
            BtnCursors.IconSize = new System.Drawing.Size(24, 24);
            BtnCursors.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnCursors.IsChoosed = false;
            BtnCursors.IsIndicatorShow = false;
            BtnCursors.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnCursors.Location = new System.Drawing.Point(11, 298);
            BtnCursors.Margin = new System.Windows.Forms.Padding(2);
            BtnCursors.MouseinBackColor = System.Drawing.Color.Silver;
            BtnCursors.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnCursors.MouseInBorderThickness = 1;
            BtnCursors.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.Name = "BtnCursors";
            BtnCursors.PressedBackColor = System.Drawing.Color.Silver;
            BtnCursors.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnCursors.PressedBorderThickness = 1;
            BtnCursors.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.Size = new System.Drawing.Size(80, 40);
            BtnCursors.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnCursors.StylizeFlag = true;
            BtnCursors.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnCursors.SVGPath = "";
            BtnCursors.TabIndex = 25;
            BtnCursors.Text = "Cursors";
            BtnCursors.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnCursors.Click += BtnCursors_Click;
            // 
            // BtnUltraAcq
            // 
            BtnUltraAcq.Adjustable = false;
            BtnUltraAcq.BackColor = System.Drawing.Color.Transparent;
            BtnUltraAcq.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUltraAcq.BorderThickness = 1;
            BtnUltraAcq.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnUltraAcq.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnUltraAcq.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnUltraAcq.CornerRadius = 8;
            BtnUltraAcq.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnUltraAcq.DaskArray = null;
            BtnUltraAcq.DoubleClickEnable = true;
            BtnUltraAcq.DropKey = System.Windows.Forms.Keys.Space;
            BtnUltraAcq.FineEnable = false;
            BtnUltraAcq.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUltraAcq.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnUltraAcq.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.Height = 40;
            BtnUltraAcq.Icon = null;
            BtnUltraAcq.IconOffset = 10;
            BtnUltraAcq.IconSize = new System.Drawing.Size(24, 24);
            BtnUltraAcq.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnUltraAcq.IsChoosed = false;
            BtnUltraAcq.IsIndicatorShow = false;
            BtnUltraAcq.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnUltraAcq.Location = new System.Drawing.Point(348, 298);
            BtnUltraAcq.Margin = new System.Windows.Forms.Padding(2);
            BtnUltraAcq.MouseinBackColor = System.Drawing.Color.Silver;
            BtnUltraAcq.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUltraAcq.MouseInBorderThickness = 1;
            BtnUltraAcq.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.Name = "BtnUltraAcq";
            BtnUltraAcq.PressedBackColor = System.Drawing.Color.Silver;
            BtnUltraAcq.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUltraAcq.PressedBorderThickness = 1;
            BtnUltraAcq.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.Size = new System.Drawing.Size(80, 40);
            BtnUltraAcq.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnUltraAcq.StylizeFlag = true;
            BtnUltraAcq.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUltraAcq.SVGPath = "";
            BtnUltraAcq.TabIndex = 26;
            BtnUltraAcq.Text = "UltraAcq";
            BtnUltraAcq.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnUltraAcq.Click += BtnUltraAcq_Click;
            // 
            // BtnMeas
            // 
            BtnMeas.Adjustable = false;
            BtnMeas.BackColor = System.Drawing.Color.Transparent;
            BtnMeas.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMeas.BorderThickness = 1;
            BtnMeas.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnMeas.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnMeas.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnMeas.CornerRadius = 8;
            BtnMeas.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnMeas.DaskArray = null;
            BtnMeas.DoubleClickEnable = true;
            BtnMeas.DropKey = System.Windows.Forms.Keys.Space;
            BtnMeas.FineEnable = false;
            BtnMeas.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMeas.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnMeas.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.Height = 40;
            BtnMeas.Icon = null;
            BtnMeas.IconOffset = 10;
            BtnMeas.IconSize = new System.Drawing.Size(24, 24);
            BtnMeas.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnMeas.IsChoosed = false;
            BtnMeas.IsIndicatorShow = false;
            BtnMeas.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnMeas.Location = new System.Drawing.Point(123, 298);
            BtnMeas.Margin = new System.Windows.Forms.Padding(2);
            BtnMeas.MouseinBackColor = System.Drawing.Color.Silver;
            BtnMeas.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMeas.MouseInBorderThickness = 1;
            BtnMeas.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.Name = "BtnMeas";
            BtnMeas.PressedBackColor = System.Drawing.Color.Silver;
            BtnMeas.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMeas.PressedBorderThickness = 1;
            BtnMeas.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.Size = new System.Drawing.Size(80, 40);
            BtnMeas.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnMeas.StylizeFlag = true;
            BtnMeas.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMeas.SVGPath = "";
            BtnMeas.TabIndex = 27;
            BtnMeas.Text = "BtnMeas";
            BtnMeas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnMeas.Click += BtnMeas_Click;
            // 
            // BtnQuickMeas
            // 
            BtnQuickMeas.Adjustable = false;
            BtnQuickMeas.BackColor = System.Drawing.Color.Transparent;
            BtnQuickMeas.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnQuickMeas.BorderThickness = 1;
            BtnQuickMeas.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnQuickMeas.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnQuickMeas.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnQuickMeas.CornerRadius = 8;
            BtnQuickMeas.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnQuickMeas.DaskArray = null;
            BtnQuickMeas.DoubleClickEnable = true;
            BtnQuickMeas.DropKey = System.Windows.Forms.Keys.Space;
            BtnQuickMeas.FineEnable = false;
            BtnQuickMeas.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnQuickMeas.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnQuickMeas.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.Height = 40;
            BtnQuickMeas.Icon = null;
            BtnQuickMeas.IconOffset = 10;
            BtnQuickMeas.IconSize = new System.Drawing.Size(24, 24);
            BtnQuickMeas.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnQuickMeas.IsChoosed = false;
            BtnQuickMeas.IsIndicatorShow = false;
            BtnQuickMeas.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnQuickMeas.Location = new System.Drawing.Point(231, 298);
            BtnQuickMeas.Margin = new System.Windows.Forms.Padding(2);
            BtnQuickMeas.MouseinBackColor = System.Drawing.Color.Silver;
            BtnQuickMeas.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnQuickMeas.MouseInBorderThickness = 1;
            BtnQuickMeas.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.Name = "BtnQuickMeas";
            BtnQuickMeas.PressedBackColor = System.Drawing.Color.Silver;
            BtnQuickMeas.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnQuickMeas.PressedBorderThickness = 1;
            BtnQuickMeas.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.Size = new System.Drawing.Size(80, 40);
            BtnQuickMeas.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnQuickMeas.StylizeFlag = true;
            BtnQuickMeas.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnQuickMeas.SVGPath = "";
            BtnQuickMeas.TabIndex = 28;
            BtnQuickMeas.Text = "QuickMeas";
            BtnQuickMeas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnQuickMeas.Click += BtnQuickMeas_Click;
            // 
            // BtnTouchLock
            // 
            BtnTouchLock.Adjustable = false;
            BtnTouchLock.BackColor = System.Drawing.Color.Transparent;
            BtnTouchLock.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnTouchLock.BorderThickness = 1;
            BtnTouchLock.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnTouchLock.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnTouchLock.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnTouchLock.CornerRadius = 8;
            BtnTouchLock.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnTouchLock.DaskArray = null;
            BtnTouchLock.DoubleClickEnable = true;
            BtnTouchLock.DropKey = System.Windows.Forms.Keys.Space;
            BtnTouchLock.FineEnable = false;
            BtnTouchLock.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnTouchLock.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnTouchLock.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.Height = 40;
            BtnTouchLock.Icon = null;
            BtnTouchLock.IconOffset = 10;
            BtnTouchLock.IconSize = new System.Drawing.Size(24, 24);
            BtnTouchLock.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnTouchLock.IsChoosed = false;
            BtnTouchLock.IsIndicatorShow = false;
            BtnTouchLock.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnTouchLock.Location = new System.Drawing.Point(348, 383);
            BtnTouchLock.Margin = new System.Windows.Forms.Padding(2);
            BtnTouchLock.MouseinBackColor = System.Drawing.Color.Silver;
            BtnTouchLock.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnTouchLock.MouseInBorderThickness = 1;
            BtnTouchLock.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.Name = "BtnTouchLock";
            BtnTouchLock.PressedBackColor = System.Drawing.Color.Silver;
            BtnTouchLock.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnTouchLock.PressedBorderThickness = 1;
            BtnTouchLock.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.Size = new System.Drawing.Size(80, 40);
            BtnTouchLock.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnTouchLock.StylizeFlag = true;
            BtnTouchLock.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnTouchLock.SVGPath = "";
            BtnTouchLock.TabIndex = 29;
            BtnTouchLock.Text = "TouchLock";
            BtnTouchLock.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnTouchLock.Click += BtnTouchLock_Click;
            // 
            // BtnUtility
            // 
            BtnUtility.Adjustable = false;
            BtnUtility.BackColor = System.Drawing.Color.Transparent;
            BtnUtility.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUtility.BorderThickness = 1;
            BtnUtility.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnUtility.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnUtility.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnUtility.CornerRadius = 8;
            BtnUtility.DaskArray = null;
            BtnUtility.DoubleClickEnable = true;
            BtnUtility.DropKey = System.Windows.Forms.Keys.Space;
            BtnUtility.Enabled = false;
            BtnUtility.FineEnable = false;
            BtnUtility.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUtility.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnUtility.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.Height = 40;
            BtnUtility.Icon = null;
            BtnUtility.IconOffset = 10;
            BtnUtility.IconSize = new System.Drawing.Size(24, 24);
            BtnUtility.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnUtility.IsChoosed = false;
            BtnUtility.IsIndicatorShow = false;
            BtnUtility.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnUtility.Location = new System.Drawing.Point(348, 468);
            BtnUtility.Margin = new System.Windows.Forms.Padding(2);
            BtnUtility.MouseinBackColor = System.Drawing.Color.Silver;
            BtnUtility.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUtility.MouseInBorderThickness = 1;
            BtnUtility.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.Name = "BtnUtility";
            BtnUtility.PressedBackColor = System.Drawing.Color.Silver;
            BtnUtility.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnUtility.PressedBorderThickness = 1;
            BtnUtility.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.Size = new System.Drawing.Size(80, 40);
            BtnUtility.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnUtility.StylizeFlag = true;
            BtnUtility.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnUtility.SVGPath = "";
            BtnUtility.TabIndex = 30;
            BtnUtility.Text = "Utility";
            BtnUtility.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnUtility.Click += BtnUtility_Click;
            // 
            // BtnDefault
            // 
            BtnDefault.Adjustable = false;
            BtnDefault.BackColor = System.Drawing.Color.Transparent;
            BtnDefault.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDefault.BorderThickness = 1;
            BtnDefault.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnDefault.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnDefault.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnDefault.CornerRadius = 8;
            BtnDefault.DaskArray = null;
            BtnDefault.DoubleClickEnable = true;
            BtnDefault.DropKey = System.Windows.Forms.Keys.Space;
            BtnDefault.Enabled = false;
            BtnDefault.FineEnable = false;
            BtnDefault.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDefault.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnDefault.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.Height = 40;
            BtnDefault.Icon = null;
            BtnDefault.IconOffset = 10;
            BtnDefault.IconSize = new System.Drawing.Size(24, 24);
            BtnDefault.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnDefault.IsChoosed = false;
            BtnDefault.IsIndicatorShow = false;
            BtnDefault.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnDefault.Location = new System.Drawing.Point(348, 553);
            BtnDefault.Margin = new System.Windows.Forms.Padding(2);
            BtnDefault.MouseinBackColor = System.Drawing.Color.Silver;
            BtnDefault.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDefault.MouseInBorderThickness = 1;
            BtnDefault.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.Name = "BtnDefault";
            BtnDefault.PressedBackColor = System.Drawing.Color.Silver;
            BtnDefault.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDefault.PressedBorderThickness = 1;
            BtnDefault.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.Size = new System.Drawing.Size(80, 40);
            BtnDefault.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnDefault.StylizeFlag = true;
            BtnDefault.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDefault.SVGPath = "";
            BtnDefault.TabIndex = 31;
            BtnDefault.Text = "Default";
            BtnDefault.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnDefault.Click += BtnDefault_Click;
            // 
            // BtnAPP
            // 
            BtnAPP.Adjustable = false;
            BtnAPP.BackColor = System.Drawing.Color.Transparent;
            BtnAPP.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAPP.BorderThickness = 1;
            BtnAPP.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnAPP.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnAPP.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnAPP.CornerRadius = 8;
            BtnAPP.DaskArray = null;
            BtnAPP.DoubleClickEnable = true;
            BtnAPP.DropKey = System.Windows.Forms.Keys.Space;
            BtnAPP.Enabled = false;
            BtnAPP.FineEnable = false;
            BtnAPP.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAPP.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnAPP.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.Height = 40;
            BtnAPP.Icon = null;
            BtnAPP.IconOffset = 10;
            BtnAPP.IconSize = new System.Drawing.Size(24, 24);
            BtnAPP.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnAPP.IsChoosed = false;
            BtnAPP.IsIndicatorShow = false;
            BtnAPP.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnAPP.Location = new System.Drawing.Point(231, 383);
            BtnAPP.Margin = new System.Windows.Forms.Padding(2);
            BtnAPP.MouseinBackColor = System.Drawing.Color.Silver;
            BtnAPP.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAPP.MouseInBorderThickness = 1;
            BtnAPP.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.Name = "BtnAPP";
            BtnAPP.PressedBackColor = System.Drawing.Color.Silver;
            BtnAPP.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnAPP.PressedBorderThickness = 1;
            BtnAPP.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.Size = new System.Drawing.Size(80, 40);
            BtnAPP.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnAPP.StylizeFlag = true;
            BtnAPP.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAPP.SVGPath = "";
            BtnAPP.TabIndex = 32;
            BtnAPP.Text = "Application";
            BtnAPP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnAPP.Click += BtnAPP_Click;
            // 
            // BtnScreenshot
            // 
            BtnScreenshot.Adjustable = false;
            BtnScreenshot.BackColor = System.Drawing.Color.Transparent;
            BtnScreenshot.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnScreenshot.BorderThickness = 1;
            BtnScreenshot.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnScreenshot.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnScreenshot.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnScreenshot.CornerRadius = 8;
            BtnScreenshot.DaskArray = null;
            BtnScreenshot.DoubleClickEnable = true;
            BtnScreenshot.DropKey = System.Windows.Forms.Keys.Space;
            BtnScreenshot.Enabled = false;
            BtnScreenshot.FineEnable = false;
            BtnScreenshot.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnScreenshot.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnScreenshot.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.Height = 40;
            BtnScreenshot.Icon = null;
            BtnScreenshot.IconOffset = 10;
            BtnScreenshot.IconSize = new System.Drawing.Size(24, 24);
            BtnScreenshot.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnScreenshot.IsChoosed = false;
            BtnScreenshot.IsIndicatorShow = false;
            BtnScreenshot.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnScreenshot.Location = new System.Drawing.Point(231, 468);
            BtnScreenshot.Margin = new System.Windows.Forms.Padding(2);
            BtnScreenshot.MouseinBackColor = System.Drawing.Color.Silver;
            BtnScreenshot.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnScreenshot.MouseInBorderThickness = 1;
            BtnScreenshot.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.Name = "BtnScreenshot";
            BtnScreenshot.PressedBackColor = System.Drawing.Color.Silver;
            BtnScreenshot.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnScreenshot.PressedBorderThickness = 1;
            BtnScreenshot.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.Size = new System.Drawing.Size(80, 40);
            BtnScreenshot.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnScreenshot.StylizeFlag = true;
            BtnScreenshot.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnScreenshot.SVGPath = "";
            BtnScreenshot.TabIndex = 33;
            BtnScreenshot.Text = "Screenshot";
            BtnScreenshot.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnScreenshot.Click += BtnScreenshot_Click;
            // 
            // BtnClear
            // 
            BtnClear.Adjustable = false;
            BtnClear.BackColor = System.Drawing.Color.Transparent;
            BtnClear.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnClear.BorderThickness = 1;
            BtnClear.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnClear.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnClear.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnClear.CornerRadius = 8;
            BtnClear.DaskArray = null;
            BtnClear.DoubleClickEnable = true;
            BtnClear.DropKey = System.Windows.Forms.Keys.Space;
            BtnClear.Enabled = false;
            BtnClear.FineEnable = false;
            BtnClear.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnClear.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnClear.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.Height = 40;
            BtnClear.Icon = null;
            BtnClear.IconOffset = 10;
            BtnClear.IconSize = new System.Drawing.Size(24, 24);
            BtnClear.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnClear.IsChoosed = false;
            BtnClear.IsIndicatorShow = false;
            BtnClear.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnClear.Location = new System.Drawing.Point(231, 553);
            BtnClear.Margin = new System.Windows.Forms.Padding(2);
            BtnClear.MouseinBackColor = System.Drawing.Color.Silver;
            BtnClear.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnClear.MouseInBorderThickness = 1;
            BtnClear.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.Name = "BtnClear";
            BtnClear.PressedBackColor = System.Drawing.Color.Silver;
            BtnClear.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnClear.PressedBorderThickness = 1;
            BtnClear.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.Size = new System.Drawing.Size(80, 40);
            BtnClear.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnClear.StylizeFlag = true;
            BtnClear.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnClear.SVGPath = "";
            BtnClear.TabIndex = 34;
            BtnClear.Text = "Clear";
            BtnClear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnClear.Click += BtnClear_Click;
            // 
            // CircFunction
            // 
            CircFunction.GroundBackColor = System.Drawing.Color.DarkGray;
            CircFunction.Location = new System.Drawing.Point(59, 388);
            CircFunction.Name = "CircFunction";
            CircFunction.Progress = 0;
            CircFunction.ProgressBackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            CircFunction.ProgressColor = System.Drawing.Color.LimeGreen;
            CircFunction.Size = new System.Drawing.Size(112, 112);
            CircFunction.StartAngle = -90;
            CircFunction.TabIndex = 35;
            CircFunction.Thickness = 10;
            CircFunction.Click += CircFunction_Click;
            // 
            // BtnGen
            // 
            BtnGen.Adjustable = false;
            BtnGen.BackColor = System.Drawing.Color.Transparent;
            BtnGen.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnGen.BorderThickness = 1;
            BtnGen.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnGen.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnGen.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnGen.CornerRadius = 8;
            BtnGen.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnGen.DaskArray = null;
            BtnGen.DoubleClickEnable = true;
            BtnGen.DropKey = System.Windows.Forms.Keys.Space;
            BtnGen.FineEnable = false;
            BtnGen.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnGen.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnGen.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.Height = 40;
            BtnGen.Icon = null;
            BtnGen.IconOffset = 10;
            BtnGen.IconSize = new System.Drawing.Size(24, 24);
            BtnGen.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnGen.IsChoosed = false;
            BtnGen.IsIndicatorShow = false;
            BtnGen.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnGen.Location = new System.Drawing.Point(123, 554);
            BtnGen.Margin = new System.Windows.Forms.Padding(2);
            BtnGen.MouseinBackColor = System.Drawing.Color.Silver;
            BtnGen.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnGen.MouseInBorderThickness = 1;
            BtnGen.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.Name = "BtnGen";
            BtnGen.PressedBackColor = System.Drawing.Color.Silver;
            BtnGen.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnGen.PressedBorderThickness = 1;
            BtnGen.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.Size = new System.Drawing.Size(80, 40);
            BtnGen.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnGen.StylizeFlag = true;
            BtnGen.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnGen.SVGPath = "";
            BtnGen.TabIndex = 36;
            BtnGen.Text = "Gen";
            BtnGen.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnGen.Click += BtnGen_Click;
            // 
            // BtnDVM
            // 
            BtnDVM.Adjustable = false;
            BtnDVM.BackColor = System.Drawing.Color.Transparent;
            BtnDVM.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDVM.BorderThickness = 1;
            BtnDVM.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnDVM.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnDVM.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnDVM.CornerRadius = 8;
            BtnDVM.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnDVM.DaskArray = null;
            BtnDVM.DoubleClickEnable = true;
            BtnDVM.DropKey = System.Windows.Forms.Keys.Space;
            BtnDVM.FineEnable = false;
            BtnDVM.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDVM.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnDVM.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.Height = 40;
            BtnDVM.Icon = null;
            BtnDVM.IconOffset = 10;
            BtnDVM.IconSize = new System.Drawing.Size(24, 24);
            BtnDVM.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnDVM.IsChoosed = false;
            BtnDVM.IsIndicatorShow = false;
            BtnDVM.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnDVM.Location = new System.Drawing.Point(11, 554);
            BtnDVM.Margin = new System.Windows.Forms.Padding(2);
            BtnDVM.MouseinBackColor = System.Drawing.Color.Silver;
            BtnDVM.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDVM.MouseInBorderThickness = 1;
            BtnDVM.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.Name = "BtnDVM";
            BtnDVM.PressedBackColor = System.Drawing.Color.Silver;
            BtnDVM.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDVM.PressedBorderThickness = 1;
            BtnDVM.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.Size = new System.Drawing.Size(80, 40);
            BtnDVM.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnDVM.StylizeFlag = true;
            BtnDVM.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDVM.SVGPath = "";
            BtnDVM.TabIndex = 37;
            BtnDVM.Text = "DVM";
            BtnDVM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnDVM.Click += BtnDVM_Click;
            // 
            // CircHScale
            // 
            CircHScale.GroundBackColor = System.Drawing.Color.DarkGray;
            CircHScale.Location = new System.Drawing.Point(59, 641);
            CircHScale.Name = "CircHScale";
            CircHScale.Progress = 0;
            CircHScale.ProgressBackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            CircHScale.ProgressColor = System.Drawing.Color.LimeGreen;
            CircHScale.Size = new System.Drawing.Size(112, 112);
            CircHScale.StartAngle = -90;
            CircHScale.TabIndex = 38;
            CircHScale.Thickness = 10;
            CircHScale.Click += CircHScale_Click;
            // 
            // CircHPosition
            // 
            CircHPosition.GroundBackColor = System.Drawing.Color.DarkGray;
            CircHPosition.Location = new System.Drawing.Point(298, 652);
            CircHPosition.Name = "CircHPosition";
            CircHPosition.Progress = 0;
            CircHPosition.ProgressBackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            CircHPosition.ProgressColor = System.Drawing.Color.LimeGreen;
            CircHPosition.Size = new System.Drawing.Size(80, 80);
            CircHPosition.StartAngle = -90;
            CircHPosition.TabIndex = 39;
            CircHPosition.Thickness = 10;
            CircHPosition.Click += CircHPosition_Click;
            // 
            // BtnMath
            // 
            BtnMath.Adjustable = false;
            BtnMath.BackColor = System.Drawing.Color.Transparent;
            BtnMath.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMath.BorderThickness = 1;
            BtnMath.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnMath.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnMath.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnMath.CornerRadius = 8;
            BtnMath.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnMath.DaskArray = null;
            BtnMath.DoubleClickEnable = true;
            BtnMath.DropKey = System.Windows.Forms.Keys.Space;
            BtnMath.FineEnable = false;
            BtnMath.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMath.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnMath.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.Height = 40;
            BtnMath.Icon = null;
            BtnMath.IconOffset = 10;
            BtnMath.IconSize = new System.Drawing.Size(24, 24);
            BtnMath.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnMath.IsChoosed = false;
            BtnMath.IsIndicatorShow = false;
            BtnMath.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnMath.Location = new System.Drawing.Point(11, 789);
            BtnMath.Margin = new System.Windows.Forms.Padding(2);
            BtnMath.MouseinBackColor = System.Drawing.Color.Silver;
            BtnMath.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMath.MouseInBorderThickness = 1;
            BtnMath.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.Name = "BtnMath";
            BtnMath.PressedBackColor = System.Drawing.Color.Silver;
            BtnMath.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnMath.PressedBorderThickness = 1;
            BtnMath.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.Size = new System.Drawing.Size(80, 40);
            BtnMath.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnMath.StylizeFlag = true;
            BtnMath.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnMath.SVGPath = "";
            BtnMath.TabIndex = 40;
            BtnMath.Text = "Math";
            BtnMath.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnMath.Click += BtnMath_Click;
            // 
            // BtnRef
            // 
            BtnRef.Adjustable = false;
            BtnRef.BackColor = System.Drawing.Color.Transparent;
            BtnRef.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRef.BorderThickness = 1;
            BtnRef.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnRef.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnRef.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnRef.CornerRadius = 8;
            BtnRef.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnRef.DaskArray = null;
            BtnRef.DoubleClickEnable = true;
            BtnRef.DropKey = System.Windows.Forms.Keys.Space;
            BtnRef.FineEnable = false;
            BtnRef.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRef.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnRef.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.Height = 40;
            BtnRef.Icon = null;
            BtnRef.IconOffset = 10;
            BtnRef.IconSize = new System.Drawing.Size(24, 24);
            BtnRef.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnRef.IsChoosed = false;
            BtnRef.IsIndicatorShow = false;
            BtnRef.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnRef.Location = new System.Drawing.Point(123, 789);
            BtnRef.Margin = new System.Windows.Forms.Padding(2);
            BtnRef.MouseinBackColor = System.Drawing.Color.Silver;
            BtnRef.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRef.MouseInBorderThickness = 1;
            BtnRef.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.Name = "BtnRef";
            BtnRef.PressedBackColor = System.Drawing.Color.Silver;
            BtnRef.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnRef.PressedBorderThickness = 1;
            BtnRef.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.Size = new System.Drawing.Size(80, 40);
            BtnRef.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnRef.StylizeFlag = true;
            BtnRef.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnRef.SVGPath = "";
            BtnRef.TabIndex = 41;
            BtnRef.Text = "Ref";
            BtnRef.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnRef.Click += BtnRef_Click;
            // 
            // BtnDigital
            // 
            BtnDigital.Adjustable = false;
            BtnDigital.BackColor = System.Drawing.Color.Transparent;
            BtnDigital.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDigital.BorderThickness = 1;
            BtnDigital.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnDigital.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnDigital.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnDigital.CornerRadius = 8;
            BtnDigital.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnDigital.DaskArray = null;
            BtnDigital.DoubleClickEnable = true;
            BtnDigital.DropKey = System.Windows.Forms.Keys.Space;
            BtnDigital.FineEnable = false;
            BtnDigital.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDigital.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnDigital.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.Height = 40;
            BtnDigital.Icon = null;
            BtnDigital.IconOffset = 10;
            BtnDigital.IconSize = new System.Drawing.Size(24, 24);
            BtnDigital.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnDigital.IsChoosed = false;
            BtnDigital.IsIndicatorShow = false;
            BtnDigital.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnDigital.Location = new System.Drawing.Point(231, 789);
            BtnDigital.Margin = new System.Windows.Forms.Padding(2);
            BtnDigital.MouseinBackColor = System.Drawing.Color.Silver;
            BtnDigital.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDigital.MouseInBorderThickness = 1;
            BtnDigital.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.Name = "BtnDigital";
            BtnDigital.PressedBackColor = System.Drawing.Color.Silver;
            BtnDigital.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnDigital.PressedBorderThickness = 1;
            BtnDigital.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.Size = new System.Drawing.Size(80, 40);
            BtnDigital.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnDigital.StylizeFlag = true;
            BtnDigital.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnDigital.SVGPath = "";
            BtnDigital.TabIndex = 42;
            BtnDigital.Text = "Digital";
            BtnDigital.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnDigital.Click += BtnDigital_Click;
            // 
            // BtnBus
            // 
            BtnBus.Adjustable = false;
            BtnBus.BackColor = System.Drawing.Color.Transparent;
            BtnBus.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnBus.BorderThickness = 1;
            BtnBus.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnBus.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnBus.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnBus.CornerRadius = 8;
            BtnBus.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnBus.DaskArray = null;
            BtnBus.DoubleClickEnable = true;
            BtnBus.DropKey = System.Windows.Forms.Keys.Space;
            BtnBus.FineEnable = false;
            BtnBus.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnBus.Font = new System.Drawing.Font("MiSans Demibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnBus.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.Height = 40;
            BtnBus.Icon = null;
            BtnBus.IconOffset = 10;
            BtnBus.IconSize = new System.Drawing.Size(24, 24);
            BtnBus.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnBus.IsChoosed = false;
            BtnBus.IsIndicatorShow = false;
            BtnBus.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnBus.Location = new System.Drawing.Point(348, 789);
            BtnBus.Margin = new System.Windows.Forms.Padding(2);
            BtnBus.MouseinBackColor = System.Drawing.Color.Silver;
            BtnBus.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnBus.MouseInBorderThickness = 1;
            BtnBus.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.Name = "BtnBus";
            BtnBus.PressedBackColor = System.Drawing.Color.Silver;
            BtnBus.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnBus.PressedBorderThickness = 1;
            BtnBus.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.Size = new System.Drawing.Size(80, 40);
            BtnBus.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnBus.StylizeFlag = true;
            BtnBus.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnBus.SVGPath = "";
            BtnBus.TabIndex = 43;
            BtnBus.Text = "Bus";
            BtnBus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnBus.Click += BtnBus_Click;
            // 
            // CircVScale
            // 
            CircVScale.GroundBackColor = System.Drawing.Color.DarkGray;
            CircVScale.Location = new System.Drawing.Point(59, 863);
            CircVScale.Name = "CircVScale";
            CircVScale.Progress = 0;
            CircVScale.ProgressBackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            CircVScale.ProgressColor = System.Drawing.Color.LimeGreen;
            CircVScale.Size = new System.Drawing.Size(112, 112);
            CircVScale.StartAngle = -90;
            CircVScale.TabIndex = 44;
            CircVScale.Thickness = 10;
            CircVScale.Click += CircVScale_Click;
            // 
            // CircVPosition
            // 
            CircVPosition.GroundBackColor = System.Drawing.Color.DarkGray;
            CircVPosition.Location = new System.Drawing.Point(298, 873);
            CircVPosition.Name = "CircVPosition";
            CircVPosition.Progress = 0;
            CircVPosition.ProgressBackColor = System.Drawing.Color.FromArgb(64, 64, 64);
            CircVPosition.ProgressColor = System.Drawing.Color.LimeGreen;
            CircVPosition.Size = new System.Drawing.Size(80, 80);
            CircVPosition.StartAngle = -90;
            CircVPosition.TabIndex = 45;
            CircVPosition.Thickness = 10;
            CircVPosition.Click += CircVPosition_Click;
            // 
            // BtnC1
            // 
            BtnC1.Adjustable = false;
            BtnC1.BackColor = System.Drawing.Color.Transparent;
            BtnC1.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC1.BorderThickness = 1;
            BtnC1.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnC1.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnC1.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnC1.CornerRadius = 8;
            BtnC1.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnC1.DaskArray = null;
            BtnC1.DoubleClickEnable = true;
            BtnC1.DropKey = System.Windows.Forms.Keys.Space;
            BtnC1.FineEnable = false;
            BtnC1.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC1.Font = new System.Drawing.Font("MiSans Demibold", 10.5F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnC1.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.Height = 40;
            BtnC1.Icon = null;
            BtnC1.IconOffset = 10;
            BtnC1.IconSize = new System.Drawing.Size(24, 24);
            BtnC1.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnC1.IsChoosed = false;
            BtnC1.IsIndicatorShow = false;
            BtnC1.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnC1.Location = new System.Drawing.Point(11, 1005);
            BtnC1.Margin = new System.Windows.Forms.Padding(2);
            BtnC1.MouseinBackColor = System.Drawing.Color.Silver;
            BtnC1.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC1.MouseInBorderThickness = 1;
            BtnC1.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.Name = "BtnC1";
            BtnC1.PressedBackColor = System.Drawing.Color.Silver;
            BtnC1.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC1.PressedBorderThickness = 1;
            BtnC1.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.Size = new System.Drawing.Size(80, 40);
            BtnC1.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnC1.StylizeFlag = true;
            BtnC1.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC1.SVGPath = "";
            BtnC1.TabIndex = 46;
            BtnC1.Text = "1";
            BtnC1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnC1.Click += BtnC1_Click;
            // 
            // BtnC2
            // 
            BtnC2.Adjustable = false;
            BtnC2.BackColor = System.Drawing.Color.Transparent;
            BtnC2.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC2.BorderThickness = 1;
            BtnC2.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnC2.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnC2.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnC2.CornerRadius = 8;
            BtnC2.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnC2.DaskArray = null;
            BtnC2.DoubleClickEnable = true;
            BtnC2.DropKey = System.Windows.Forms.Keys.Space;
            BtnC2.FineEnable = false;
            BtnC2.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC2.Font = new System.Drawing.Font("MiSans Demibold", 10.5F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnC2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.Height = 40;
            BtnC2.Icon = null;
            BtnC2.IconOffset = 10;
            BtnC2.IconSize = new System.Drawing.Size(24, 24);
            BtnC2.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnC2.IsChoosed = false;
            BtnC2.IsIndicatorShow = false;
            BtnC2.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnC2.Location = new System.Drawing.Point(123, 1005);
            BtnC2.Margin = new System.Windows.Forms.Padding(2);
            BtnC2.MouseinBackColor = System.Drawing.Color.Silver;
            BtnC2.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC2.MouseInBorderThickness = 1;
            BtnC2.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.Name = "BtnC2";
            BtnC2.PressedBackColor = System.Drawing.Color.Silver;
            BtnC2.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC2.PressedBorderThickness = 1;
            BtnC2.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.Size = new System.Drawing.Size(80, 40);
            BtnC2.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnC2.StylizeFlag = true;
            BtnC2.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC2.SVGPath = "";
            BtnC2.TabIndex = 47;
            BtnC2.Text = "2";
            BtnC2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnC2.Click += BtnC2_Click;
            // 
            // BtnC3
            // 
            BtnC3.Adjustable = false;
            BtnC3.BackColor = System.Drawing.Color.Transparent;
            BtnC3.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC3.BorderThickness = 1;
            BtnC3.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnC3.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnC3.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnC3.CornerRadius = 8;
            BtnC3.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnC3.DaskArray = null;
            BtnC3.DoubleClickEnable = true;
            BtnC3.DropKey = System.Windows.Forms.Keys.Space;
            BtnC3.FineEnable = false;
            BtnC3.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC3.Font = new System.Drawing.Font("MiSans Demibold", 10.5F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnC3.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.Height = 40;
            BtnC3.Icon = null;
            BtnC3.IconOffset = 10;
            BtnC3.IconSize = new System.Drawing.Size(24, 24);
            BtnC3.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnC3.IsChoosed = false;
            BtnC3.IsIndicatorShow = false;
            BtnC3.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnC3.Location = new System.Drawing.Point(231, 1005);
            BtnC3.Margin = new System.Windows.Forms.Padding(2);
            BtnC3.MouseinBackColor = System.Drawing.Color.Silver;
            BtnC3.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC3.MouseInBorderThickness = 1;
            BtnC3.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.Name = "BtnC3";
            BtnC3.PressedBackColor = System.Drawing.Color.Silver;
            BtnC3.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC3.PressedBorderThickness = 1;
            BtnC3.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.Size = new System.Drawing.Size(80, 40);
            BtnC3.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnC3.StylizeFlag = true;
            BtnC3.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC3.SVGPath = "";
            BtnC3.TabIndex = 48;
            BtnC3.Text = "3";
            BtnC3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnC3.Click += BtnC3_Click;
            // 
            // BtnC4
            // 
            BtnC4.Adjustable = false;
            BtnC4.BackColor = System.Drawing.Color.Transparent;
            BtnC4.BorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC4.BorderThickness = 1;
            BtnC4.ChoosedBackColor = System.Drawing.Color.Gray;
            BtnC4.ChoosedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.ChoosedMouseinBackColor = System.Drawing.Color.Gray;
            BtnC4.ChoosedPressedBackColor = System.Drawing.Color.Gray;
            BtnC4.CornerRadius = 8;
            BtnC4.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnC4.DaskArray = null;
            BtnC4.DoubleClickEnable = true;
            BtnC4.DropKey = System.Windows.Forms.Keys.Space;
            BtnC4.FineEnable = false;
            BtnC4.FocusedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC4.Font = new System.Drawing.Font("MiSans Demibold", 10.5F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            BtnC4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.Height = 40;
            BtnC4.Icon = null;
            BtnC4.IconOffset = 10;
            BtnC4.IconSize = new System.Drawing.Size(24, 24);
            BtnC4.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnC4.IsChoosed = false;
            BtnC4.IsIndicatorShow = false;
            BtnC4.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnC4.Location = new System.Drawing.Point(348, 1005);
            BtnC4.Margin = new System.Windows.Forms.Padding(2);
            BtnC4.MouseinBackColor = System.Drawing.Color.Silver;
            BtnC4.MouseinBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC4.MouseInBorderThickness = 1;
            BtnC4.MouseinForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.MouseinSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.Name = "BtnC4";
            BtnC4.PressedBackColor = System.Drawing.Color.Silver;
            BtnC4.PressedBorderColor = System.Drawing.Color.FromArgb(64, 64, 64);
            BtnC4.PressedBorderThickness = 1;
            BtnC4.PressedForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.PressedSvgForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.Size = new System.Drawing.Size(80, 40);
            BtnC4.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnC4.StylizeFlag = true;
            BtnC4.SVGForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnC4.SVGPath = "";
            BtnC4.TabIndex = 49;
            BtnC4.Text = "4";
            BtnC4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnC4.Click += BtnC4_Click;
            // 
            // Page7000X
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.Black;
            Controls.Add(BtnC4);
            Controls.Add(BtnC3);
            Controls.Add(BtnC2);
            Controls.Add(BtnC1);
            Controls.Add(CircVPosition);
            Controls.Add(CircVScale);
            Controls.Add(BtnBus);
            Controls.Add(BtnDigital);
            Controls.Add(BtnRef);
            Controls.Add(BtnMath);
            Controls.Add(CircHPosition);
            Controls.Add(CircHScale);
            Controls.Add(BtnDVM);
            Controls.Add(BtnGen);
            Controls.Add(CircFunction);
            Controls.Add(BtnClear);
            Controls.Add(BtnScreenshot);
            Controls.Add(BtnAPP);
            Controls.Add(BtnDefault);
            Controls.Add(BtnUtility);
            Controls.Add(BtnTouchLock);
            Controls.Add(BtnQuickMeas);
            Controls.Add(BtnMeas);
            Controls.Add(BtnUltraAcq);
            Controls.Add(BtnCursors);
            Controls.Add(BtnForce);
            Controls.Add(BtnMenu);
            Controls.Add(BtnAuto);
            Controls.Add(BtnNormal);
            Controls.Add(BtnSingle);
            Controls.Add(BtnAutoset);
            Controls.Add(BtnRunStop);
            Controls.Add(CircLevel);
            Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            Name = "Page7000X";
            Size = new System.Drawing.Size(490, 1100);
            ResumeLayout(false);
        }

        #endregion

        private CircularProgressBar CircLevel;
        private UserControls.ScopeXIconButton BtnRunStop;
        private UserControls.ScopeXIconButton BtnAutoset;
        private UserControls.ScopeXIconButton BtnSingle;
        private UserControls.ScopeXIconButton BtnNormal;
        private UserControls.ScopeXIconButton BtnAuto;
        private UserControls.ScopeXIconButton BtnMenu;
        private UserControls.ScopeXIconButton BtnForce;
        private UserControls.ScopeXIconButton BtnCursors;
        private UserControls.ScopeXIconButton BtnUltraAcq;
        private UserControls.ScopeXIconButton BtnMeas;
        private UserControls.ScopeXIconButton BtnQuickMeas;
        private UserControls.ScopeXIconButton BtnTouchLock;
        private UserControls.ScopeXIconButton BtnUtility;
        private UserControls.ScopeXIconButton BtnDefault;
        private UserControls.ScopeXIconButton BtnAPP;
        private UserControls.ScopeXIconButton BtnScreenshot;
        private UserControls.ScopeXIconButton BtnClear;
        private CircularProgressBar CircFunction;
        private UserControls.ScopeXIconButton BtnGen;
        private UserControls.ScopeXIconButton BtnDVM;
        private CircularProgressBar CircHScale;
        private CircularProgressBar CircHPosition;
        private UserControls.ScopeXIconButton BtnMath;
        private UserControls.ScopeXIconButton BtnRef;
        private UserControls.ScopeXIconButton BtnDigital;
        private UserControls.ScopeXIconButton BtnBus;
        private CircularProgressBar CircVScale;
        private CircularProgressBar CircVPosition;
        private UserControls.ScopeXIconButton BtnC1;
        private UserControls.ScopeXIconButton BtnC2;
        private UserControls.ScopeXIconButton BtnC3;
        private UserControls.ScopeXIconButton BtnC4;
    }
}