//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopeX.U2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopeX.U2.Properties.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 “采集”系统参数 的本地化字符串。
        /// </summary>
        internal static string AboutAcquire {
            get {
                return ResourceManager.GetString("AboutAcquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部应用 的本地化字符串。
        /// </summary>
        internal static string AboutAllApps {
            get {
                return ResourceManager.GetString("AboutAllApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “模拟”通道参数 的本地化字符串。
        /// </summary>
        internal static string AboutAnalogBadge {
            get {
                return ResourceManager.GetString("AboutAnalogBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “信号源”参数 的本地化字符串。
        /// </summary>
        internal static string AboutAwgBadge {
            get {
                return ResourceManager.GetString("AboutAwgBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “总线”通道参数 的本地化字符串。
        /// </summary>
        internal static string AboutBusBadge {
            get {
                return ResourceManager.GetString("AboutBusBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string AboutClear {
            get {
                return ResourceManager.GetString("AboutClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string AboutClose {
            get {
                return ResourceManager.GetString("AboutClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光标测量 的本地化字符串。
        /// </summary>
        internal static string AboutCursor {
            get {
                return ResourceManager.GetString("AboutCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率计 的本地化字符串。
        /// </summary>
        internal static string AboutCymometer {
            get {
                return ResourceManager.GetString("AboutCymometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “数字”通道参数 的本地化字符串。
        /// </summary>
        internal static string AboutDigitalBadge {
            get {
                return ResourceManager.GetString("AboutDigitalBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主窗口显示设置 的本地化字符串。
        /// </summary>
        internal static string AboutDisplay {
            get {
                return ResourceManager.GetString("AboutDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快采 的本地化字符串。
        /// </summary>
        internal static string AboutFastReq {
            get {
                return ResourceManager.GetString("AboutFastReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速傅里叶变换 的本地化字符串。
        /// </summary>
        internal static string AboutFft {
            get {
                return ResourceManager.GetString("AboutFft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记 的本地化字符串。
        /// </summary>
        internal static string AboutMark {
            get {
                return ResourceManager.GetString("AboutMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “数学”通道参数 的本地化字符串。
        /// </summary>
        internal static string AboutMathBadge {
            get {
                return ResourceManager.GetString("AboutMathBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数测量 的本地化字符串。
        /// </summary>
        internal static string AboutMeasurement {
            get {
                return ResourceManager.GetString("AboutMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域直方图 的本地化字符串。
        /// </summary>
        internal static string AboutNormalMani {
            get {
                return ResourceManager.GetString("AboutNormalMani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string AboutPrinter {
            get {
                return ResourceManager.GetString("AboutPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “参考”通道参数 的本地化字符串。
        /// </summary>
        internal static string AboutRefBadge {
            get {
                return ResourceManager.GetString("AboutRefBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储 的本地化字符串。
        /// </summary>
        internal static string AboutSave {
            get {
                return ResourceManager.GetString("AboutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截屏 的本地化字符串。
        /// </summary>
        internal static string AboutScreenShot {
            get {
                return ResourceManager.GetString("AboutScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波形搜索 的本地化字符串。
        /// </summary>
        internal static string AboutSearch {
            get {
                return ResourceManager.GetString("AboutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string AboutSetting {
            get {
                return ResourceManager.GetString("AboutSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数快照 的本地化字符串。
        /// </summary>
        internal static string AboutSnapShot {
            get {
                return ResourceManager.GetString("AboutSnapShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “水平”系统参数 的本地化字符串。
        /// </summary>
        internal static string AboutTimebase {
            get {
                return ResourceManager.GetString("AboutTimebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “触发”系统参数 的本地化字符串。
        /// </summary>
        internal static string AboutTrigger {
            get {
                return ResourceManager.GetString("AboutTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发状态及Run/Stop 的本地化字符串。
        /// </summary>
        internal static string AboutTriggerState {
            get {
                return ResourceManager.GetString("AboutTriggerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字电压表 的本地化字符串。
        /// </summary>
        internal static string AboutVoltmeter {
            get {
                return ResourceManager.GetString("AboutVoltmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口状态 的本地化字符串。
        /// </summary>
        internal static string AboutWindowState {
            get {
                return ResourceManager.GetString("AboutWindowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展 的本地化字符串。
        /// </summary>
        internal static string AboutZoom {
            get {
                return ResourceManager.GetString("AboutZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开一个新的“总线”通道 的本地化字符串。
        /// </summary>
        internal static string NewBus {
            get {
                return ResourceManager.GetString("NewBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开“数字”通道 的本地化字符串。
        /// </summary>
        internal static string NewDigital {
            get {
                return ResourceManager.GetString("NewDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开一个新的“数学”通道 的本地化字符串。
        /// </summary>
        internal static string NewMath {
            get {
                return ResourceManager.GetString("NewMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开一个新的“参考”通道 的本地化字符串。
        /// </summary>
        internal static string NewRef {
            get {
                return ResourceManager.GetString("NewRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开“信号源1” 的本地化字符串。
        /// </summary>
        internal static string OpenAwg1 {
            get {
                return ResourceManager.GetString("OpenAwg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开“信号源2” 的本地化字符串。
        /// </summary>
        internal static string OpenAwg2 {
            get {
                return ResourceManager.GetString("OpenAwg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动“自动设置”功能 的本地化字符串。
        /// </summary>
        internal static string SetAutoset {
            get {
                return ResourceManager.GetString("SetAutoset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换采集状态 的本地化字符串。
        /// </summary>
        internal static string SetRunStop {
            get {
                return ResourceManager.GetString("SetRunStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动“单次”触发模式 的本地化字符串。
        /// </summary>
        internal static string SetSingleTriggerMode {
            get {
                return ResourceManager.GetString("SetSingleTriggerMode", resourceCulture);
            }
        }
    }
}
