//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopeX.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopeX.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] _32Mb_32_064Mb {
            get {
                object obj = ResourceManager.GetObject("_32Mb_32_064Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] _97Mb_97_728Mb {
            get {
                object obj = ResourceManager.GetObject("_97Mb_97_728Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] Clock_Interface_Coaxial_Pair_2_048Mb {
            get {
                object obj = ResourceManager.GetObject("Clock_Interface_Coaxial_Pair_2_048Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] Clock_Interface_Symmetric_Pair_2_048Mb {
            get {
                object obj = ResourceManager.GetObject("Clock_Interface_Symmetric_Pair_2_048Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS0_Data_Contradirectional_64Mb {
            get {
                object obj = ResourceManager.GetObject("DS0_Data_Contradirectional_64Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS0_Double_64Mb {
            get {
                object obj = ResourceManager.GetObject("DS0_Double_64Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS0_Single_64Mb {
            get {
                object obj = ResourceManager.GetObject("DS0_Single_64Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS0_Timing_64Mb {
            get {
                object obj = ResourceManager.GetObject("DS0_Timing_64Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS1_1_544Mb {
            get {
                object obj = ResourceManager.GetObject("DS1_1_544Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS1_G_703_1_544M {
            get {
                object obj = ResourceManager.GetObject("DS1_G_703_1_544M", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS1_Old_Rate_1_544Mb {
            get {
                object obj = ResourceManager.GetObject("DS1_Old_Rate_1_544Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS1A_2_048Mb {
            get {
                object obj = ResourceManager.GetObject("DS1A_2_048Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS1C_3_152Mb {
            get {
                object obj = ResourceManager.GetObject("DS1C_3_152Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS2_6_312Mb {
            get {
                object obj = ResourceManager.GetObject("DS2_6_312Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS2_Rate_Coax_Pair_6_312Mb {
            get {
                object obj = ResourceManager.GetObject("DS2_Rate_Coax_Pair_6_312Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS2_Rate_Symmetric_Pair_6_312Mb {
            get {
                object obj = ResourceManager.GetObject("DS2_Rate_Symmetric_Pair_6_312Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS3_44_736Mb {
            get {
                object obj = ResourceManager.GetObject("DS3_44_736Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS3_G_703_44_736Mb {
            get {
                object obj = ResourceManager.GetObject("DS3_G_703_44_736Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS3_Old_Rate_44_736Mb {
            get {
                object obj = ResourceManager.GetObject("DS3_Old_Rate_44_736Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS4_Max_Output_138_26Mb {
            get {
                object obj = ResourceManager.GetObject("DS4_Max_Output_138_26Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] DS4NA_139_26Mb {
            get {
                object obj = ResourceManager.GetObject("DS4NA_139_26Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] E1_Coaxial_Pair_2_048Mb {
            get {
                object obj = ResourceManager.GetObject("E1_Coaxial_Pair_2_048Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] E1_Symmetric_Pair_2_048Mb {
            get {
                object obj = ResourceManager.GetObject("E1_Symmetric_Pair_2_048Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] E2_8_448Mb {
            get {
                object obj = ResourceManager.GetObject("E2_8_448Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] E3_34_368Mb {
            get {
                object obj = ResourceManager.GetObject("E3_34_368Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] E4_Binary_0_139_26Mb {
            get {
                object obj = ResourceManager.GetObject("E4_Binary_0_139_26Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] E4_Binary_1_139_26Mb {
            get {
                object obj = ResourceManager.GetObject("E4_Binary_1_139_26Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] HST1_480Mb {
            get {
                object obj = ResourceManager.GetObject("HST1_480Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] HST2_480Mb {
            get {
                object obj = ResourceManager.GetObject("HST2_480Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] HST3_480Mb {
            get {
                object obj = ResourceManager.GetObject("HST3_480Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] HST4_480Mb {
            get {
                object obj = ResourceManager.GetObject("HST4_480Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] HST5_480Mb {
            get {
                object obj = ResourceManager.GetObject("HST5_480Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] HST6_480Mb {
            get {
                object obj = ResourceManager.GetObject("HST6_480Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STM_0_CMI_0_51_84Mb {
            get {
                object obj = ResourceManager.GetObject("STM_0_CMI_0_51_84Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STM_0_CMI_1_51_84Mb {
            get {
                object obj = ResourceManager.GetObject("STM_0_CMI_1_51_84Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STM_0_HDBx_51_84Mb {
            get {
                object obj = ResourceManager.GetObject("STM_0_HDBx_51_84Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STM1E_Binary_0_155_52Mb {
            get {
                object obj = ResourceManager.GetObject("STM1E_Binary_0_155_52Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STM1E_Binary_1_155_52Mb {
            get {
                object obj = ResourceManager.GetObject("STM1E_Binary_1_155_52Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STS_1_Eye_51_84Mb {
            get {
                object obj = ResourceManager.GetObject("STS_1_Eye_51_84Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STS_1_Pulse_51_84Mb {
            get {
                object obj = ResourceManager.GetObject("STS_1_Pulse_51_84Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STS_3_155_52Mb {
            get {
                object obj = ResourceManager.GetObject("STS_3_155_52Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static Byte[] STS_3_Max_Output_155_52Mb {
            get {
                object obj = ResourceManager.GetObject("STS_3_Max_Output_155_52Mb", resourceCulture);
                return ((Byte[])(obj));
            }
        }
    }
}
