//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopeX.Updater {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class UpdateSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UpdateSettings defaultInstance = ((UpdateSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UpdateSettings())));
        
        public static UpdateSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CyBootProgrammer3.0.img")]
        public string USBDefaultImgFileName {
            get {
                return ((string)(this["USBDefaultImgFileName"]));
            }
            set {
                this["USBDefaultImgFileName"] = value;
            }
        }
    }
}
