namespace ScopeX.U2
{
    partial class ParameterPage
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要修改
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt1 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt2 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle1 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle1 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle2 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle3 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle2 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle4 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle5 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle6 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle3 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle7 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle8 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle9 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle4 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle10 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle11 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle12 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle5 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle13 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle14 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle15 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle6 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle16 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle17 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle18 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle7 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle19 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle20 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle21 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle8 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle22 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle23 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle24 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle9 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle25 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle26 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle27 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle10 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle28 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle29 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle30 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt3 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt4 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt5 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt6 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt7 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt8 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt9 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle11 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle31 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle32 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle33 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle12 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle34 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle35 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle36 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt10 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt11 = new ScopeX.UserControls.DefaultHighlightPrompt();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle13 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle37 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle38 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle39 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle buttonStyle14 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle40 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle41 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle buttonBaseStyle42 = new ScopeX.UserControls.ScopeXNumericEditBox.ButtonBaseStyle();
            ScopeX.UserControls.DefaultHighlightPrompt defaultHighlightPrompt12 = new ScopeX.UserControls.DefaultHighlightPrompt();
            CbxFFTLength = new ScopeX.UserControls.ComboBoxEx();
            LblRBW = new ScopeX.UserControls.ScopeXLabel();
            LblFFTLength = new ScopeX.UserControls.ScopeXLabel();
            NebRBW = new ScopeX.UserControls.ScopeXNumericEditBox();
            NebSpan = new ScopeX.UserControls.ScopeXNumericEditBox();
            NebCenterFrequency = new ScopeX.UserControls.ScopeXNumericEditBox();
            NebEndFrequency = new ScopeX.UserControls.ScopeXNumericEditBox();
            NebStartFrequency = new ScopeX.UserControls.ScopeXNumericEditBox();
            LblEndFrequency = new ScopeX.UserControls.ScopeXLabel();
            LblStartFrequency = new ScopeX.UserControls.ScopeXLabel();
            LblCenterFrequency = new ScopeX.UserControls.ScopeXLabel();
            LblSpan = new ScopeX.UserControls.ScopeXLabel();
            CbxSTFTStep = new ScopeX.UserControls.ComboBoxEx();
            CbxSTFTDataLength = new ScopeX.UserControls.ComboBoxEx();
            LblSTFTStep = new ScopeX.UserControls.ScopeXLabel();
            LblSTFTDataLength = new ScopeX.UserControls.ScopeXLabel();
            CbxWindowType = new ScopeX.UserControls.ComboBoxEx();
            LblWindowType = new ScopeX.UserControls.ScopeXLabel();
            NebTimeScale = new ScopeX.UserControls.ScopeXNumericEditBox();
            LblTimeScale = new ScopeX.UserControls.ScopeXLabel();
            LblTimeFreqSpan = new ScopeX.UserControls.ScopeXLabel();
            CbxTimeFreqSpan = new ScopeX.UserControls.ComboBoxEx();
            NebTimeStep = new ScopeX.UserControls.ScopeXNumericEditBox();
            LblTimeStep = new ScopeX.UserControls.ScopeXLabel();
            SuspendLayout();
            // 
            // CbxFFTLength
            // 
            CbxFFTLength.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxFFTLength.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxFFTLength.BorderThickness = 0;
            CbxFFTLength.ContainerBackColor = null;
            CbxFFTLength.ContainerForeColor = null;
            CbxFFTLength.CornerRadius = 0;
            CbxFFTLength.DataSource = null;
            CbxFFTLength.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            CbxFFTLength.DropDownHeight = 200;
            CbxFFTLength.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            CbxFFTLength.DropDownWidth = 200;
            CbxFFTLength.DropKey = System.Windows.Forms.Keys.Space;
            CbxFFTLength.DroppedDown = false;
            CbxFFTLength.FocusColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxFFTLength.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            CbxFFTLength.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            CbxFFTLength.FormattingEnabled = true;
            CbxFFTLength.GetDisPlayName = null;
            CbxFFTLength.Height = 30;
            CbxFFTLength.ImageMode = false;
            CbxFFTLength.ItemHeight = 28;
            CbxFFTLength.Items.AddRange(new object[] { "8", "16", "32", "64", "128", "256", "512", "1024", "2048", "4096", "8192", "16384" });
            CbxFFTLength.KeyDropEnble = true;
            CbxFFTLength.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            CbxFFTLength.Location = new System.Drawing.Point(25, 38);
            CbxFFTLength.MaxDropDownItems = 8;
            CbxFFTLength.Name = "CbxFFTLength";
            CbxFFTLength.RectBtnWidth = 20;
            CbxFFTLength.SelectedBackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            CbxFFTLength.SelectedIndex = -1;
            CbxFFTLength.SelectedItem = null;
            CbxFFTLength.SelectedText = "";
            CbxFFTLength.Size = new System.Drawing.Size(200, 30);
            CbxFFTLength.Soreted = false;
            CbxFFTLength.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            CbxFFTLength.StylizeFlag = true;
            CbxFFTLength.TabIndex = 17;
            CbxFFTLength.Text = "";
            CbxFFTLength.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            CbxFFTLength.VerticalAlignment = System.Windows.Forms.VisualStyles.VerticalAlignment.Center;
            CbxFFTLength.SelectedValueChanged += CbxFFTLength_SelectedIndexChanged;
            // 
            // LblRBW
            // 
            LblRBW.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblRBW.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblRBW.BorderThickness = 0;
            LblRBW.CornerRadius = 0;
            LblRBW.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblRBW.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblRBW.HighlightPrompt = defaultHighlightPrompt1;
            LblRBW.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblRBW.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblRBW.Location = new System.Drawing.Point(254, 14);
            LblRBW.MultyLineFlag = false;
            LblRBW.Name = "LblRBW";
            LblRBW.Size = new System.Drawing.Size(200, 18);
            LblRBW.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblRBW.StylizeFlag = false;
            LblRBW.TabIndex = 18;
            LblRBW.TabStop = false;
            LblRBW.Text = "RBW";
            LblRBW.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblRBW.Token = null;
            // 
            // LblFFTLength
            // 
            LblFFTLength.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblFFTLength.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblFFTLength.BorderThickness = 0;
            LblFFTLength.CornerRadius = 0;
            LblFFTLength.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblFFTLength.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblFFTLength.HighlightPrompt = defaultHighlightPrompt2;
            LblFFTLength.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblFFTLength.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblFFTLength.Location = new System.Drawing.Point(25, 14);
            LblFFTLength.MultyLineFlag = false;
            LblFFTLength.Name = "LblFFTLength";
            LblFFTLength.Size = new System.Drawing.Size(200, 18);
            LblFFTLength.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblFFTLength.StylizeFlag = false;
            LblFFTLength.TabIndex = 16;
            LblFFTLength.TabStop = false;
            LblFFTLength.Text = "FFT长度";
            LblFFTLength.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblFFTLength.Token = null;
            // 
            // NebRBW
            // 
            NebRBW.AddButtonImg = null;
            buttonBaseStyle1.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle1.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle1.BorderThickness = 0;
            buttonBaseStyle1.ForeColor = System.Drawing.Color.White;
            buttonStyle1.MouseClickStyle = buttonBaseStyle1;
            buttonBaseStyle2.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle2.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle2.BorderThickness = 0;
            buttonBaseStyle2.ForeColor = System.Drawing.Color.White;
            buttonStyle1.MouseInStyle = buttonBaseStyle2;
            buttonBaseStyle3.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle3.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle3.BorderThickness = 0;
            buttonBaseStyle3.ForeColor = System.Drawing.Color.White;
            buttonStyle1.NomalStyle = buttonBaseStyle3;
            NebRBW.AddButtonStyle = buttonStyle1;
            NebRBW.AllwaysShowFocusImage = false;
            NebRBW.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebRBW.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebRBW.BorderThickness = 0;
            NebRBW.DisableHoldOnInput = false;
            NebRBW.DropKey = System.Windows.Forms.Keys.Space;
            NebRBW.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebRBW.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebRBW.FocusImage = null;
            NebRBW.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebRBW.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebRBW.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebRBW.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebRBW.Height = 30;
            NebRBW.HoldOnSpeedLevel = 10;
            NebRBW.IconWidthProportion = 1F;
            NebRBW.Interval = 0.1D;
            NebRBW.LanguageKey = null;
            NebRBW.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebRBW.Location = new System.Drawing.Point(254, 38);
            NebRBW.MaxValue = 100D;
            NebRBW.MinValue = -100D;
            NebRBW.Name = "NebRBW";
            NebRBW.Size = new System.Drawing.Size(200, 30);
            NebRBW.StringFormatFunc = null;
            NebRBW.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebRBW.StylizeFlag = true;
            NebRBW.SubButtonImg = null;
            buttonBaseStyle4.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle4.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle4.BorderThickness = 0;
            buttonBaseStyle4.ForeColor = System.Drawing.Color.White;
            buttonStyle2.MouseClickStyle = buttonBaseStyle4;
            buttonBaseStyle5.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle5.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle5.BorderThickness = 0;
            buttonBaseStyle5.ForeColor = System.Drawing.Color.White;
            buttonStyle2.MouseInStyle = buttonBaseStyle5;
            buttonBaseStyle6.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle6.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle6.BorderThickness = 0;
            buttonBaseStyle6.ForeColor = System.Drawing.Color.White;
            buttonStyle2.NomalStyle = buttonBaseStyle6;
            NebRBW.SubButtonStyle = buttonStyle2;
            NebRBW.TabIndex = 19;
            NebRBW.Value = 0D;
            // 
            // NebSpan
            // 
            NebSpan.AddButtonImg = null;
            buttonBaseStyle7.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle7.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle7.BorderThickness = 0;
            buttonBaseStyle7.ForeColor = System.Drawing.Color.White;
            buttonStyle3.MouseClickStyle = buttonBaseStyle7;
            buttonBaseStyle8.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle8.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle8.BorderThickness = 0;
            buttonBaseStyle8.ForeColor = System.Drawing.Color.White;
            buttonStyle3.MouseInStyle = buttonBaseStyle8;
            buttonBaseStyle9.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle9.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle9.BorderThickness = 0;
            buttonBaseStyle9.ForeColor = System.Drawing.Color.White;
            buttonStyle3.NomalStyle = buttonBaseStyle9;
            NebSpan.AddButtonStyle = buttonStyle3;
            NebSpan.AllwaysShowFocusImage = false;
            NebSpan.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebSpan.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebSpan.BorderThickness = 0;
            NebSpan.DisableHoldOnInput = false;
            NebSpan.DropKey = System.Windows.Forms.Keys.Space;
            NebSpan.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebSpan.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebSpan.FocusImage = null;
            NebSpan.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebSpan.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebSpan.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebSpan.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebSpan.Height = 30;
            NebSpan.HoldOnSpeedLevel = 10;
            NebSpan.IconWidthProportion = 1F;
            NebSpan.Interval = 0.1D;
            NebSpan.LanguageKey = null;
            NebSpan.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebSpan.Location = new System.Drawing.Point(25, 174);
            NebSpan.MaxValue = 100D;
            NebSpan.MinValue = 0D;
            NebSpan.Name = "NebSpan";
            NebSpan.Size = new System.Drawing.Size(200, 30);
            NebSpan.StringFormatFunc = null;
            NebSpan.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebSpan.StylizeFlag = true;
            NebSpan.SubButtonImg = null;
            buttonBaseStyle10.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle10.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle10.BorderThickness = 0;
            buttonBaseStyle10.ForeColor = System.Drawing.Color.White;
            buttonStyle4.MouseClickStyle = buttonBaseStyle10;
            buttonBaseStyle11.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle11.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle11.BorderThickness = 0;
            buttonBaseStyle11.ForeColor = System.Drawing.Color.White;
            buttonStyle4.MouseInStyle = buttonBaseStyle11;
            buttonBaseStyle12.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle12.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle12.BorderThickness = 0;
            buttonBaseStyle12.ForeColor = System.Drawing.Color.White;
            buttonStyle4.NomalStyle = buttonBaseStyle12;
            NebSpan.SubButtonStyle = buttonStyle4;
            NebSpan.TabIndex = 25;
            NebSpan.Value = 0D;
            // 
            // NebCenterFrequency
            // 
            NebCenterFrequency.AddButtonImg = null;
            buttonBaseStyle13.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle13.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle13.BorderThickness = 0;
            buttonBaseStyle13.ForeColor = System.Drawing.Color.White;
            buttonStyle5.MouseClickStyle = buttonBaseStyle13;
            buttonBaseStyle14.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle14.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle14.BorderThickness = 0;
            buttonBaseStyle14.ForeColor = System.Drawing.Color.White;
            buttonStyle5.MouseInStyle = buttonBaseStyle14;
            buttonBaseStyle15.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle15.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle15.BorderThickness = 0;
            buttonBaseStyle15.ForeColor = System.Drawing.Color.White;
            buttonStyle5.NomalStyle = buttonBaseStyle15;
            NebCenterFrequency.AddButtonStyle = buttonStyle5;
            NebCenterFrequency.AllwaysShowFocusImage = false;
            NebCenterFrequency.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebCenterFrequency.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebCenterFrequency.BorderThickness = 0;
            NebCenterFrequency.DisableHoldOnInput = false;
            NebCenterFrequency.DropKey = System.Windows.Forms.Keys.Space;
            NebCenterFrequency.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebCenterFrequency.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebCenterFrequency.FocusImage = null;
            NebCenterFrequency.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebCenterFrequency.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebCenterFrequency.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebCenterFrequency.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebCenterFrequency.Height = 30;
            NebCenterFrequency.HoldOnSpeedLevel = 10;
            NebCenterFrequency.IconWidthProportion = 1F;
            NebCenterFrequency.Interval = 0.1D;
            NebCenterFrequency.LanguageKey = null;
            NebCenterFrequency.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebCenterFrequency.Location = new System.Drawing.Point(25, 108);
            NebCenterFrequency.MaxValue = 100D;
            NebCenterFrequency.MinValue = 0D;
            NebCenterFrequency.Name = "NebCenterFrequency";
            NebCenterFrequency.Size = new System.Drawing.Size(200, 30);
            NebCenterFrequency.StringFormatFunc = null;
            NebCenterFrequency.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebCenterFrequency.StylizeFlag = true;
            NebCenterFrequency.SubButtonImg = null;
            buttonBaseStyle16.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle16.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle16.BorderThickness = 0;
            buttonBaseStyle16.ForeColor = System.Drawing.Color.White;
            buttonStyle6.MouseClickStyle = buttonBaseStyle16;
            buttonBaseStyle17.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle17.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle17.BorderThickness = 0;
            buttonBaseStyle17.ForeColor = System.Drawing.Color.White;
            buttonStyle6.MouseInStyle = buttonBaseStyle17;
            buttonBaseStyle18.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle18.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle18.BorderThickness = 0;
            buttonBaseStyle18.ForeColor = System.Drawing.Color.White;
            buttonStyle6.NomalStyle = buttonBaseStyle18;
            NebCenterFrequency.SubButtonStyle = buttonStyle6;
            NebCenterFrequency.TabIndex = 21;
            NebCenterFrequency.Value = 0D;
            // 
            // NebEndFrequency
            // 
            NebEndFrequency.AddButtonImg = null;
            buttonBaseStyle19.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle19.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle19.BorderThickness = 0;
            buttonBaseStyle19.ForeColor = System.Drawing.Color.White;
            buttonStyle7.MouseClickStyle = buttonBaseStyle19;
            buttonBaseStyle20.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle20.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle20.BorderThickness = 0;
            buttonBaseStyle20.ForeColor = System.Drawing.Color.White;
            buttonStyle7.MouseInStyle = buttonBaseStyle20;
            buttonBaseStyle21.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle21.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle21.BorderThickness = 0;
            buttonBaseStyle21.ForeColor = System.Drawing.Color.White;
            buttonStyle7.NomalStyle = buttonBaseStyle21;
            NebEndFrequency.AddButtonStyle = buttonStyle7;
            NebEndFrequency.AllwaysShowFocusImage = false;
            NebEndFrequency.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebEndFrequency.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebEndFrequency.BorderThickness = 0;
            NebEndFrequency.DisableHoldOnInput = false;
            NebEndFrequency.DropKey = System.Windows.Forms.Keys.Space;
            NebEndFrequency.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebEndFrequency.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebEndFrequency.FocusImage = null;
            NebEndFrequency.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebEndFrequency.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebEndFrequency.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebEndFrequency.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebEndFrequency.Height = 30;
            NebEndFrequency.HoldOnSpeedLevel = 10;
            NebEndFrequency.IconWidthProportion = 1F;
            NebEndFrequency.Interval = 0.1D;
            NebEndFrequency.LanguageKey = null;
            NebEndFrequency.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebEndFrequency.Location = new System.Drawing.Point(254, 174);
            NebEndFrequency.MaxValue = 100D;
            NebEndFrequency.MinValue = 0D;
            NebEndFrequency.Name = "NebEndFrequency";
            NebEndFrequency.Size = new System.Drawing.Size(200, 30);
            NebEndFrequency.StringFormatFunc = null;
            NebEndFrequency.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebEndFrequency.StylizeFlag = true;
            NebEndFrequency.SubButtonImg = null;
            buttonBaseStyle22.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle22.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle22.BorderThickness = 0;
            buttonBaseStyle22.ForeColor = System.Drawing.Color.White;
            buttonStyle8.MouseClickStyle = buttonBaseStyle22;
            buttonBaseStyle23.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle23.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle23.BorderThickness = 0;
            buttonBaseStyle23.ForeColor = System.Drawing.Color.White;
            buttonStyle8.MouseInStyle = buttonBaseStyle23;
            buttonBaseStyle24.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle24.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle24.BorderThickness = 0;
            buttonBaseStyle24.ForeColor = System.Drawing.Color.White;
            buttonStyle8.NomalStyle = buttonBaseStyle24;
            NebEndFrequency.SubButtonStyle = buttonStyle8;
            NebEndFrequency.TabIndex = 27;
            NebEndFrequency.Value = 0D;
            // 
            // NebStartFrequency
            // 
            NebStartFrequency.AddButtonImg = null;
            buttonBaseStyle25.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle25.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle25.BorderThickness = 0;
            buttonBaseStyle25.ForeColor = System.Drawing.Color.White;
            buttonStyle9.MouseClickStyle = buttonBaseStyle25;
            buttonBaseStyle26.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle26.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle26.BorderThickness = 0;
            buttonBaseStyle26.ForeColor = System.Drawing.Color.White;
            buttonStyle9.MouseInStyle = buttonBaseStyle26;
            buttonBaseStyle27.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle27.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle27.BorderThickness = 0;
            buttonBaseStyle27.ForeColor = System.Drawing.Color.White;
            buttonStyle9.NomalStyle = buttonBaseStyle27;
            NebStartFrequency.AddButtonStyle = buttonStyle9;
            NebStartFrequency.AllwaysShowFocusImage = false;
            NebStartFrequency.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebStartFrequency.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebStartFrequency.BorderThickness = 0;
            NebStartFrequency.DisableHoldOnInput = false;
            NebStartFrequency.DropKey = System.Windows.Forms.Keys.Space;
            NebStartFrequency.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebStartFrequency.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebStartFrequency.FocusImage = null;
            NebStartFrequency.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebStartFrequency.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebStartFrequency.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebStartFrequency.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebStartFrequency.Height = 30;
            NebStartFrequency.HoldOnSpeedLevel = 10;
            NebStartFrequency.IconWidthProportion = 1F;
            NebStartFrequency.Interval = 0.1D;
            NebStartFrequency.LanguageKey = null;
            NebStartFrequency.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebStartFrequency.Location = new System.Drawing.Point(254, 108);
            NebStartFrequency.MaxValue = 100D;
            NebStartFrequency.MinValue = 0D;
            NebStartFrequency.Name = "NebStartFrequency";
            NebStartFrequency.Size = new System.Drawing.Size(200, 30);
            NebStartFrequency.StringFormatFunc = null;
            NebStartFrequency.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebStartFrequency.StylizeFlag = true;
            NebStartFrequency.SubButtonImg = null;
            buttonBaseStyle28.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle28.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle28.BorderThickness = 0;
            buttonBaseStyle28.ForeColor = System.Drawing.Color.White;
            buttonStyle10.MouseClickStyle = buttonBaseStyle28;
            buttonBaseStyle29.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle29.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle29.BorderThickness = 0;
            buttonBaseStyle29.ForeColor = System.Drawing.Color.White;
            buttonStyle10.MouseInStyle = buttonBaseStyle29;
            buttonBaseStyle30.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle30.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle30.BorderThickness = 0;
            buttonBaseStyle30.ForeColor = System.Drawing.Color.White;
            buttonStyle10.NomalStyle = buttonBaseStyle30;
            NebStartFrequency.SubButtonStyle = buttonStyle10;
            NebStartFrequency.TabIndex = 23;
            NebStartFrequency.Value = 0D;
            // 
            // LblEndFrequency
            // 
            LblEndFrequency.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblEndFrequency.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblEndFrequency.BorderThickness = 0;
            LblEndFrequency.CornerRadius = 0;
            LblEndFrequency.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblEndFrequency.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblEndFrequency.HighlightPrompt = defaultHighlightPrompt3;
            LblEndFrequency.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblEndFrequency.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblEndFrequency.Location = new System.Drawing.Point(254, 150);
            LblEndFrequency.MultyLineFlag = false;
            LblEndFrequency.Name = "LblEndFrequency";
            LblEndFrequency.Size = new System.Drawing.Size(200, 18);
            LblEndFrequency.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblEndFrequency.StylizeFlag = false;
            LblEndFrequency.TabIndex = 26;
            LblEndFrequency.TabStop = false;
            LblEndFrequency.Text = "终止频率";
            LblEndFrequency.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblEndFrequency.Token = null;
            // 
            // LblStartFrequency
            // 
            LblStartFrequency.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblStartFrequency.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblStartFrequency.BorderThickness = 0;
            LblStartFrequency.CornerRadius = 0;
            LblStartFrequency.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblStartFrequency.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblStartFrequency.HighlightPrompt = defaultHighlightPrompt4;
            LblStartFrequency.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblStartFrequency.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblStartFrequency.Location = new System.Drawing.Point(254, 84);
            LblStartFrequency.MultyLineFlag = false;
            LblStartFrequency.Name = "LblStartFrequency";
            LblStartFrequency.Size = new System.Drawing.Size(200, 18);
            LblStartFrequency.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblStartFrequency.StylizeFlag = false;
            LblStartFrequency.TabIndex = 22;
            LblStartFrequency.TabStop = false;
            LblStartFrequency.Text = "起始频率";
            LblStartFrequency.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblStartFrequency.Token = null;
            // 
            // LblCenterFrequency
            // 
            LblCenterFrequency.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblCenterFrequency.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblCenterFrequency.BorderThickness = 0;
            LblCenterFrequency.CornerRadius = 0;
            LblCenterFrequency.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblCenterFrequency.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblCenterFrequency.HighlightPrompt = defaultHighlightPrompt5;
            LblCenterFrequency.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblCenterFrequency.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblCenterFrequency.Location = new System.Drawing.Point(25, 84);
            LblCenterFrequency.MultyLineFlag = false;
            LblCenterFrequency.Name = "LblCenterFrequency";
            LblCenterFrequency.Size = new System.Drawing.Size(200, 18);
            LblCenterFrequency.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblCenterFrequency.StylizeFlag = false;
            LblCenterFrequency.TabIndex = 20;
            LblCenterFrequency.TabStop = false;
            LblCenterFrequency.Text = "中心频率";
            LblCenterFrequency.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblCenterFrequency.Token = null;
            // 
            // LblSpan
            // 
            LblSpan.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblSpan.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblSpan.BorderThickness = 0;
            LblSpan.CornerRadius = 0;
            LblSpan.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblSpan.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblSpan.HighlightPrompt = defaultHighlightPrompt6;
            LblSpan.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblSpan.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblSpan.Location = new System.Drawing.Point(25, 150);
            LblSpan.MultyLineFlag = false;
            LblSpan.Name = "LblSpan";
            LblSpan.Size = new System.Drawing.Size(200, 18);
            LblSpan.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblSpan.StylizeFlag = false;
            LblSpan.TabIndex = 24;
            LblSpan.TabStop = false;
            LblSpan.Text = "频域跨度";
            LblSpan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblSpan.Token = null;
            // 
            // CbxSTFTStep
            // 
            CbxSTFTStep.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxSTFTStep.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxSTFTStep.BorderThickness = 0;
            CbxSTFTStep.ContainerBackColor = null;
            CbxSTFTStep.ContainerForeColor = null;
            CbxSTFTStep.CornerRadius = 0;
            CbxSTFTStep.DataSource = null;
            CbxSTFTStep.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            CbxSTFTStep.DropDownHeight = 200;
            CbxSTFTStep.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            CbxSTFTStep.DropDownWidth = 196;
            CbxSTFTStep.DropKey = System.Windows.Forms.Keys.Space;
            CbxSTFTStep.DroppedDown = false;
            CbxSTFTStep.FocusColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxSTFTStep.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            CbxSTFTStep.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            CbxSTFTStep.FormattingEnabled = true;
            CbxSTFTStep.GetDisPlayName = null;
            CbxSTFTStep.Height = 26;
            CbxSTFTStep.ImageMode = false;
            CbxSTFTStep.ItemHeight = 28;
            CbxSTFTStep.Items.AddRange(new object[] { "8", "16", "32", "64", "128", "256", "512", "1024", "2048" });
            CbxSTFTStep.KeyDropEnble = true;
            CbxSTFTStep.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            CbxSTFTStep.Location = new System.Drawing.Point(258, 315);
            CbxSTFTStep.MaxDropDownItems = 8;
            CbxSTFTStep.Name = "CbxSTFTStep";
            CbxSTFTStep.RectBtnWidth = 20;
            CbxSTFTStep.SelectedBackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            CbxSTFTStep.SelectedIndex = -1;
            CbxSTFTStep.SelectedItem = null;
            CbxSTFTStep.SelectedText = "";
            CbxSTFTStep.Size = new System.Drawing.Size(196, 26);
            CbxSTFTStep.Soreted = false;
            CbxSTFTStep.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            CbxSTFTStep.StylizeFlag = false;
            CbxSTFTStep.TabIndex = 29;
            CbxSTFTStep.Text = "";
            CbxSTFTStep.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            CbxSTFTStep.VerticalAlignment = System.Windows.Forms.VisualStyles.VerticalAlignment.Center;
            CbxSTFTStep.SelectedValueChanged += CbxSTFTStep_SelectedIndexChanged;
            // 
            // CbxSTFTDataLength
            // 
            CbxSTFTDataLength.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxSTFTDataLength.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxSTFTDataLength.BorderThickness = 0;
            CbxSTFTDataLength.ContainerBackColor = null;
            CbxSTFTDataLength.ContainerForeColor = null;
            CbxSTFTDataLength.CornerRadius = 0;
            CbxSTFTDataLength.DataSource = null;
            CbxSTFTDataLength.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            CbxSTFTDataLength.DropDownHeight = 200;
            CbxSTFTDataLength.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            CbxSTFTDataLength.DropDownWidth = 200;
            CbxSTFTDataLength.DropKey = System.Windows.Forms.Keys.Space;
            CbxSTFTDataLength.DroppedDown = false;
            CbxSTFTDataLength.FocusColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxSTFTDataLength.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            CbxSTFTDataLength.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            CbxSTFTDataLength.FormattingEnabled = true;
            CbxSTFTDataLength.GetDisPlayName = null;
            CbxSTFTDataLength.Height = 26;
            CbxSTFTDataLength.ImageMode = false;
            CbxSTFTDataLength.ItemHeight = 28;
            CbxSTFTDataLength.Items.AddRange(new object[] { "128", "256", "512", "1024", "2048", "4096", "8192", "16384", "32768" });
            CbxSTFTDataLength.KeyDropEnble = true;
            CbxSTFTDataLength.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            CbxSTFTDataLength.Location = new System.Drawing.Point(25, 315);
            CbxSTFTDataLength.MaxDropDownItems = 8;
            CbxSTFTDataLength.Name = "CbxSTFTDataLength";
            CbxSTFTDataLength.RectBtnWidth = 20;
            CbxSTFTDataLength.SelectedBackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            CbxSTFTDataLength.SelectedIndex = -1;
            CbxSTFTDataLength.SelectedItem = null;
            CbxSTFTDataLength.SelectedText = "";
            CbxSTFTDataLength.Size = new System.Drawing.Size(200, 26);
            CbxSTFTDataLength.Soreted = false;
            CbxSTFTDataLength.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            CbxSTFTDataLength.StylizeFlag = false;
            CbxSTFTDataLength.TabIndex = 28;
            CbxSTFTDataLength.Text = "";
            CbxSTFTDataLength.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            CbxSTFTDataLength.VerticalAlignment = System.Windows.Forms.VisualStyles.VerticalAlignment.Center;
            CbxSTFTDataLength.SelectedValueChanged += CbxSTFTDataLength_SelectedIndexChanged;
            // 
            // LblSTFTStep
            // 
            LblSTFTStep.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblSTFTStep.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblSTFTStep.BorderThickness = 0;
            LblSTFTStep.CornerRadius = 0;
            LblSTFTStep.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblSTFTStep.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblSTFTStep.HighlightPrompt = defaultHighlightPrompt7;
            LblSTFTStep.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblSTFTStep.Location = new System.Drawing.Point(258, 294);
            LblSTFTStep.MultyLineFlag = false;
            LblSTFTStep.Name = "LblSTFTStep";
            LblSTFTStep.Size = new System.Drawing.Size(74, 16);
            LblSTFTStep.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblSTFTStep.StylizeFlag = false;
            LblSTFTStep.TabIndex = 31;
            LblSTFTStep.TabStop = false;
            LblSTFTStep.Text = "STFT步进";
            LblSTFTStep.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblSTFTStep.Token = null;
            // 
            // LblSTFTDataLength
            // 
            LblSTFTDataLength.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblSTFTDataLength.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblSTFTDataLength.BorderThickness = 0;
            LblSTFTDataLength.CornerRadius = 0;
            LblSTFTDataLength.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblSTFTDataLength.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblSTFTDataLength.HighlightPrompt = defaultHighlightPrompt8;
            LblSTFTDataLength.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblSTFTDataLength.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblSTFTDataLength.Location = new System.Drawing.Point(25, 294);
            LblSTFTDataLength.MultyLineFlag = false;
            LblSTFTDataLength.Name = "LblSTFTDataLength";
            LblSTFTDataLength.Size = new System.Drawing.Size(91, 16);
            LblSTFTDataLength.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblSTFTDataLength.StylizeFlag = false;
            LblSTFTDataLength.TabIndex = 30;
            LblSTFTDataLength.TabStop = false;
            LblSTFTDataLength.Text = "STFT分析长度";
            LblSTFTDataLength.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblSTFTDataLength.Token = null;
            // 
            // CbxWindowType
            // 
            CbxWindowType.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxWindowType.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxWindowType.BorderThickness = 0;
            CbxWindowType.ContainerBackColor = null;
            CbxWindowType.ContainerForeColor = null;
            CbxWindowType.CornerRadius = 0;
            CbxWindowType.DataSource = null;
            CbxWindowType.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            CbxWindowType.DropDownHeight = 200;
            CbxWindowType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            CbxWindowType.DropDownWidth = 200;
            CbxWindowType.DropKey = System.Windows.Forms.Keys.Space;
            CbxWindowType.DroppedDown = false;
            CbxWindowType.FocusColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxWindowType.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            CbxWindowType.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            CbxWindowType.FormattingEnabled = true;
            CbxWindowType.GetDisPlayName = null;
            CbxWindowType.Height = 26;
            CbxWindowType.ImageMode = false;
            CbxWindowType.ItemHeight = 28;
            CbxWindowType.Items.AddRange(new object[] { "Rectangle", "Hann", "Hamming", "Blackman", "Flattop", "Kaiser", "Gaussian" });
            CbxWindowType.KeyDropEnble = true;
            CbxWindowType.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            CbxWindowType.Location = new System.Drawing.Point(25, 380);
            CbxWindowType.MaxDropDownItems = 8;
            CbxWindowType.Name = "CbxWindowType";
            CbxWindowType.RectBtnWidth = 20;
            CbxWindowType.SelectedBackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            CbxWindowType.SelectedIndex = -1;
            CbxWindowType.SelectedItem = null;
            CbxWindowType.SelectedText = "";
            CbxWindowType.Size = new System.Drawing.Size(200, 26);
            CbxWindowType.Soreted = false;
            CbxWindowType.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            CbxWindowType.StylizeFlag = false;
            CbxWindowType.TabIndex = 32;
            CbxWindowType.Text = "";
            CbxWindowType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            CbxWindowType.VerticalAlignment = System.Windows.Forms.VisualStyles.VerticalAlignment.Center;
            // 
            // LblWindowType
            // 
            LblWindowType.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblWindowType.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblWindowType.BorderThickness = 0;
            LblWindowType.CornerRadius = 0;
            LblWindowType.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblWindowType.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblWindowType.HighlightPrompt = defaultHighlightPrompt9;
            LblWindowType.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblWindowType.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblWindowType.Location = new System.Drawing.Point(25, 359);
            LblWindowType.MultyLineFlag = false;
            LblWindowType.Name = "LblWindowType";
            LblWindowType.Size = new System.Drawing.Size(74, 16);
            LblWindowType.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblWindowType.StylizeFlag = false;
            LblWindowType.TabIndex = 33;
            LblWindowType.Text = "窗";
            LblWindowType.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblWindowType.Token = null;
            // 
            // NebTimeScale
            // 
            NebTimeScale.AddButtonImg = null;
            buttonBaseStyle31.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle31.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle31.BorderThickness = 0;
            buttonBaseStyle31.ForeColor = System.Drawing.Color.White;
            buttonStyle11.MouseClickStyle = buttonBaseStyle31;
            buttonBaseStyle32.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle32.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle32.BorderThickness = 0;
            buttonBaseStyle32.ForeColor = System.Drawing.Color.White;
            buttonStyle11.MouseInStyle = buttonBaseStyle32;
            buttonBaseStyle33.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle33.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle33.BorderThickness = 0;
            buttonBaseStyle33.ForeColor = System.Drawing.Color.White;
            buttonStyle11.NomalStyle = buttonBaseStyle33;
            NebTimeScale.AddButtonStyle = buttonStyle11;
            NebTimeScale.AllwaysShowFocusImage = false;
            NebTimeScale.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebTimeScale.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebTimeScale.BorderThickness = 0;
            NebTimeScale.DisableHoldOnInput = false;
            NebTimeScale.DropKey = System.Windows.Forms.Keys.Space;
            NebTimeScale.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebTimeScale.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebTimeScale.FocusImage = null;
            NebTimeScale.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebTimeScale.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebTimeScale.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebTimeScale.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebTimeScale.Height = 30;
            NebTimeScale.HoldOnSpeedLevel = 10;
            NebTimeScale.IconWidthProportion = 1F;
            NebTimeScale.Interval = 0.1D;
            NebTimeScale.LanguageKey = null;
            NebTimeScale.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebTimeScale.Location = new System.Drawing.Point(254, 246);
            NebTimeScale.MaxValue = 100D;
            NebTimeScale.MinValue = 0D;
            NebTimeScale.Name = "NebTimeScale";
            NebTimeScale.Size = new System.Drawing.Size(200, 30);
            NebTimeScale.StringFormatFunc = null;
            NebTimeScale.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebTimeScale.StylizeFlag = true;
            NebTimeScale.SubButtonImg = null;
            buttonBaseStyle34.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle34.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle34.BorderThickness = 0;
            buttonBaseStyle34.ForeColor = System.Drawing.Color.White;
            buttonStyle12.MouseClickStyle = buttonBaseStyle34;
            buttonBaseStyle35.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle35.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle35.BorderThickness = 0;
            buttonBaseStyle35.ForeColor = System.Drawing.Color.White;
            buttonStyle12.MouseInStyle = buttonBaseStyle35;
            buttonBaseStyle36.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle36.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle36.BorderThickness = 0;
            buttonBaseStyle36.ForeColor = System.Drawing.Color.White;
            buttonStyle12.NomalStyle = buttonBaseStyle36;
            NebTimeScale.SubButtonStyle = buttonStyle12;
            NebTimeScale.TabIndex = 37;
            NebTimeScale.Value = 0D;
            // 
            // LblTimeScale
            // 
            LblTimeScale.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblTimeScale.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblTimeScale.BorderThickness = 0;
            LblTimeScale.CornerRadius = 0;
            LblTimeScale.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblTimeScale.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblTimeScale.HighlightPrompt = defaultHighlightPrompt10;
            LblTimeScale.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblTimeScale.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblTimeScale.Location = new System.Drawing.Point(254, 222);
            LblTimeScale.MultyLineFlag = false;
            LblTimeScale.Name = "LblTimeScale";
            LblTimeScale.Size = new System.Drawing.Size(200, 18);
            LblTimeScale.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblTimeScale.StylizeFlag = false;
            LblTimeScale.TabIndex = 36;
            LblTimeScale.TabStop = false;
            LblTimeScale.Text = "时频图时间分辨率";
            LblTimeScale.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblTimeScale.Token = null;
            // 
            // LblTimeFreqSpan
            // 
            LblTimeFreqSpan.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblTimeFreqSpan.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblTimeFreqSpan.BorderThickness = 0;
            LblTimeFreqSpan.CornerRadius = 0;
            LblTimeFreqSpan.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblTimeFreqSpan.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblTimeFreqSpan.HighlightPrompt = defaultHighlightPrompt11;
            LblTimeFreqSpan.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblTimeFreqSpan.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblTimeFreqSpan.Location = new System.Drawing.Point(25, 222);
            LblTimeFreqSpan.MultyLineFlag = false;
            LblTimeFreqSpan.Name = "LblTimeFreqSpan";
            LblTimeFreqSpan.Size = new System.Drawing.Size(200, 18);
            LblTimeFreqSpan.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblTimeFreqSpan.StylizeFlag = false;
            LblTimeFreqSpan.TabIndex = 34;
            LblTimeFreqSpan.TabStop = false;
            LblTimeFreqSpan.Text = "时频跨度";
            LblTimeFreqSpan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblTimeFreqSpan.Token = null;
            // 
            // CbxTimeFreqSpan
            // 
            CbxTimeFreqSpan.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxTimeFreqSpan.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxTimeFreqSpan.BorderThickness = 0;
            CbxTimeFreqSpan.ContainerBackColor = null;
            CbxTimeFreqSpan.ContainerForeColor = null;
            CbxTimeFreqSpan.CornerRadius = 0;
            CbxTimeFreqSpan.DataSource = null;
            CbxTimeFreqSpan.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            CbxTimeFreqSpan.DropDownHeight = 200;
            CbxTimeFreqSpan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            CbxTimeFreqSpan.DropDownWidth = 200;
            CbxTimeFreqSpan.DropKey = System.Windows.Forms.Keys.Space;
            CbxTimeFreqSpan.DroppedDown = false;
            CbxTimeFreqSpan.FocusColor = System.Drawing.Color.FromArgb(53, 54, 58);
            CbxTimeFreqSpan.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            CbxTimeFreqSpan.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            CbxTimeFreqSpan.FormattingEnabled = true;
            CbxTimeFreqSpan.GetDisPlayName = null;
            CbxTimeFreqSpan.Height = 30;
            CbxTimeFreqSpan.ImageMode = false;
            CbxTimeFreqSpan.ItemHeight = 28;
            CbxTimeFreqSpan.Items.AddRange(new object[] { "8", "16", "32", "64", "128", "256", "512", "1024", "2048", "4096", "8192", "16384" });
            CbxTimeFreqSpan.KeyDropEnble = true;
            CbxTimeFreqSpan.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            CbxTimeFreqSpan.Location = new System.Drawing.Point(25, 246);
            CbxTimeFreqSpan.MaxDropDownItems = 8;
            CbxTimeFreqSpan.Name = "CbxTimeFreqSpan";
            CbxTimeFreqSpan.RectBtnWidth = 20;
            CbxTimeFreqSpan.SelectedBackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            CbxTimeFreqSpan.SelectedIndex = -1;
            CbxTimeFreqSpan.SelectedItem = null;
            CbxTimeFreqSpan.SelectedText = "";
            CbxTimeFreqSpan.Size = new System.Drawing.Size(200, 30);
            CbxTimeFreqSpan.Soreted = false;
            CbxTimeFreqSpan.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            CbxTimeFreqSpan.StylizeFlag = true;
            CbxTimeFreqSpan.TabIndex = 38;
            CbxTimeFreqSpan.Text = "";
            CbxTimeFreqSpan.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            CbxTimeFreqSpan.VerticalAlignment = System.Windows.Forms.VisualStyles.VerticalAlignment.Center;
            // 
            // NebTimeStep
            // 
            NebTimeStep.AddButtonImg = null;
            buttonBaseStyle37.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle37.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle37.BorderThickness = 0;
            buttonBaseStyle37.ForeColor = System.Drawing.Color.White;
            buttonStyle13.MouseClickStyle = buttonBaseStyle37;
            buttonBaseStyle38.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle38.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle38.BorderThickness = 0;
            buttonBaseStyle38.ForeColor = System.Drawing.Color.White;
            buttonStyle13.MouseInStyle = buttonBaseStyle38;
            buttonBaseStyle39.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle39.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle39.BorderThickness = 0;
            buttonBaseStyle39.ForeColor = System.Drawing.Color.White;
            buttonStyle13.NomalStyle = buttonBaseStyle39;
            NebTimeStep.AddButtonStyle = buttonStyle13;
            NebTimeStep.AllwaysShowFocusImage = false;
            NebTimeStep.BackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebTimeStep.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebTimeStep.BorderThickness = 0;
            NebTimeStep.DisableHoldOnInput = false;
            NebTimeStep.DropKey = System.Windows.Forms.Keys.Space;
            NebTimeStep.FocusBoederColor = System.Drawing.Color.FromArgb(53, 54, 58);
            NebTimeStep.FocusForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            NebTimeStep.FocusImage = null;
            NebTimeStep.FocusImagePosition = ScopeX.UserControls.ScopeXNumericEditBox.FocusImagePositionEnum.Left;
            NebTimeStep.FocusImageRect = new System.Drawing.Rectangle(0, 0, 0, 0);
            NebTimeStep.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            NebTimeStep.ForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            NebTimeStep.Height = 30;
            NebTimeStep.HoldOnSpeedLevel = 10;
            NebTimeStep.IconWidthProportion = 1F;
            NebTimeStep.Interval = 0.1D;
            NebTimeStep.LanguageKey = null;
            NebTimeStep.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Ignore;
            NebTimeStep.Location = new System.Drawing.Point(254, 380);
            NebTimeStep.MaxValue = 100D;
            NebTimeStep.MinValue = 0D;
            NebTimeStep.Name = "NebTimeStep";
            NebTimeStep.Size = new System.Drawing.Size(200, 30);
            NebTimeStep.StringFormatFunc = null;
            NebTimeStep.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            NebTimeStep.StylizeFlag = true;
            NebTimeStep.SubButtonImg = null;
            buttonBaseStyle40.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle40.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle40.BorderThickness = 0;
            buttonBaseStyle40.ForeColor = System.Drawing.Color.White;
            buttonStyle14.MouseClickStyle = buttonBaseStyle40;
            buttonBaseStyle41.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle41.BorderColor = System.Drawing.Color.Green;
            buttonBaseStyle41.BorderThickness = 0;
            buttonBaseStyle41.ForeColor = System.Drawing.Color.White;
            buttonStyle14.MouseInStyle = buttonBaseStyle41;
            buttonBaseStyle42.BackColor = System.Drawing.Color.FromArgb(0, 157, 255);
            buttonBaseStyle42.BorderColor = System.Drawing.Color.Transparent;
            buttonBaseStyle42.BorderThickness = 0;
            buttonBaseStyle42.ForeColor = System.Drawing.Color.White;
            buttonStyle14.NomalStyle = buttonBaseStyle42;
            NebTimeStep.SubButtonStyle = buttonStyle14;
            NebTimeStep.TabIndex = 40;
            NebTimeStep.Value = 0D;
            // 
            // LblTimeStep
            // 
            LblTimeStep.BackColor = System.Drawing.Color.FromArgb(41, 42, 45);
            LblTimeStep.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            LblTimeStep.BorderThickness = 0;
            LblTimeStep.CornerRadius = 0;
            LblTimeStep.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LblTimeStep.ForeColor = System.Drawing.Color.FromArgb(232, 234, 237);
            LblTimeStep.HighlightPrompt = defaultHighlightPrompt12;
            LblTimeStep.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            LblTimeStep.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LblTimeStep.Location = new System.Drawing.Point(254, 357);
            LblTimeStep.MultyLineFlag = false;
            LblTimeStep.Name = "LblTimeStep";
            LblTimeStep.Size = new System.Drawing.Size(200, 18);
            LblTimeStep.StyleFlags = ScopeX.UserControls.Style.StyleFlag.None;
            LblTimeStep.StylizeFlag = false;
            LblTimeStep.TabIndex = 39;
            LblTimeStep.TabStop = false;
            LblTimeStep.Text = "释抑时间";
            LblTimeStep.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            LblTimeStep.Token = null;
            // 
            // ParameterPage
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(39, 41, 48);
            Controls.Add(NebTimeStep);
            Controls.Add(LblTimeStep);
            Controls.Add(CbxTimeFreqSpan);
            Controls.Add(NebTimeScale);
            Controls.Add(LblTimeScale);
            Controls.Add(LblTimeFreqSpan);
            Controls.Add(CbxWindowType);
            Controls.Add(LblWindowType);
            Controls.Add(CbxSTFTStep);
            Controls.Add(CbxSTFTDataLength);
            Controls.Add(LblSTFTStep);
            Controls.Add(LblSTFTDataLength);
            Controls.Add(CbxFFTLength);
            Controls.Add(LblRBW);
            Controls.Add(LblFFTLength);
            Controls.Add(NebRBW);
            Controls.Add(NebSpan);
            Controls.Add(NebCenterFrequency);
            Controls.Add(NebEndFrequency);
            Controls.Add(NebStartFrequency);
            Controls.Add(LblEndFrequency);
            Controls.Add(LblStartFrequency);
            Controls.Add(LblCenterFrequency);
            Controls.Add(LblSpan);
            Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            Name = "ParameterPage";
            Size = new System.Drawing.Size(482, 425);
            ResumeLayout(false);
        }

        #endregion
        private ScopeX.UserControls.ComboBoxEx CbxFFTLength;
        private ScopeX.UserControls.ScopeXLabel LblRBW;
        private ScopeX.UserControls.ScopeXLabel LblFFTLength;
        private ScopeX.UserControls.ScopeXNumericEditBox NebRBW;
        private ScopeX.UserControls.ScopeXNumericEditBox NebSpan;
        private ScopeX.UserControls.ScopeXNumericEditBox NebCenterFrequency;
        private ScopeX.UserControls.ScopeXNumericEditBox NebEndFrequency;
        private ScopeX.UserControls.ScopeXNumericEditBox NebStartFrequency;
        private ScopeX.UserControls.ScopeXLabel LblEndFrequency;
        private ScopeX.UserControls.ScopeXLabel LblStartFrequency;
        private ScopeX.UserControls.ScopeXLabel LblCenterFrequency;
        private ScopeX.UserControls.ScopeXLabel LblSpan;
        private ScopeX.UserControls.ComboBoxEx CbxSTFTStep;
        private ScopeX.UserControls.ComboBoxEx CbxSTFTDataLength;
        private ScopeX.UserControls.ScopeXLabel LblSTFTStep;
        private ScopeX.UserControls.ScopeXLabel LblSTFTDataLength;
        private ScopeX.UserControls.ComboBoxEx CbxWindowType;
        private ScopeX.UserControls.ScopeXLabel LblWindowType;
        private ScopeX.UserControls.ScopeXNumericEditBox NebTimeScale;
        private ScopeX.UserControls.ScopeXLabel LblTimeScale;
        private ScopeX.UserControls.ScopeXLabel LblTimeFreqSpan;
        private ScopeX.UserControls.ComboBoxEx CbxTimeFreqSpan;
        private ScopeX.UserControls.ScopeXNumericEditBox NebTimeStep;
        private ScopeX.UserControls.ScopeXLabel LblTimeStep;
    }
}
