
namespace ScopeX.U2
{
    partial class DsoResultStrip
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要修改
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            TlpBody = new System.Windows.Forms.TableLayoutPanel();
            BtnAddMeasure = new UserControls.ScopeXIconButton();
            LpVoltmeterItem = new UserControls.ScopeXListPage();
            LpCymometerItem = new UserControls.ScopeXListPage();
            LpMeasureItem10 = new UserControls.ScopeXListPage();
            LpMeasureItem9 = new UserControls.ScopeXListPage();
            LpMeasureItem8 = new UserControls.ScopeXListPage();
            LpMeasureItem7 = new UserControls.ScopeXListPage();
            LpMeasureItem6 = new UserControls.ScopeXListPage();
            LpMeasureItem5 = new UserControls.ScopeXListPage();
            LpMeasureItem4 = new UserControls.ScopeXListPage();
            LpMeasureItem3 = new UserControls.ScopeXListPage();
            LpMeasureItem2 = new UserControls.ScopeXListPage();
            LpMeasureItem1 = new UserControls.ScopeXListPage();
            BtnMeasureTool = new UserControls.ScopeXIconButton();
            TmUpdate = new System.Timers.Timer();
            TlpBody.SuspendLayout();
            SuspendLayout();
            // 
            // TlpBody
            // 
            TlpBody.BackColor = System.Drawing.Color.FromArgb(33, 33, 40);
            TlpBody.ColumnCount = 14;
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 62F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 231F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 233F));
            TlpBody.Controls.Add(BtnAddMeasure, 11, 0);
            TlpBody.Controls.Add(LpVoltmeterItem, 12, 0);
            TlpBody.Controls.Add(LpCymometerItem, 13, 0);
            TlpBody.Controls.Add(LpMeasureItem10, 10, 0);
            TlpBody.Controls.Add(LpMeasureItem9, 9, 0);
            TlpBody.Controls.Add(LpMeasureItem8, 8, 0);
            TlpBody.Controls.Add(LpMeasureItem7, 7, 0);
            TlpBody.Controls.Add(LpMeasureItem6, 6, 0);
            TlpBody.Controls.Add(LpMeasureItem5, 5, 0);
            TlpBody.Controls.Add(LpMeasureItem4, 4, 0);
            TlpBody.Controls.Add(LpMeasureItem3, 3, 0);
            TlpBody.Controls.Add(LpMeasureItem2, 2, 0);
            TlpBody.Controls.Add(LpMeasureItem1, 1, 0);
            TlpBody.Controls.Add(BtnMeasureTool, 0, 0);
            TlpBody.Dock = System.Windows.Forms.DockStyle.Fill;
            TlpBody.Location = new System.Drawing.Point(0, 0);
            TlpBody.Margin = new System.Windows.Forms.Padding(4);
            TlpBody.Name = "TlpBody";
            TlpBody.RowCount = 1;
            TlpBody.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            TlpBody.Size = new System.Drawing.Size(2469, 49);
            TlpBody.TabIndex = 0;
            TlpBody.TabStop = true;
            // 
            // BtnAddMeasure
            // 
            BtnAddMeasure.BackColor = System.Drawing.Color.Transparent;
            BtnAddMeasure.BorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            BtnAddMeasure.BorderThickness = 1;
            BtnAddMeasure.CornerRadius = 0;
            BtnAddMeasure.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnAddMeasure.DaskArray = null;
            BtnAddMeasure.Dock = System.Windows.Forms.DockStyle.Left;
            BtnAddMeasure.DropKey = System.Windows.Forms.Keys.Space;
            BtnAddMeasure.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            BtnAddMeasure.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            BtnAddMeasure.Height = 37;
            BtnAddMeasure.Icon = Properties.Resources.AddMeasParam;
            BtnAddMeasure.IconOffset = 2;
            BtnAddMeasure.IconSize = new System.Drawing.Size(20, 32);
            BtnAddMeasure.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnAddMeasure.IsChoosed = false;
            BtnAddMeasure.IsIndicatorShow = false;
            BtnAddMeasure.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnAddMeasure.Location = new System.Drawing.Point(2006, 6);
            BtnAddMeasure.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            BtnAddMeasure.MouseinBackColor = System.Drawing.Color.FromArgb(53, 54, 58);
            BtnAddMeasure.MouseinBorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            BtnAddMeasure.MouseInBorderThickness = 0;
            BtnAddMeasure.MouseinForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            BtnAddMeasure.MouseinSvgForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            BtnAddMeasure.Name = "BtnAddMeasure";
            BtnAddMeasure.PressedBackColor = System.Drawing.Color.Gray;
            BtnAddMeasure.PressedBorderColor = System.Drawing.Color.FromArgb(53, 54, 58);
            BtnAddMeasure.PressedBorderThickness = 0;
            BtnAddMeasure.PressedForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            BtnAddMeasure.PressedSvgForeColor = System.Drawing.Color.FromArgb(0, 157, 255);
            BtnAddMeasure.Size = new System.Drawing.Size(0, 37);
            BtnAddMeasure.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnAddMeasure.StylizeFlag = true;
            BtnAddMeasure.SVGForeColor = System.Drawing.Color.FromArgb(185, 192, 199);
            BtnAddMeasure.SVGPath = "";
            BtnAddMeasure.TabIndex = 29;
            BtnAddMeasure.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnAddMeasure.Visible = false;
            BtnAddMeasure.Click += BtnAddMeasure_Click;
            // 
            // LpVoltmeterItem
            // 
            LpVoltmeterItem.AutoHide = false;
            LpVoltmeterItem.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpVoltmeterItem.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpVoltmeterItem.BorderThickness = 1;
            LpVoltmeterItem.DashArray = null;
            LpVoltmeterItem.DataSource = null;
            LpVoltmeterItem.DisplayForeColor = System.Drawing.Color.Green;
            LpVoltmeterItem.DisplayMember = "Key";
            LpVoltmeterItem.Dock = System.Windows.Forms.DockStyle.Fill;
            LpVoltmeterItem.DrawValueOffset = 0;
            LpVoltmeterItem.DropBackOpacity = 100;
            LpVoltmeterItem.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.DropedHeaderHeight = 20;
            LpVoltmeterItem.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.DropedMeasNameItemHeight = 18;
            LpVoltmeterItem.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.DropedValueItemHeight = 18;
            LpVoltmeterItem.DropOpacity = 100;
            LpVoltmeterItem.DroppedDown = false;
            LpVoltmeterItem.EnbleNomalBorder = true;
            LpVoltmeterItem.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.ForeColor = System.Drawing.Color.Pink;
            LpVoltmeterItem.Header = ScopeX.Controls.Language.LanguageManger.Instance.GetIDMessage("DianYaBiao");
            LpVoltmeterItem.HeaderBackColor = System.Drawing.Color.Violet;
            LpVoltmeterItem.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.HeaderForeColor = System.Drawing.Color.Black;
            LpVoltmeterItem.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpVoltmeterItem.HeaderInfos = new string[] { "info", "" };
            LpVoltmeterItem.HeadWidthGain = 30;
            LpVoltmeterItem.IsHitTestVisible = true;
            LpVoltmeterItem.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpVoltmeterItem.Location = new System.Drawing.Point(2009, 4);
            LpVoltmeterItem.Margin = new System.Windows.Forms.Padding(4);
            LpVoltmeterItem.MaxItemViewCount = 7;
            LpVoltmeterItem.MeasItemName = "";
            LpVoltmeterItem.MeasNameItemHeight = 24;
            LpVoltmeterItem.MinimumSize = new System.Drawing.Size(103, 42);
            LpVoltmeterItem.Name = "LpVoltmeterItem";
            LpVoltmeterItem.Percentage = 0.45F;
            LpVoltmeterItem.SelectedIndex = 0;
            LpVoltmeterItem.ShowHeader = true;
            LpVoltmeterItem.ShowHeaderInfo = true;
            LpVoltmeterItem.ShowIndicator = false;
            LpVoltmeterItem.Size = new System.Drawing.Size(223, 42);
            LpVoltmeterItem.TabIndex = 13;
            LpVoltmeterItem.Tag = "";
            LpVoltmeterItem.Text = "ScopeXListPage8";
            LpVoltmeterItem.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpVoltmeterItem.ValueForeColor = System.Drawing.Color.White;
            LpVoltmeterItem.ValueMember = "Value";
            LpVoltmeterItem.Visible = true;
            LpVoltmeterItem.MouseClick += LpVoltmeterItem_MouseClick;
            // 
            // LpCymometerItem
            // 
            LpCymometerItem.AutoHide = false;
            LpCymometerItem.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpCymometerItem.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpCymometerItem.BorderThickness = 1;
            LpCymometerItem.DashArray = null;
            LpCymometerItem.DataSource = null;
            LpCymometerItem.DisplayForeColor = System.Drawing.Color.Green;
            LpCymometerItem.DisplayMember = "Key";
            LpCymometerItem.Dock = System.Windows.Forms.DockStyle.Fill;
            LpCymometerItem.DrawValueOffset = 0;
            LpCymometerItem.DropBackOpacity = 100;
            LpCymometerItem.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.DropedHeaderHeight = 20;
            LpCymometerItem.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.DropedMeasNameItemHeight = 18;
            LpCymometerItem.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.DropedValueItemHeight = 18;
            LpCymometerItem.DropOpacity = 100;
            LpCymometerItem.DroppedDown = false;
            LpCymometerItem.EnbleNomalBorder = true;
            LpCymometerItem.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.ForeColor = System.Drawing.Color.Pink;
            LpCymometerItem.Header = ScopeX.Controls.Language.LanguageManger.Instance.GetIDMessage("PinLvJi");
            LpCymometerItem.HeaderBackColor = System.Drawing.Color.Violet;
            LpCymometerItem.HeaderFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.HeaderForeColor = System.Drawing.Color.Black;
            LpCymometerItem.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpCymometerItem.HeaderInfos = new string[] { "info", "" };
            LpCymometerItem.HeadWidthGain = 40;
            LpCymometerItem.IsHitTestVisible = true;
            LpCymometerItem.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpCymometerItem.Location = new System.Drawing.Point(2240, 4);
            LpCymometerItem.Margin = new System.Windows.Forms.Padding(4);
            LpCymometerItem.MaxItemViewCount = 7;
            LpCymometerItem.MeasItemName = "";
            LpCymometerItem.MeasNameItemHeight = 24;
            LpCymometerItem.MinimumSize = new System.Drawing.Size(103, 42);
            LpCymometerItem.Name = "LpCymometerItem";
            LpCymometerItem.Percentage = 0.45F;
            LpCymometerItem.SelectedIndex = 0;
            LpCymometerItem.ShowHeader = true;
            LpCymometerItem.ShowHeaderInfo = false;
            LpCymometerItem.ShowIndicator = false;
            LpCymometerItem.Size = new System.Drawing.Size(225, 42);
            LpCymometerItem.TabIndex = 12;
            LpCymometerItem.Tag = "";
            LpCymometerItem.Text = "ScopeXListPage8";
            LpCymometerItem.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpCymometerItem.ValueForeColor = System.Drawing.Color.White;
            LpCymometerItem.ValueMember = "Value";
            LpCymometerItem.Visible = false;
            LpCymometerItem.MouseClick += LpCymometerItem_MouseClick;
            // 
            // LpMeasureItem10
            // 
            LpMeasureItem10.AutoHide = true;
            LpMeasureItem10.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem10.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem10.BorderThickness = 1;
            LpMeasureItem10.DashArray = null;
            LpMeasureItem10.DataSource = null;
            LpMeasureItem10.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem10.DisplayMember = "";
            LpMeasureItem10.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem10.DrawValueOffset = 10;
            LpMeasureItem10.DropBackOpacity = 100;
            LpMeasureItem10.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.DropedHeaderHeight = 20;
            LpMeasureItem10.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.DropedMeasNameItemHeight = 18;
            LpMeasureItem10.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.DropedValueItemHeight = 18;
            LpMeasureItem10.DropOpacity = 100;
            LpMeasureItem10.DroppedDown = false;
            LpMeasureItem10.EnbleNomalBorder = true;
            LpMeasureItem10.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem10.Header = "P";
            LpMeasureItem10.HeaderBackColor = System.Drawing.Color.Violet;
            LpMeasureItem10.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem10.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem10.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem10.HeadWidthGain = 10;
            LpMeasureItem10.IsHitTestVisible = true;
            LpMeasureItem10.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem10.Location = new System.Drawing.Point(1812, 4);
            LpMeasureItem10.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem10.MaxItemViewCount = 7;
            LpMeasureItem10.MeasItemName = null;
            LpMeasureItem10.MeasNameItemHeight = 24;
            LpMeasureItem10.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem10.Name = "LpMeasureItem10";
            LpMeasureItem10.Percentage = 0.45F;
            LpMeasureItem10.SelectedIndex = 0;
            LpMeasureItem10.ShowHeader = true;
            LpMeasureItem10.ShowHeaderInfo = true;
            LpMeasureItem10.ShowIndicator = false;
            LpMeasureItem10.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem10.TabIndex = 10;
            LpMeasureItem10.Text = "ScopeXListPage8";
            LpMeasureItem10.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem10.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem10.ValueMember = null;
            LpMeasureItem10.Visible = false;
            // 
            // LpMeasureItem9
            // 
            LpMeasureItem9.AutoHide = true;
            LpMeasureItem9.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem9.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem9.BorderThickness = 1;
            LpMeasureItem9.DashArray = null;
            LpMeasureItem9.DataSource = null;
            LpMeasureItem9.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem9.DisplayMember = "";
            LpMeasureItem9.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem9.DrawValueOffset = 10;
            LpMeasureItem9.DropBackOpacity = 100;
            LpMeasureItem9.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.DropedHeaderHeight = 20;
            LpMeasureItem9.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.DropedMeasNameItemHeight = 18;
            LpMeasureItem9.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.DropedValueItemHeight = 18;
            LpMeasureItem9.DropOpacity = 100;
            LpMeasureItem9.DroppedDown = false;
            LpMeasureItem9.EnbleNomalBorder = true;
            LpMeasureItem9.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem9.Header = "P";
            LpMeasureItem9.HeaderBackColor = System.Drawing.Color.Violet;
            LpMeasureItem9.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem9.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem9.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem9.HeadWidthGain = 10;
            LpMeasureItem9.IsHitTestVisible = true;
            LpMeasureItem9.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem9.Location = new System.Drawing.Point(1618, 4);
            LpMeasureItem9.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem9.MaxItemViewCount = 7;
            LpMeasureItem9.MeasItemName = null;
            LpMeasureItem9.MeasNameItemHeight = 24;
            LpMeasureItem9.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem9.Name = "LpMeasureItem9";
            LpMeasureItem9.Percentage = 0.45F;
            LpMeasureItem9.SelectedIndex = 0;
            LpMeasureItem9.ShowHeader = true;
            LpMeasureItem9.ShowHeaderInfo = true;
            LpMeasureItem9.ShowIndicator = false;
            LpMeasureItem9.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem9.TabIndex = 9;
            LpMeasureItem9.Text = "ScopeXListPage8";
            LpMeasureItem9.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem9.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem9.ValueMember = null;
            LpMeasureItem9.Visible = false;
            // 
            // LpMeasureItem8
            // 
            LpMeasureItem8.AutoHide = true;
            LpMeasureItem8.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem8.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem8.BorderThickness = 1;
            LpMeasureItem8.DashArray = null;
            LpMeasureItem8.DataSource = null;
            LpMeasureItem8.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem8.DisplayMember = "";
            LpMeasureItem8.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem8.DrawValueOffset = 10;
            LpMeasureItem8.DropBackOpacity = 100;
            LpMeasureItem8.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.DropedHeaderHeight = 20;
            LpMeasureItem8.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.DropedMeasNameItemHeight = 18;
            LpMeasureItem8.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.DropedValueItemHeight = 18;
            LpMeasureItem8.DropOpacity = 100;
            LpMeasureItem8.DroppedDown = false;
            LpMeasureItem8.EnbleNomalBorder = true;
            LpMeasureItem8.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem8.Header = "P";
            LpMeasureItem8.HeaderBackColor = System.Drawing.Color.Violet;
            LpMeasureItem8.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem8.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem8.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem8.HeadWidthGain = 10;
            LpMeasureItem8.IsHitTestVisible = true;
            LpMeasureItem8.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem8.Location = new System.Drawing.Point(1424, 4);
            LpMeasureItem8.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem8.MaxItemViewCount = 7;
            LpMeasureItem8.MeasItemName = null;
            LpMeasureItem8.MeasNameItemHeight = 24;
            LpMeasureItem8.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem8.Name = "LpMeasureItem8";
            LpMeasureItem8.Percentage = 0.45F;
            LpMeasureItem8.SelectedIndex = 0;
            LpMeasureItem8.ShowHeader = true;
            LpMeasureItem8.ShowHeaderInfo = true;
            LpMeasureItem8.ShowIndicator = false;
            LpMeasureItem8.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem8.TabIndex = 8;
            LpMeasureItem8.Text = "ScopeXListPage8";
            LpMeasureItem8.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem8.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem8.ValueMember = null;
            LpMeasureItem8.Visible = false;
            // 
            // LpMeasureItem7
            // 
            LpMeasureItem7.AutoHide = true;
            LpMeasureItem7.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem7.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem7.BorderThickness = 1;
            LpMeasureItem7.DashArray = null;
            LpMeasureItem7.DataSource = null;
            LpMeasureItem7.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem7.DisplayMember = "";
            LpMeasureItem7.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem7.DrawValueOffset = 10;
            LpMeasureItem7.DropBackOpacity = 100;
            LpMeasureItem7.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.DropedHeaderHeight = 20;
            LpMeasureItem7.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.DropedMeasNameItemHeight = 18;
            LpMeasureItem7.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.DropedValueItemHeight = 18;
            LpMeasureItem7.DropOpacity = 100;
            LpMeasureItem7.DroppedDown = false;
            LpMeasureItem7.EnbleNomalBorder = true;
            LpMeasureItem7.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem7.Header = "P";
            LpMeasureItem7.HeaderBackColor = System.Drawing.Color.Violet;
            LpMeasureItem7.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem7.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem7.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem7.HeadWidthGain = 10;
            LpMeasureItem7.IsHitTestVisible = true;
            LpMeasureItem7.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem7.Location = new System.Drawing.Point(1230, 4);
            LpMeasureItem7.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem7.MaxItemViewCount = 7;
            LpMeasureItem7.MeasItemName = null;
            LpMeasureItem7.MeasNameItemHeight = 24;
            LpMeasureItem7.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem7.Name = "LpMeasureItem7";
            LpMeasureItem7.Percentage = 0.45F;
            LpMeasureItem7.SelectedIndex = 0;
            LpMeasureItem7.ShowHeader = true;
            LpMeasureItem7.ShowHeaderInfo = true;
            LpMeasureItem7.ShowIndicator = false;
            LpMeasureItem7.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem7.TabIndex = 7;
            LpMeasureItem7.Text = "ScopeXListPage9";
            LpMeasureItem7.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem7.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem7.ValueMember = null;
            LpMeasureItem7.Visible = false;
            // 
            // LpMeasureItem6
            // 
            LpMeasureItem6.AutoHide = true;
            LpMeasureItem6.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem6.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem6.BorderThickness = 1;
            LpMeasureItem6.DashArray = null;
            LpMeasureItem6.DataSource = null;
            LpMeasureItem6.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem6.DisplayMember = "";
            LpMeasureItem6.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem6.DrawValueOffset = 10;
            LpMeasureItem6.DropBackOpacity = 100;
            LpMeasureItem6.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.DropedHeaderHeight = 20;
            LpMeasureItem6.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.DropedMeasNameItemHeight = 18;
            LpMeasureItem6.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.DropedValueItemHeight = 18;
            LpMeasureItem6.DropOpacity = 100;
            LpMeasureItem6.DroppedDown = false;
            LpMeasureItem6.EnbleNomalBorder = true;
            LpMeasureItem6.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem6.Header = "P";
            LpMeasureItem6.HeaderBackColor = System.Drawing.Color.FromArgb(255, 128, 0);
            LpMeasureItem6.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem6.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem6.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem6.HeadWidthGain = 10;
            LpMeasureItem6.IsHitTestVisible = true;
            LpMeasureItem6.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem6.Location = new System.Drawing.Point(1036, 4);
            LpMeasureItem6.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem6.MaxItemViewCount = 7;
            LpMeasureItem6.MeasItemName = null;
            LpMeasureItem6.MeasNameItemHeight = 24;
            LpMeasureItem6.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem6.Name = "LpMeasureItem6";
            LpMeasureItem6.Percentage = 0.45F;
            LpMeasureItem6.SelectedIndex = 0;
            LpMeasureItem6.ShowHeader = true;
            LpMeasureItem6.ShowHeaderInfo = true;
            LpMeasureItem6.ShowIndicator = false;
            LpMeasureItem6.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem6.TabIndex = 6;
            LpMeasureItem6.Text = "ScopeXListPage5";
            LpMeasureItem6.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem6.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem6.ValueMember = null;
            LpMeasureItem6.Visible = false;
            // 
            // LpMeasureItem5
            // 
            LpMeasureItem5.AutoHide = true;
            LpMeasureItem5.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem5.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem5.BorderThickness = 1;
            LpMeasureItem5.DashArray = null;
            LpMeasureItem5.DataSource = null;
            LpMeasureItem5.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem5.DisplayMember = "";
            LpMeasureItem5.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem5.DrawValueOffset = 10;
            LpMeasureItem5.DropBackOpacity = 100;
            LpMeasureItem5.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.DropedHeaderHeight = 20;
            LpMeasureItem5.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.DropedMeasNameItemHeight = 18;
            LpMeasureItem5.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.DropedValueItemHeight = 18;
            LpMeasureItem5.DropOpacity = 100;
            LpMeasureItem5.DroppedDown = false;
            LpMeasureItem5.EnbleNomalBorder = true;
            LpMeasureItem5.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem5.Header = "P";
            LpMeasureItem5.HeaderBackColor = System.Drawing.Color.FromArgb(255, 128, 0);
            LpMeasureItem5.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem5.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem5.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem5.HeadWidthGain = 10;
            LpMeasureItem5.IsHitTestVisible = true;
            LpMeasureItem5.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem5.Location = new System.Drawing.Point(842, 4);
            LpMeasureItem5.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem5.MaxItemViewCount = 7;
            LpMeasureItem5.MeasItemName = null;
            LpMeasureItem5.MeasNameItemHeight = 24;
            LpMeasureItem5.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem5.Name = "LpMeasureItem5";
            LpMeasureItem5.Percentage = 0.45F;
            LpMeasureItem5.SelectedIndex = 0;
            LpMeasureItem5.ShowHeader = true;
            LpMeasureItem5.ShowHeaderInfo = true;
            LpMeasureItem5.ShowIndicator = false;
            LpMeasureItem5.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem5.TabIndex = 5;
            LpMeasureItem5.Text = "ScopeXListPage6";
            LpMeasureItem5.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem5.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem5.ValueMember = null;
            LpMeasureItem5.Visible = false;
            // 
            // LpMeasureItem4
            // 
            LpMeasureItem4.AutoHide = true;
            LpMeasureItem4.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem4.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem4.BorderThickness = 1;
            LpMeasureItem4.DashArray = null;
            LpMeasureItem4.DataSource = null;
            LpMeasureItem4.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem4.DisplayMember = "";
            LpMeasureItem4.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem4.DrawValueOffset = 10;
            LpMeasureItem4.DropBackOpacity = 100;
            LpMeasureItem4.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.DropedHeaderHeight = 20;
            LpMeasureItem4.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.DropedMeasNameItemHeight = 18;
            LpMeasureItem4.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.DropedValueItemHeight = 18;
            LpMeasureItem4.DropOpacity = 100;
            LpMeasureItem4.DroppedDown = false;
            LpMeasureItem4.EnbleNomalBorder = true;
            LpMeasureItem4.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem4.Header = "P";
            LpMeasureItem4.HeaderBackColor = System.Drawing.Color.FromArgb(255, 128, 0);
            LpMeasureItem4.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem4.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem4.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem4.HeadWidthGain = 10;
            LpMeasureItem4.IsHitTestVisible = true;
            LpMeasureItem4.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem4.Location = new System.Drawing.Point(648, 4);
            LpMeasureItem4.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem4.MaxItemViewCount = 7;
            LpMeasureItem4.MeasItemName = null;
            LpMeasureItem4.MeasNameItemHeight = 24;
            LpMeasureItem4.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem4.Name = "LpMeasureItem4";
            LpMeasureItem4.Percentage = 0.45F;
            LpMeasureItem4.SelectedIndex = 0;
            LpMeasureItem4.ShowHeader = true;
            LpMeasureItem4.ShowHeaderInfo = true;
            LpMeasureItem4.ShowIndicator = false;
            LpMeasureItem4.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem4.TabIndex = 4;
            LpMeasureItem4.Text = "ScopeXListPage7";
            LpMeasureItem4.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem4.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem4.ValueMember = null;
            LpMeasureItem4.Visible = false;
            // 
            // LpMeasureItem3
            // 
            LpMeasureItem3.AutoHide = true;
            LpMeasureItem3.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem3.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem3.BorderThickness = 1;
            LpMeasureItem3.DashArray = null;
            LpMeasureItem3.DataSource = null;
            LpMeasureItem3.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem3.DisplayMember = "";
            LpMeasureItem3.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem3.DrawValueOffset = 10;
            LpMeasureItem3.DropBackOpacity = 100;
            LpMeasureItem3.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.DropedHeaderHeight = 20;
            LpMeasureItem3.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.DropedMeasNameItemHeight = 18;
            LpMeasureItem3.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.DropedValueItemHeight = 18;
            LpMeasureItem3.DropOpacity = 100;
            LpMeasureItem3.DroppedDown = false;
            LpMeasureItem3.EnbleNomalBorder = true;
            LpMeasureItem3.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem3.Header = "P";
            LpMeasureItem3.HeaderBackColor = System.Drawing.Color.Pink;
            LpMeasureItem3.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem3.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem3.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem3.HeadWidthGain = 10;
            LpMeasureItem3.IsHitTestVisible = true;
            LpMeasureItem3.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem3.Location = new System.Drawing.Point(454, 4);
            LpMeasureItem3.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem3.MaxItemViewCount = 7;
            LpMeasureItem3.MeasItemName = null;
            LpMeasureItem3.MeasNameItemHeight = 24;
            LpMeasureItem3.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem3.Name = "LpMeasureItem3";
            LpMeasureItem3.Percentage = 0.45F;
            LpMeasureItem3.SelectedIndex = 0;
            LpMeasureItem3.ShowHeader = true;
            LpMeasureItem3.ShowHeaderInfo = true;
            LpMeasureItem3.ShowIndicator = false;
            LpMeasureItem3.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem3.TabIndex = 3;
            LpMeasureItem3.Text = "ScopeXListPage4";
            LpMeasureItem3.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem3.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem3.ValueMember = null;
            LpMeasureItem3.Visible = false;
            // 
            // LpMeasureItem2
            // 
            LpMeasureItem2.AutoHide = true;
            LpMeasureItem2.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem2.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem2.BorderThickness = 1;
            LpMeasureItem2.DashArray = null;
            LpMeasureItem2.DataSource = null;
            LpMeasureItem2.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem2.DisplayMember = "";
            LpMeasureItem2.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem2.DrawValueOffset = 10;
            LpMeasureItem2.DropBackOpacity = 100;
            LpMeasureItem2.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.DropedHeaderHeight = 20;
            LpMeasureItem2.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.DropedMeasNameItemHeight = 18;
            LpMeasureItem2.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.DropedValueItemHeight = 18;
            LpMeasureItem2.DropOpacity = 100;
            LpMeasureItem2.DroppedDown = false;
            LpMeasureItem2.EnbleNomalBorder = true;
            LpMeasureItem2.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem2.Header = "P";
            LpMeasureItem2.HeaderBackColor = System.Drawing.Color.Pink;
            LpMeasureItem2.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem2.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem2.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem2.HeadWidthGain = 10;
            LpMeasureItem2.IsHitTestVisible = true;
            LpMeasureItem2.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem2.Location = new System.Drawing.Point(260, 4);
            LpMeasureItem2.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem2.MaxItemViewCount = 7;
            LpMeasureItem2.MeasItemName = null;
            LpMeasureItem2.MeasNameItemHeight = 24;
            LpMeasureItem2.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem2.Name = "LpMeasureItem2";
            LpMeasureItem2.Percentage = 0.45F;
            LpMeasureItem2.SelectedIndex = 0;
            LpMeasureItem2.ShowHeader = true;
            LpMeasureItem2.ShowHeaderInfo = true;
            LpMeasureItem2.ShowIndicator = false;
            LpMeasureItem2.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem2.TabIndex = 2;
            LpMeasureItem2.Text = "ScopeXListPage3";
            LpMeasureItem2.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem2.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem2.ValueMember = null;
            LpMeasureItem2.Visible = false;
            // 
            // LpMeasureItem1
            // 
            LpMeasureItem1.AutoHide = true;
            LpMeasureItem1.BackColor = System.Drawing.Color.FromArgb(32, 32, 32);
            LpMeasureItem1.BorderColor = System.Drawing.Color.FromArgb(119, 119, 119);
            LpMeasureItem1.BorderThickness = 1;
            LpMeasureItem1.DashArray = null;
            LpMeasureItem1.DataSource = null;
            LpMeasureItem1.DisplayForeColor = System.Drawing.Color.Green;
            LpMeasureItem1.DisplayMember = "";
            LpMeasureItem1.Dock = System.Windows.Forms.DockStyle.Fill;
            LpMeasureItem1.DrawValueOffset = 10;
            LpMeasureItem1.DropBackOpacity = 100;
            LpMeasureItem1.DropedHeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.DropedHeaderHeight = 20;
            LpMeasureItem1.DropedMeasNameItemFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.DropedMeasNameItemHeight = 18;
            LpMeasureItem1.DropedValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.DropedValueItemHeight = 18;
            LpMeasureItem1.DropOpacity = 100;
            LpMeasureItem1.DroppedDown = false;
            LpMeasureItem1.EnbleNomalBorder = true;
            LpMeasureItem1.Font = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.ForeColor = System.Drawing.Color.Pink;
            LpMeasureItem1.Header = "P";
            LpMeasureItem1.HeaderBackColor = System.Drawing.Color.Pink;
            LpMeasureItem1.HeaderFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.HeaderForeColor = System.Drawing.Color.White;
            LpMeasureItem1.HeaderInfoFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.HeaderInfoForeColors = new System.Drawing.Color[] { System.Drawing.Color.White, System.Drawing.Color.White };
            LpMeasureItem1.HeaderInfos = new string[] { "info", "" };
            LpMeasureItem1.HeadWidthGain = 10;
            LpMeasureItem1.IsHitTestVisible = true;
            LpMeasureItem1.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            LpMeasureItem1.Location = new System.Drawing.Point(66, 4);
            LpMeasureItem1.Margin = new System.Windows.Forms.Padding(4);
            LpMeasureItem1.MaxItemViewCount = 7;
            LpMeasureItem1.MeasItemName = "";
            LpMeasureItem1.MeasNameItemHeight = 24;
            LpMeasureItem1.MinimumSize = new System.Drawing.Size(103, 42);
            LpMeasureItem1.Name = "LpMeasureItem1";
            LpMeasureItem1.Percentage = 0.45F;
            LpMeasureItem1.SelectedIndex = 0;
            LpMeasureItem1.ShowHeader = true;
            LpMeasureItem1.ShowHeaderInfo = true;
            LpMeasureItem1.ShowIndicator = false;
            LpMeasureItem1.Size = new System.Drawing.Size(186, 42);
            LpMeasureItem1.TabIndex = 1;
            LpMeasureItem1.Text = "ScopeXListPage2";
            LpMeasureItem1.ValueFont = new System.Drawing.Font("Arial", 10.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            LpMeasureItem1.ValueForeColor = System.Drawing.Color.White;
            LpMeasureItem1.ValueMember = null;
            LpMeasureItem1.Visible = false;
            // 
            // BtnLog
            // 
            BtnMeasureTool.BackColor = System.Drawing.Color.FromArgb(33, 33, 40);
            BtnMeasureTool.BorderColor = System.Drawing.Color.Empty;
            BtnMeasureTool.BorderThickness = 0;
            BtnMeasureTool.CornerRadius = 0;
            BtnMeasureTool.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnMeasureTool.DaskArray = null;
            BtnMeasureTool.DropKey = System.Windows.Forms.Keys.Space;
            BtnMeasureTool.ForeColor = System.Drawing.Color.Empty;
            BtnMeasureTool.Height = 45;
            BtnMeasureTool.IconOffset = 5;
            BtnMeasureTool.IconSize = new System.Drawing.Size(40, 40);
            BtnMeasureTool.IndicatorColor = System.Drawing.Color.FromArgb(40, 71, 193);
            BtnMeasureTool.IsIndicatorShow = false;
            BtnMeasureTool.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnMeasureTool.Location = new System.Drawing.Point(0, 0);
            BtnMeasureTool.Margin = new System.Windows.Forms.Padding(0);
            BtnMeasureTool.MinimumSize = new System.Drawing.Size(40, 40);
            BtnMeasureTool.MouseinBackColor = System.Drawing.Color.Transparent;
            BtnMeasureTool.MouseinBorderColor = System.Drawing.Color.Blue;
            BtnMeasureTool.MouseInBorderThickness = 0;
            BtnMeasureTool.MouseinForeColor = System.Drawing.Color.Blue;
            BtnMeasureTool.MouseinSvgForeColor = System.Drawing.Color.Blue;
            BtnMeasureTool.Name = "BtnLog";
            BtnMeasureTool.PressedBackColor = System.Drawing.Color.Gray;
            BtnMeasureTool.PressedBorderColor = System.Drawing.Color.Blue;
            BtnMeasureTool.PressedBorderThickness = 0;
            BtnMeasureTool.PressedForeColor = System.Drawing.Color.Blue;
            BtnMeasureTool.PressedSvgForeColor = System.Drawing.Color.Blue;
            BtnMeasureTool.Size = new System.Drawing.Size(50, 45);
            BtnMeasureTool.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnMeasureTool.StylizeFlag = false;
            BtnMeasureTool.SVGForeColor = System.Drawing.Color.Black;
            BtnMeasureTool.SVGPath = "";
            BtnMeasureTool.TabIndex = 20;
            BtnMeasureTool.TabIndex = 20;
            BtnMeasureTool.Dock = System.Windows.Forms.DockStyle.Fill;
            BtnMeasureTool.Tag = ScopeX.Controls.Language.LanguageManger.Instance.GetIDMessage("YingYong");
            BtnMeasureTool.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            BtnMeasureTool.Click += BtnMeasureTool_Click;
            // 
            // TmUpdate
            // 
            TmUpdate.Interval = 500;
            TmUpdate.Elapsed += TmUpdate_Tick;
            // 
            // DsoResultStrip
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(33, 33, 40);
            Controls.Add(TlpBody);
            DoubleBuffered = true;
            Margin = new System.Windows.Forms.Padding(4);
            Name = "DsoResultStrip";
            Size = new System.Drawing.Size(2469, 49);
            TlpBody.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel TlpBody;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem3;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem4;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem5;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem6;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem7;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem8;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem9;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem10;
        private System.Timers.Timer TmUpdate;
        private ScopeX.UserControls.ScopeXListPage LpCymometerItem;
        private ScopeX.UserControls.ScopeXListPage LpVoltmeterItem;
        private ScopeX.UserControls.ScopeXIconButton BtnAddMeasure;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem2;
        private ScopeX.UserControls.ScopeXListPage LpMeasureItem1;
        private ScopeX.UserControls.ScopeXIconButton BtnMeasureTool;
    }
}
