
using System.Drawing;

namespace ScopeX.U2
{
    partial class DsoTopStrip
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要修改
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            TlpBody = new System.Windows.Forms.TableLayoutPanel();
            BtnApps = new ScopeX.UserControls.ScopeXIconButton();
            BtnTriggerState = new ScopeX.UserControls.ScopeXIconButton();
            CBTriggerMode = new ScopeX.UserControls.ScopeXIconButton();
            BtnAutoset = new ScopeX.UserControls.ScopeXIconButton();
            SiTimebase = new StickyInfo();
            SiTrigger = new StickyInfo();
            BtnLog = new ScopeX.UserControls.ScopeXIconButton();
            BtnSetting = new ScopeX.UserControls.ScopeXIconButton();
            BtnClear = new ScopeX.UserControls.ScopeXIconButton();
            BtnScreenShot = new ScopeX.UserControls.ScopeXIconButton();
            BtnFile = new ScopeX.UserControls.ScopeXIconButton();
            BtnPrinter = new ScopeX.UserControls.ScopeXIconButton();
            BtnCursor = new ScopeX.UserControls.ScopeXIconButton();
            BtnFft = new ScopeX.UserControls.ScopeXIconButton();
            BtnSearch = new ScopeX.UserControls.ScopeXIconButton();
            SiAcquisition = new StickyInfo();
            BtnFastReq = new ScopeX.UserControls.ScopeXIconButton();
            TlpBody.SuspendLayout();
            SuspendLayout();
            // 
            // TlpBody
            // 
            TlpBody.ColumnCount = 22;
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 425F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 1F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            TlpBody.Controls.Add(BtnApps, 21, 0);
            TlpBody.Controls.Add(BtnTriggerState, 1, 0);
            TlpBody.Controls.Add(CBTriggerMode, 2, 0);
            TlpBody.Controls.Add(BtnAutoset, 3, 0);
            TlpBody.Controls.Add(SiTimebase, 4, 0);
            TlpBody.Controls.Add(SiTrigger, 6, 0);
            TlpBody.Controls.Add(BtnLog, 0, 0);
            TlpBody.Controls.Add(BtnSetting, 20, 0);
            TlpBody.Controls.Add(BtnClear, 19, 0);
            TlpBody.Controls.Add(BtnScreenShot, 17, 0);
            TlpBody.Controls.Add(BtnFile, 16, 0);
            TlpBody.Controls.Add(BtnPrinter, 15, 0);
            TlpBody.Controls.Add(BtnCursor, 15, 0);
            TlpBody.Controls.Add(BtnSearch, 9, 0);
            TlpBody.Controls.Add(SiAcquisition, 5, 0);
            TlpBody.Controls.Add(BtnFft, 10, 0);
            TlpBody.Dock = System.Windows.Forms.DockStyle.Fill;
            TlpBody.GrowStyle = System.Windows.Forms.TableLayoutPanelGrowStyle.FixedSize;
            TlpBody.Location = new Point(0, 0);
            TlpBody.Margin = new System.Windows.Forms.Padding(0);
            TlpBody.Name = "TlpBody";
            TlpBody.RowCount = 1;
            TlpBody.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            TlpBody.Size = new Size(1920, 40);
            TlpBody.TabIndex = 0;
            // 
            // BtnApps
            // 
            BtnApps.Adjustable = false;
            BtnApps.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnApps.BackColor = Color.Transparent;
            BtnApps.BorderColor = Color.Black;
            BtnApps.BorderThickness = 0;
            BtnApps.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnApps.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnApps.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnApps.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnApps.CornerRadius = 0;
            BtnApps.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnApps.DaskArray = null;
            BtnApps.DoubleClickEnable = true;
            BtnApps.DropKey = System.Windows.Forms.Keys.Space;
            BtnApps.FineEnable = true;
            BtnApps.FocusedBorderColor = Color.DeepSkyBlue;
            BtnApps.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnApps.ForeColor = SystemColors.ActiveCaptionText;
            BtnApps.Height = 38;
            BtnApps.Icon = Properties.Resources.Begin;
            BtnApps.IconOffset = 11;
            BtnApps.IconSize = new Size(30, 30);
            BtnApps.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnApps.IsChoosed = false;
            BtnApps.IsIndicatorShow = false;
            BtnApps.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnApps.Location = new Point(1862, 1);
            BtnApps.Margin = new System.Windows.Forms.Padding(0);
            BtnApps.MinimumSize = new Size(46, 30);
            BtnApps.MouseinBackColor = Color.Transparent;
            BtnApps.MouseinBorderColor = Color.Blue;
            BtnApps.MouseInBorderThickness = 0;
            BtnApps.MouseinForeColor = Color.Blue;
            BtnApps.MouseinSvgForeColor = Color.Blue;
            BtnApps.Name = "BtnApps";
            BtnApps.PressedBackColor = Color.Gray;
            BtnApps.PressedBorderColor = Color.Blue;
            BtnApps.PressedBorderThickness = 0;
            BtnApps.PressedForeColor = Color.Blue;
            BtnApps.PressedSvgForeColor = Color.Blue;
            BtnApps.Size = new Size(58, 38);
            BtnApps.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnApps.StylizeFlag = false;
            BtnApps.SVGForeColor = Color.Black;
            BtnApps.SVGPath = "";
            BtnApps.TabIndex = 41;
            BtnApps.Tag = "";
            BtnApps.TextAlign = ContentAlignment.MiddleCenter;
            BtnApps.Paint += IconBtn_Paint;
            BtnApps.MouseClick += BtnApps_MouseClick;
            BtnApps.MouseDown += Trigger_MouseDown;
            BtnApps.MouseUp += Trigger_MouseUp;
            // 
            // BtnTriggerState
            // 
            BtnTriggerState.Adjustable = false;
            BtnTriggerState.BackColor = Color.Transparent;
            BtnTriggerState.BorderColor = Color.FromArgb(33, 33, 40);
            BtnTriggerState.BorderThickness = 0;
            BtnTriggerState.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnTriggerState.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnTriggerState.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnTriggerState.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnTriggerState.CornerRadius = 0;
            BtnTriggerState.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnTriggerState.DaskArray = null;
            BtnTriggerState.Dock = System.Windows.Forms.DockStyle.Fill;
            BtnTriggerState.DoubleClickEnable = true;
            BtnTriggerState.DropKey = System.Windows.Forms.Keys.Space;
            BtnTriggerState.FineEnable = true;
            BtnTriggerState.FocusedBorderColor = Color.DeepSkyBlue;
            BtnTriggerState.Font = new Font("Arial", 12F, FontStyle.Bold, GraphicsUnit.Point);
            BtnTriggerState.ForeColor = SystemColors.ActiveCaptionText;
            BtnTriggerState.Height = 40;
            BtnTriggerState.Icon = null;
            BtnTriggerState.IconOffset = 10;
            BtnTriggerState.IconSize = new Size(24, 24);
            BtnTriggerState.IndicatorColor = Color.FromArgb(40, 71, 193);
            BtnTriggerState.IsChoosed = false;
            BtnTriggerState.IsIndicatorShow = false;
            BtnTriggerState.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnTriggerState.Location = new Point(112, 0);
            BtnTriggerState.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            BtnTriggerState.MouseinBackColor = Color.Transparent;
            BtnTriggerState.MouseinBorderColor = Color.Blue;
            BtnTriggerState.MouseInBorderThickness = 0;
            BtnTriggerState.MouseinForeColor = Color.Blue;
            BtnTriggerState.MouseinSvgForeColor = Color.Blue;
            BtnTriggerState.Name = "BtnTriggerState";
            BtnTriggerState.PressedBackColor = SystemColors.ActiveBorder;
            BtnTriggerState.PressedBorderColor = Color.Blue;
            BtnTriggerState.PressedBorderThickness = 0;
            BtnTriggerState.PressedForeColor = Color.White;
            BtnTriggerState.PressedSvgForeColor = Color.Blue;
            BtnTriggerState.Size = new Size(80, 40);
            BtnTriggerState.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnTriggerState.StylizeFlag = false;
            BtnTriggerState.SVGForeColor = Color.Black;
            BtnTriggerState.SVGPath = "";
            BtnTriggerState.TabIndex = 0;
            BtnTriggerState.Text = "Auto";
            BtnTriggerState.TextAlign = ContentAlignment.MiddleCenter;
            BtnTriggerState.Paint += BtnTriggerState_Paint;
            BtnTriggerState.MouseClick += BtnTriggerState_MouseClick;
            BtnTriggerState.MouseDown += Trigger_MouseDown;
            BtnTriggerState.MouseUp += Trigger_MouseUp;
            // 
            // CBTriggerMode
            // 
            CBTriggerMode.Adjustable = false;
            CBTriggerMode.BackColor = Color.Transparent;
            CBTriggerMode.BorderColor = Color.FromArgb(33, 33, 40);
            CBTriggerMode.BorderThickness = 0;
            CBTriggerMode.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            CBTriggerMode.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            CBTriggerMode.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            CBTriggerMode.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            CBTriggerMode.CornerRadius = 0;
            CBTriggerMode.Cursor = System.Windows.Forms.Cursors.Hand;
            CBTriggerMode.DaskArray = null;
            CBTriggerMode.DoubleClickEnable = true;
            CBTriggerMode.DropKey = System.Windows.Forms.Keys.Space;
            CBTriggerMode.FineEnable = true;
            CBTriggerMode.FocusedBorderColor = Color.DeepSkyBlue;
            CBTriggerMode.Font = new Font("Arial", 12F, FontStyle.Bold, GraphicsUnit.Point);
            CBTriggerMode.ForeColor = SystemColors.ActiveCaptionText;
            CBTriggerMode.Height = 40;
            CBTriggerMode.Icon = null;
            CBTriggerMode.IconOffset = 5;
            CBTriggerMode.IconSize = new Size(51, 17);
            CBTriggerMode.IndicatorColor = Color.FromArgb(40, 71, 193);
            CBTriggerMode.IsChoosed = false;
            CBTriggerMode.IsIndicatorShow = false;
            CBTriggerMode.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            CBTriggerMode.Location = new Point(196, 0);
            CBTriggerMode.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            CBTriggerMode.MouseinBackColor = Color.FromArgb(35, 62, 169);
            CBTriggerMode.MouseinBorderColor = Color.Blue;
            CBTriggerMode.MouseInBorderThickness = 0;
            CBTriggerMode.MouseinForeColor = Color.White;
            CBTriggerMode.MouseinSvgForeColor = Color.Blue;
            CBTriggerMode.Name = "CBTriggerMode";
            CBTriggerMode.PressedBackColor = SystemColors.ActiveBorder;
            CBTriggerMode.PressedBorderColor = Color.Blue;
            CBTriggerMode.PressedBorderThickness = 0;
            CBTriggerMode.PressedForeColor = Color.White;
            CBTriggerMode.PressedSvgForeColor = Color.Blue;
            CBTriggerMode.Size = new Size(80, 40);
            CBTriggerMode.StyleFlags = UserControls.Style.StyleFlag.None;
            CBTriggerMode.StylizeFlag = false;
            CBTriggerMode.SVGForeColor = Color.Black;
            CBTriggerMode.SVGPath = "";
            CBTriggerMode.TabIndex = 2;
            CBTriggerMode.Text = "Single";
            CBTriggerMode.TextAlign = ContentAlignment.MiddleCenter;
            CBTriggerMode.Paint += CBTriggerMode_Paint;
            CBTriggerMode.MouseClick += CBTriggerMode_MouseClick;
            CBTriggerMode.MouseDown += Trigger_MouseDown;
            CBTriggerMode.MouseUp += Trigger_MouseUp;
            // 
            // BtnAutoset
            // 
            BtnAutoset.Adjustable = false;
            BtnAutoset.BackColor = Color.Transparent;
            BtnAutoset.BorderColor = Color.FromArgb(33, 33, 40);
            BtnAutoset.BorderThickness = 0;
            BtnAutoset.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnAutoset.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnAutoset.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnAutoset.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnAutoset.CornerRadius = 0;
            BtnAutoset.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnAutoset.DaskArray = null;
            BtnAutoset.DoubleClickEnable = true;
            BtnAutoset.DropKey = System.Windows.Forms.Keys.Space;
            BtnAutoset.FineEnable = true;
            BtnAutoset.FocusedBorderColor = Color.DeepSkyBlue;
            BtnAutoset.Font = new Font("Arial", 12F, FontStyle.Bold, GraphicsUnit.Point);
            BtnAutoset.ForeColor = SystemColors.ActiveCaptionText;
            BtnAutoset.Height = 40;
            BtnAutoset.Icon = null;
            BtnAutoset.IconOffset = 5;
            BtnAutoset.IconSize = new Size(51, 17);
            BtnAutoset.IndicatorColor = Color.FromArgb(40, 71, 193);
            BtnAutoset.IsChoosed = false;
            BtnAutoset.IsIndicatorShow = false;
            BtnAutoset.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnAutoset.Location = new Point(280, 0);
            BtnAutoset.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            BtnAutoset.MouseinBackColor = Color.FromArgb(35, 62, 169);
            BtnAutoset.MouseinBorderColor = Color.Blue;
            BtnAutoset.MouseInBorderThickness = 0;
            BtnAutoset.MouseinForeColor = Color.White;
            BtnAutoset.MouseinSvgForeColor = Color.Blue;
            BtnAutoset.Name = "BtnAutoset";
            BtnAutoset.PressedBackColor = SystemColors.ActiveBorder;
            BtnAutoset.PressedBorderColor = Color.Blue;
            BtnAutoset.PressedBorderThickness = 0;
            BtnAutoset.PressedForeColor = Color.White;
            BtnAutoset.PressedSvgForeColor = Color.Blue;
            BtnAutoset.Size = new Size(80, 40);
            BtnAutoset.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnAutoset.StylizeFlag = false;
            BtnAutoset.SVGForeColor = Color.Black;
            BtnAutoset.SVGPath = "";
            BtnAutoset.TabIndex = 2;
            BtnAutoset.Text = "Autoset";
            BtnAutoset.TextAlign = ContentAlignment.MiddleCenter;
            BtnAutoset.Paint += BtnAutoset_Paint;
            BtnAutoset.MouseClick += BtnAutoset_MouseClick;
            BtnAutoset.MouseDown += Trigger_MouseDown;
            BtnAutoset.MouseUp += Trigger_MouseUp;
            // 
            // SiTimebase
            // 
            SiTimebase.BackColor = Color.FromArgb(41, 42, 45);
            SiTimebase.ContentRowHeight = 32;
            SiTimebase.Dock = System.Windows.Forms.DockStyle.Left;
            SiTimebase.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            SiTimebase.IconWidth = 32;
            SiTimebase.IndicatorColor = Color.FromArgb(40, 71, 193);
            SiTimebase.IsIndicatorShow = false;
            SiTimebase.IsStickyBackColorChanged = false;
            SiTimebase.Location = new Point(364, 0);
            SiTimebase.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            SiTimebase.Name = "SiTimebase";
            SiTimebase.Padding = new System.Windows.Forms.Padding(1);
            SiTimebase.Size = new Size(189, 40);
            SiTimebase.StickyBackColor = Color.FromArgb(41, 42, 45);
            SiTimebase.StickyContentBackColor = Color.FromArgb(41, 42, 45);
            SiTimebase.StickyForeColor = Color.White;
            SiTimebase.StickyTitle = "H";
            SiTimebase.TabIndex = 3;
            SiTimebase.Tag = "";
            SiTimebase.MouseClick += SiTimebase_MouseClick;
            // 
            // SiTrigger
            //
            SiTrigger.BackColor = Color.FromArgb(41, 42, 45);
            SiTrigger.ContentRowHeight = 32;
            SiTrigger.Dock = System.Windows.Forms.DockStyle.Left;
            SiTrigger.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            SiTrigger.IconWidth = 32;
            SiTrigger.IndicatorColor = Color.FromArgb(40, 71, 193);
            SiTrigger.IsIndicatorShow = false;
            SiTrigger.IsStickyBackColorChanged = false;
            SiTrigger.Location = new Point(1041, 0);
            SiTrigger.Margin = new System.Windows.Forms.Padding(2, 0, 3, 0);
            SiTrigger.Name = "SiTrigger";
            SiTrigger.Padding = new System.Windows.Forms.Padding(1);
            SiTrigger.Size = new Size(225, 40);
            SiTrigger.StickyBackColor = Color.FromArgb(41, 42, 45);
            SiTrigger.StickyContentBackColor = Color.FromArgb(41, 42, 45);
            SiTrigger.StickyForeColor = Color.White;
            SiTrigger.StickyTitle = "T";
            SiTrigger.TabIndex = 40;
            SiTrigger.Tag = "Trigger";
            SiTrigger.MouseClick += SiTrigger_MouseClick;
            // 
            // BtnLog
            // 
            BtnLog.Adjustable = false;
            BtnLog.BackColor = Color.Transparent;
            BtnLog.BorderColor = Color.Empty;
            BtnLog.BorderThickness = 0;
            BtnLog.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnLog.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnLog.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnLog.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnLog.CornerRadius = 0;
            BtnLog.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnLog.DaskArray = null;
            BtnLog.DoubleClickEnable = true;
            BtnLog.DropKey = System.Windows.Forms.Keys.Space;
            BtnLog.FineEnable = true;
            BtnLog.FocusedBorderColor = Color.DeepSkyBlue;
            BtnLog.ForeColor = SystemColors.ActiveCaptionText;
            BtnLog.Height = 40;
            BtnLog.Icon = null;
            BtnLog.IconOffset = 1;
            BtnLog.IconSize = new Size(80, 15);
            BtnLog.IndicatorColor = Color.FromArgb(40, 71, 193);
            BtnLog.IsChoosed = false;
            BtnLog.IsIndicatorShow = false;
            BtnLog.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnLog.Location = new Point(0, 0);
            BtnLog.Margin = new System.Windows.Forms.Padding(0);
            BtnLog.MinimumSize = new Size(70, 40);
            BtnLog.MouseinBackColor = Color.Transparent;
            BtnLog.MouseinBorderColor = Color.Blue;
            BtnLog.MouseInBorderThickness = 0;
            BtnLog.MouseinForeColor = Color.Blue;
            BtnLog.MouseinSvgForeColor = Color.Blue;
            BtnLog.Name = "BtnLog";
            BtnLog.PressedBackColor = Color.Gray;
            BtnLog.PressedBorderColor = Color.Blue;
            BtnLog.PressedBorderThickness = 0;
            BtnLog.PressedForeColor = Color.Blue;
            BtnLog.PressedSvgForeColor = Color.Blue;
            BtnLog.Size = new Size(110, 40);
            BtnLog.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnLog.StylizeFlag = false;
            BtnLog.SVGForeColor = Color.Black;
            BtnLog.SVGPath = "";
            BtnLog.TabIndex = 20;
            BtnLog.TextAlign = ContentAlignment.MiddleCenter;
            BtnLog.Paint += BtnLog_Paint;
            // 
            // BtnSetting
            // 
            BtnSetting.Adjustable = false;
            BtnSetting.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnSetting.BackColor = Color.Transparent;
            BtnSetting.BorderColor = Color.Transparent;
            BtnSetting.BorderThickness = 0;
            BtnSetting.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnSetting.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnSetting.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnSetting.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnSetting.CornerRadius = 0;
            BtnSetting.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnSetting.DaskArray = null;
            BtnSetting.DoubleClickEnable = true;
            BtnSetting.DropKey = System.Windows.Forms.Keys.Space;
            BtnSetting.FineEnable = true;
            BtnSetting.FocusedBorderColor = Color.DeepSkyBlue;
            BtnSetting.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnSetting.ForeColor = SystemColors.ActiveCaptionText;
            BtnSetting.Height = 38;
            BtnSetting.Icon = Properties.Resources.Setting;
            BtnSetting.IconOffset = 11;
            BtnSetting.IconSize = new Size(30, 30);
            BtnSetting.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnSetting.IsChoosed = false;
            BtnSetting.IsIndicatorShow = false;
            BtnSetting.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnSetting.Location = new Point(1804, 1);
            BtnSetting.Margin = new System.Windows.Forms.Padding(0);
            BtnSetting.MinimumSize = new Size(46, 30);
            BtnSetting.MouseinBackColor = Color.Transparent;
            BtnSetting.MouseinBorderColor = Color.Blue;
            BtnSetting.MouseInBorderThickness = 0;
            BtnSetting.MouseinForeColor = Color.Blue;
            BtnSetting.MouseinSvgForeColor = Color.Blue;
            BtnSetting.Name = "BtnSetting";
            BtnSetting.PressedBackColor = Color.Gray;
            BtnSetting.PressedBorderColor = Color.Blue;
            BtnSetting.PressedBorderThickness = 0;
            BtnSetting.PressedForeColor = Color.Blue;
            BtnSetting.PressedSvgForeColor = Color.Blue;
            BtnSetting.Size = new Size(58, 38);
            BtnSetting.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnSetting.StylizeFlag = false;
            BtnSetting.SVGForeColor = Color.Black;
            BtnSetting.SVGPath = "";
            BtnSetting.TabIndex = 19;
            BtnSetting.Tag = "";
            BtnSetting.TextAlign = ContentAlignment.MiddleCenter;
            BtnSetting.Paint += IconBtn_Paint;
            BtnSetting.MouseClick += BtnSetting_MouseClick;
            BtnSetting.MouseDown += Trigger_MouseDown;
            BtnSetting.MouseUp += Trigger_MouseUp;
            // 
            // BtnClear
            // 
            BtnClear.Adjustable = false;
            BtnClear.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnClear.BackColor = Color.Transparent;
            BtnClear.BorderColor = Color.Transparent;
            BtnClear.BorderThickness = 0;
            BtnClear.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnClear.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnClear.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnClear.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnClear.CornerRadius = 0;
            BtnClear.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnClear.DaskArray = null;
            BtnClear.DoubleClickEnable = true;
            BtnClear.DropKey = System.Windows.Forms.Keys.Space;
            BtnClear.FineEnable = true;
            BtnClear.FocusedBorderColor = Color.DeepSkyBlue;
            BtnClear.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnClear.ForeColor = SystemColors.ActiveCaptionText;
            BtnClear.Height = 38;
            BtnClear.Icon = Properties.Resources.Clear;
            BtnClear.IconOffset = 11;
            BtnClear.IconSize = new Size(30, 30);
            BtnClear.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnClear.IsChoosed = false;
            BtnClear.IsIndicatorShow = false;
            BtnClear.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnClear.Location = new Point(1746, 1);
            BtnClear.Margin = new System.Windows.Forms.Padding(0);
            BtnClear.MinimumSize = new Size(46, 30);
            BtnClear.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnClear.MouseinBorderColor = Color.Blue;
            BtnClear.MouseInBorderThickness = 0;
            BtnClear.MouseinForeColor = Color.White;
            BtnClear.MouseinSvgForeColor = Color.Blue;
            BtnClear.Name = "BtnClear";
            BtnClear.PressedBackColor = SystemColors.ActiveBorder;
            BtnClear.PressedBorderColor = Color.Blue;
            BtnClear.PressedBorderThickness = 0;
            BtnClear.PressedForeColor = Color.White;
            BtnClear.PressedSvgForeColor = Color.Blue;
            BtnClear.Size = new Size(58, 38);
            BtnClear.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnClear.StylizeFlag = false;
            BtnClear.SVGForeColor = Color.Black;
            BtnClear.SVGPath = "";
            BtnClear.TabIndex = 18;
            BtnClear.TextAlign = ContentAlignment.MiddleCenter;
            BtnClear.Paint += IconBtn_Paint;
            BtnClear.MouseClick += BtnClear_MouseClick;
            BtnClear.MouseDown += Trigger_MouseDown;
            BtnClear.MouseUp += Trigger_MouseUp;
            // 
            // BtnScreenShot
            // 
            BtnScreenShot.Adjustable = false;
            BtnScreenShot.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnScreenShot.BackColor = Color.Transparent;
            BtnScreenShot.BorderColor = Color.Transparent;
            BtnScreenShot.BorderThickness = 0;
            BtnScreenShot.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnScreenShot.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnScreenShot.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnScreenShot.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnScreenShot.CornerRadius = 0;
            BtnScreenShot.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnScreenShot.DaskArray = null;
            BtnScreenShot.DoubleClickEnable = true;
            BtnScreenShot.DropKey = System.Windows.Forms.Keys.Space;
            BtnScreenShot.FineEnable = true;
            BtnScreenShot.FocusedBorderColor = Color.DeepSkyBlue;
            BtnScreenShot.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnScreenShot.ForeColor = SystemColors.ActiveCaptionText;
            BtnScreenShot.Height = 38;
            BtnScreenShot.Icon = Properties.Resources.ScreenShot;
            BtnScreenShot.IconOffset = 11;
            BtnScreenShot.IconSize = new Size(30, 30);
            BtnScreenShot.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnScreenShot.IsChoosed = false;
            BtnScreenShot.IsIndicatorShow = false;
            BtnScreenShot.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnScreenShot.Location = new Point(1688, 1);
            BtnScreenShot.Margin = new System.Windows.Forms.Padding(0);
            BtnScreenShot.MinimumSize = new Size(46, 30);
            BtnScreenShot.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnScreenShot.MouseinBorderColor = Color.Blue;
            BtnScreenShot.MouseInBorderThickness = 0;
            BtnScreenShot.MouseinForeColor = Color.White;
            BtnScreenShot.MouseinSvgForeColor = Color.Blue;
            BtnScreenShot.Name = "BtnScreenShot";
            BtnScreenShot.PressedBackColor = SystemColors.ActiveBorder;
            BtnScreenShot.PressedBorderColor = Color.Blue;
            BtnScreenShot.PressedBorderThickness = 0;
            BtnScreenShot.PressedForeColor = Color.White;
            BtnScreenShot.PressedSvgForeColor = Color.Blue;
            BtnScreenShot.Size = new Size(58, 38);
            BtnScreenShot.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnScreenShot.StylizeFlag = false;
            BtnScreenShot.SVGForeColor = Color.Black;
            BtnScreenShot.SVGPath = "";
            BtnScreenShot.TabIndex = 17;
            BtnScreenShot.TextAlign = ContentAlignment.MiddleCenter;
            BtnScreenShot.Paint += IconBtn_Paint;
            BtnScreenShot.MouseClick += BtnScreenShot_MouseClick;
            BtnScreenShot.MouseDown += Trigger_MouseDown;
            BtnScreenShot.MouseUp += Trigger_MouseUp;
            // 
            // BtnFile
            // 
            BtnFile.Adjustable = false;
            BtnFile.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnFile.BackColor = Color.Transparent;
            BtnFile.BorderColor = Color.Transparent;
            BtnFile.BorderThickness = 0;
            BtnFile.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnFile.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnFile.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnFile.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnFile.CornerRadius = 0;
            BtnFile.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnFile.DaskArray = null;
            BtnFile.DoubleClickEnable = true;
            BtnFile.DropKey = System.Windows.Forms.Keys.Space;
            BtnFile.FineEnable = true;
            BtnFile.FocusedBorderColor = Color.DeepSkyBlue;
            BtnFile.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnFile.ForeColor = SystemColors.ActiveCaptionText;
            BtnFile.Height = 38;
            BtnFile.Icon = Properties.Resources.Save;
            BtnFile.IconOffset = 11;
            BtnFile.IconSize = new Size(30, 30);
            BtnFile.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnFile.IsChoosed = false;
            BtnFile.IsIndicatorShow = false;
            BtnFile.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnFile.Location = new Point(1630, 1);
            BtnFile.Margin = new System.Windows.Forms.Padding(0);
            BtnFile.MinimumSize = new Size(46, 30);
            BtnFile.MouseinBackColor = Color.Transparent;
            BtnFile.MouseinBorderColor = Color.Blue;
            BtnFile.MouseInBorderThickness = 0;
            BtnFile.MouseinForeColor = Color.Blue;
            BtnFile.MouseinSvgForeColor = Color.Blue;
            BtnFile.Name = "BtnFile";
            BtnFile.PressedBackColor = Color.Gray;
            BtnFile.PressedBorderColor = Color.Blue;
            BtnFile.PressedBorderThickness = 0;
            BtnFile.PressedForeColor = Color.Blue;
            BtnFile.PressedSvgForeColor = Color.Blue;
            BtnFile.Size = new Size(58, 38);
            BtnFile.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnFile.StylizeFlag = false;
            BtnFile.SVGForeColor = Color.Black;
            BtnFile.SVGPath = "";
            BtnFile.TabIndex = 16;
            BtnFile.Tag = "";
            BtnFile.TextAlign = ContentAlignment.MiddleCenter;
            BtnFile.Paint += IconBtn_Paint;
            BtnFile.MouseClick += BtnFile_MouseClick;
            BtnFile.MouseDown += Trigger_MouseDown;
            BtnFile.MouseUp += Trigger_MouseUp;
            // 
            // BtnPrinter
            // 
            BtnPrinter.Adjustable = false;
            BtnPrinter.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnPrinter.BackColor = Color.Transparent;
            BtnPrinter.BorderColor = Color.Transparent;
            BtnPrinter.BorderThickness = 0;
            BtnPrinter.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnPrinter.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnPrinter.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnPrinter.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnPrinter.CornerRadius = 0;
            BtnPrinter.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnPrinter.DaskArray = null;
            BtnPrinter.DoubleClickEnable = true;
            BtnPrinter.DropKey = System.Windows.Forms.Keys.Space;
            BtnPrinter.FineEnable = true;
            BtnPrinter.FocusedBorderColor = Color.DeepSkyBlue;
            BtnPrinter.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnPrinter.ForeColor = SystemColors.ActiveCaptionText;
            BtnPrinter.Height = 38;
            BtnPrinter.Icon = Properties.Resources.Printer;
            BtnPrinter.IconOffset = 11;
            BtnPrinter.IconSize = new Size(30, 30);
            BtnPrinter.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnPrinter.IsChoosed = false;
            BtnPrinter.IsIndicatorShow = false;
            BtnPrinter.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnPrinter.Location = new Point(1572, 1);
            BtnPrinter.Margin = new System.Windows.Forms.Padding(0);
            BtnPrinter.MinimumSize = new Size(46, 30);
            BtnPrinter.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnPrinter.MouseinBorderColor = Color.Blue;
            BtnPrinter.MouseInBorderThickness = 0;
            BtnPrinter.MouseinForeColor = Color.White;
            BtnPrinter.MouseinSvgForeColor = Color.Blue;
            BtnPrinter.Name = "BtnPrinter";
            BtnPrinter.PressedBackColor = SystemColors.ActiveBorder;
            BtnPrinter.PressedBorderColor = Color.Blue;
            BtnPrinter.PressedBorderThickness = 0;
            BtnPrinter.PressedForeColor = Color.White;
            BtnPrinter.PressedSvgForeColor = Color.Blue;
            BtnPrinter.Size = new Size(58, 38);
            BtnPrinter.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnPrinter.StylizeFlag = false;
            BtnPrinter.SVGForeColor = Color.Black;
            BtnPrinter.SVGPath = "";
            BtnPrinter.TabIndex = 38;
            BtnPrinter.Tag = "";
            BtnPrinter.TextAlign = ContentAlignment.MiddleCenter;
            BtnPrinter.Visible = false;
            BtnPrinter.Click += BtnPrinter_Click;
            BtnPrinter.Paint += IconBtn_Paint;
            BtnPrinter.MouseClick += BtnPrinter_MouseClick;
            BtnPrinter.MouseDown += Trigger_MouseDown;
            BtnPrinter.MouseUp += Trigger_MouseUp;
            // 
            // BtnCursor
            // 
            BtnCursor.Adjustable = false;
            BtnCursor.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnCursor.BackColor = Color.Transparent;
            BtnCursor.BorderColor = Color.Transparent;
            BtnCursor.BorderThickness = 0;
            BtnCursor.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnCursor.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnCursor.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnCursor.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnCursor.CornerRadius = 0;
            BtnCursor.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnCursor.DaskArray = null;
            BtnCursor.DoubleClickEnable = true;
            BtnCursor.DropKey = System.Windows.Forms.Keys.Space;
            BtnCursor.FineEnable = true;
            BtnCursor.FocusedBorderColor = Color.DeepSkyBlue;
            BtnCursor.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnCursor.ForeColor = SystemColors.ActiveCaptionText;
            BtnCursor.Height = 32;
            BtnCursor.Icon = Properties.Resources.Cursor;
            BtnCursor.IconOffset = 11;
            BtnCursor.IconSize = new Size(30, 30);
            BtnCursor.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnCursor.IsChoosed = false;
            BtnCursor.IsIndicatorShow = false;
            BtnCursor.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnCursor.Location = new Point(1514, 4);
            BtnCursor.Margin = new System.Windows.Forms.Padding(0);
            BtnCursor.MinimumSize = new Size(46, 30);
            BtnCursor.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnCursor.MouseinBorderColor = Color.Blue;
            BtnCursor.MouseInBorderThickness = 0;
            BtnCursor.MouseinForeColor = Color.White;
            BtnCursor.MouseinSvgForeColor = Color.Blue;
            BtnCursor.Name = "BtnCursor";
            BtnCursor.PressedBackColor = SystemColors.ActiveBorder;
            BtnCursor.PressedBorderColor = Color.Blue;
            BtnCursor.PressedBorderThickness = 0;
            BtnCursor.PressedForeColor = Color.White;
            BtnCursor.PressedSvgForeColor = Color.Blue;
            BtnCursor.Size = new Size(58, 32);
            BtnCursor.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnCursor.StylizeFlag = false;
            BtnCursor.SVGForeColor = Color.Black;
            BtnCursor.SVGPath = "";
            BtnCursor.TabIndex = 12;
            BtnCursor.Tag = "";
            BtnCursor.TextAlign = ContentAlignment.MiddleCenter;
            BtnCursor.Paint += IconBtn_Paint;
            BtnCursor.MouseClick += BtnCursor_MouseClick;
            BtnCursor.MouseDown += Trigger_MouseDown;
            BtnCursor.MouseUp += Trigger_MouseUp;
            // 
            // BtnFft
            // 
            BtnFft.Adjustable = false;
            BtnFft.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnFft.BackColor = Color.Transparent;
            BtnFft.BorderColor = Color.Transparent;
            BtnFft.BorderThickness = 0;
            BtnFft.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnFft.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnFft.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnFft.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnFft.CornerRadius = 0;
            BtnFft.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnFft.DaskArray = null;
            BtnFft.DoubleClickEnable = true;
            BtnFft.DropKey = System.Windows.Forms.Keys.Space;
            BtnFft.FineEnable = true;
            BtnFft.FocusedBorderColor = Color.DeepSkyBlue;
            BtnFft.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnFft.ForeColor = SystemColors.ActiveCaptionText;
            BtnFft.Height = 38;
            BtnFft.Icon = Properties.Resources.Fft;
            BtnFft.IconOffset = 11;
            BtnFft.IconSize = new Size(30, 30);
            BtnFft.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnFft.IsChoosed = false;
            BtnFft.IsIndicatorShow = false;
            BtnFft.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnFft.Location = new Point(1456, 1);
            BtnFft.Margin = new System.Windows.Forms.Padding(0);
            BtnFft.MinimumSize = new Size(46, 30);
            BtnFft.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnFft.MouseinBorderColor = Color.Blue;
            BtnFft.MouseInBorderThickness = 0;
            BtnFft.MouseinForeColor = Color.White;
            BtnFft.MouseinSvgForeColor = Color.Blue;
            BtnFft.Name = "BtnFft";
            BtnFft.PressedBackColor = SystemColors.ActiveBorder;
            BtnFft.PressedBorderColor = Color.Blue;
            BtnFft.PressedBorderThickness = 0;
            BtnFft.PressedForeColor = Color.White;
            BtnFft.PressedSvgForeColor = Color.Blue;
            BtnFft.Size = new Size(58, 38);
            BtnFft.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnFft.StylizeFlag = false;
            BtnFft.SVGForeColor = Color.Black;
            BtnFft.SVGPath = "";
            BtnFft.TabIndex = 13;
            BtnFft.TextAlign = ContentAlignment.MiddleCenter;
            BtnFft.Paint += IconBtn_Paint;
            BtnFft.MouseClick += BtnFft_MouseClick;
            BtnFft.MouseDown += Trigger_MouseDown;
            BtnFft.MouseUp += Trigger_MouseUp;
            // 
            // BtnSearch
            // 
            BtnSearch.Adjustable = false;
            BtnSearch.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnSearch.BackColor = Color.Transparent;
            BtnSearch.BorderColor = Color.Transparent;
            BtnSearch.BorderThickness = 0;
            BtnSearch.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnSearch.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnSearch.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnSearch.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnSearch.CornerRadius = 0;
            BtnSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnSearch.DaskArray = null;
            BtnSearch.DoubleClickEnable = true;
            BtnSearch.DropKey = System.Windows.Forms.Keys.Space;
            BtnSearch.FineEnable = true;
            BtnSearch.FocusedBorderColor = Color.DeepSkyBlue;
            BtnSearch.Font = new Font("Arial", 12F, FontStyle.Bold, GraphicsUnit.Point);
            BtnSearch.ForeColor = SystemColors.ActiveCaptionText;
            BtnSearch.Height = 38;
            BtnSearch.Icon = null;
            BtnSearch.IconOffset = 11;
            BtnSearch.IconSize = new Size(30, 30);
            BtnSearch.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnSearch.IsChoosed = false;
            BtnSearch.IsIndicatorShow = false;
            BtnSearch.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnSearch.Location = new Point(1398, 1);
            BtnSearch.Margin = new System.Windows.Forms.Padding(0);
            BtnSearch.MinimumSize = new Size(46, 30);
            BtnSearch.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnSearch.MouseinBorderColor = Color.Blue;
            BtnSearch.MouseInBorderThickness = 0;
            BtnSearch.MouseinForeColor = Color.White;
            BtnSearch.MouseinSvgForeColor = Color.Blue;
            BtnSearch.Name = "BtnSearch";
            BtnSearch.PressedBackColor = SystemColors.ActiveBorder;
            BtnSearch.PressedBorderColor = Color.Blue;
            BtnSearch.PressedBorderThickness = 0;
            BtnSearch.PressedForeColor = Color.White;
            BtnSearch.PressedSvgForeColor = Color.Blue;
            BtnSearch.Size = new Size(58, 38);
            BtnSearch.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnSearch.StylizeFlag = false;
            BtnSearch.SVGForeColor = Color.Black;
            BtnSearch.SVGPath = "";
            BtnSearch.TabIndex = 37;
            BtnSearch.Tag = "";
            BtnSearch.Text = "AiSet";
            BtnSearch.TextAlign = ContentAlignment.MiddleCenter;
            BtnSearch.MouseClick += BtnAiSet_MouseClick;
            // 
            // SiAcquisition
            // 
            SiAcquisition.BackColor = Color.FromArgb(41, 42, 45);
            SiAcquisition.ContentRowHeight = 32;
            SiAcquisition.Dock = System.Windows.Forms.DockStyle.Left;
            SiAcquisition.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            SiAcquisition.IconWidth = 32;
            SiAcquisition.IndicatorColor = Color.FromArgb(40, 71, 193);
            SiAcquisition.IsIndicatorShow = false;
            SiAcquisition.IsStickyBackColorChanged = false;
            SiAcquisition.Location = new Point(627, 0);
            SiAcquisition.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            SiAcquisition.Name = "SiAcquisition";
            SiAcquisition.Padding = new System.Windows.Forms.Padding(1);
            SiAcquisition.Size = new Size(284, 40);
            SiAcquisition.StickyBackColor = Color.FromArgb(41, 42, 45);
            SiAcquisition.StickyContentBackColor = Color.FromArgb(41, 42, 45);
            SiAcquisition.StickyForeColor = Color.White;
            SiAcquisition.StickyTitle = "A";
            SiAcquisition.TabIndex = 4;
            SiAcquisition.Tag = "";
            SiAcquisition.MouseClick += SiAcquisition_MouseClick;
            // 
            // BtnFastReq
            // 
            BtnFastReq.Adjustable = false;
            BtnFastReq.Anchor = System.Windows.Forms.AnchorStyles.Left;
            BtnFastReq.BackColor = Color.Transparent;
            BtnFastReq.BorderColor = Color.Transparent;
            BtnFastReq.BorderThickness = 0;
            BtnFastReq.ChoosedBackColor = Color.FromArgb(40, 71, 193);
            BtnFastReq.ChoosedForeColor = Color.FromArgb(192, 192, 192);
            BtnFastReq.ChoosedMouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnFastReq.ChoosedPressedBackColor = Color.FromArgb(40, 71, 193);
            BtnFastReq.CornerRadius = 0;
            BtnFastReq.Cursor = System.Windows.Forms.Cursors.Hand;
            BtnFastReq.DaskArray = null;
            BtnFastReq.DoubleClickEnable = true;
            BtnFastReq.DropKey = System.Windows.Forms.Keys.Space;
            BtnFastReq.FineEnable = true;
            BtnFastReq.FocusedBorderColor = Color.DeepSkyBlue;
            BtnFastReq.Font = new Font("Arial", 9.75F, FontStyle.Regular, GraphicsUnit.Point);
            BtnFastReq.ForeColor = SystemColors.ActiveCaptionText;
            BtnFastReq.Height = 38;
            BtnFastReq.Icon = Properties.Resources.UltraAcq;
            BtnFastReq.IconOffset = 11;
            BtnFastReq.IconSize = new Size(30, 30);
            BtnFastReq.IndicatorColor = Color.FromArgb(0, 171, 209);
            BtnFastReq.IsChoosed = false;
            BtnFastReq.IsIndicatorShow = false;
            BtnFastReq.LanguagePattern = ScopeX.Controls.LanguageDefinition.LanguagePattern.Default;
            BtnFastReq.Location = new Point(1456, 1);
            BtnFastReq.Margin = new System.Windows.Forms.Padding(0);
            BtnFastReq.MinimumSize = new Size(46, 30);
            BtnFastReq.MouseinBackColor = Color.FromArgb(40, 71, 193);
            BtnFastReq.MouseinBorderColor = Color.Blue;
            BtnFastReq.MouseInBorderThickness = 0;
            BtnFastReq.MouseinForeColor = Color.White;
            BtnFastReq.MouseinSvgForeColor = Color.Blue;
            BtnFastReq.Name = "BtnFastReq";
            BtnFastReq.PressedBackColor = SystemColors.ActiveBorder;
            BtnFastReq.PressedBorderColor = Color.Blue;
            BtnFastReq.PressedBorderThickness = 0;
            BtnFastReq.PressedForeColor = Color.White;
            BtnFastReq.PressedSvgForeColor = Color.Blue;
            BtnFastReq.Size = new Size(58, 38);
            BtnFastReq.StyleFlags = UserControls.Style.StyleFlag.None;
            BtnFastReq.StylizeFlag = false;
            BtnFastReq.SVGForeColor = Color.Black;
            BtnFastReq.SVGPath = "";
            BtnFastReq.TabIndex = 14;
            BtnFastReq.TextAlign = ContentAlignment.MiddleCenter;
            BtnFastReq.Paint += IconBtn_Paint;
            BtnFastReq.MouseClick += BtnFastReq_MouseClick;
            BtnFastReq.MouseDown += Trigger_MouseDown;
            BtnFastReq.MouseUp += Trigger_MouseUp;
            // 
            // DsoTopStrip
            // 
            AutoScaleDimensions = new SizeF(8F, 16F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = Color.FromArgb(33, 33, 40);
            Controls.Add(TlpBody);
            DoubleBuffered = true;
            Font = new Font("Arial", 10.5F, FontStyle.Regular, GraphicsUnit.Point);
            ForeColor = Color.White;
            Margin = new System.Windows.Forms.Padding(0);
            Name = "DsoTopStrip";
            Size = new Size(1920, 40);
            TlpBody.ResumeLayout(false);
            TlpBody.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel TlpBody;
        private ScopeX.UserControls.ScopeXIconButton BtnAutoset;
        private ScopeX.UserControls.ScopeXIconButton BtnTriggerState;
        private StickyInfo SiAcquisition;
        private StickyInfo SiTimebase;
        private StickyInfo SiTrigger;
        private ScopeX.UserControls.ScopeXIconButton BtnFile;
        private ScopeX.UserControls.ScopeXIconButton CBTriggerMode;
        private ScopeX.UserControls.ScopeXIconButton BtnCursor;
        private ScopeX.UserControls.ScopeXIconButton BtnScreenShot;
        private ScopeX.UserControls.ScopeXIconButton BtnFastReq;
        private ScopeX.UserControls.ScopeXIconButton BtnClear;
        private ScopeX.UserControls.ScopeXIconButton BtnSetting;
        private ScopeX.UserControls.ScopeXIconButton BtnPrinter;
        private ScopeX.UserControls.ScopeXIconButton BtnApps;
        private ScopeX.UserControls.ScopeXIconButton BtnFft;
        private ScopeX.UserControls.ScopeXIconButton BtnLog;
        private ScopeX.UserControls.ScopeXIconButton BtnSearch;
    }
}
