//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopeX.U2.PowerAnalysis
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerAnalysis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerAnalysis() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopeX.U2.PowerAnalysis.PowerAnalysis", typeof(PowerAnalysis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 摆率 的本地化字符串。
        /// </summary>
        internal static string DifferSlewRate {
            get {
                return ResourceManager.GetString("DifferSlewRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流 的本地化字符串。
        /// </summary>
        internal static string EfficiencyCurrent {
            get {
                return ResourceManager.GetString("EfficiencyCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率 的本地化字符串。
        /// </summary>
        internal static string EfficiencyPower {
            get {
                return ResourceManager.GetString("EfficiencyPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压 的本地化字符串。
        /// </summary>
        internal static string EfficiencyVoltage {
            get {
                return ResourceManager.GetString("EfficiencyVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THD-F 的本地化字符串。
        /// </summary>
        internal static string HarmonicTHDF {
            get {
                return ResourceManager.GetString("HarmonicTHDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THD-R 的本地化字符串。
        /// </summary>
        internal static string HarmonicTHDR {
            get {
                return ResourceManager.GetString("HarmonicTHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 均方根 的本地化字符串。
        /// </summary>
        internal static string HarmonicTHDrms {
            get {
                return ResourceManager.GetString("HarmonicTHDrms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 涌入电流 的本地化字符串。
        /// </summary>
        internal static string InrushCurrentPk2Pk {
            get {
                return ResourceManager.GetString("InrushCurrentPk2Pk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 占空比 的本地化字符串。
        /// </summary>
        internal static string ModulationDuty {
            get {
                return ResourceManager.GetString("ModulationDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率 的本地化字符串。
        /// </summary>
        internal static string ModulationFreq {
            get {
                return ResourceManager.GetString("ModulationFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负脉宽 的本地化字符串。
        /// </summary>
        internal static string ModulationNegPulse {
            get {
                return ResourceManager.GetString("ModulationNegPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周期 的本地化字符串。
        /// </summary>
        internal static string ModulationPeriod {
            get {
                return ResourceManager.GetString("ModulationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正脉宽 的本地化字符串。
        /// </summary>
        internal static string ModulationPosPulse {
            get {
                return ResourceManager.GetString("ModulationPosPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视在功率 的本地化字符串。
        /// </summary>
        internal static string QualityApparantPower {
            get {
                return ResourceManager.GetString("QualityApparantPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率 的本地化字符串。
        /// </summary>
        internal static string QualityFrequency {
            get {
                return ResourceManager.GetString("QualityFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流波峰因素 的本地化字符串。
        /// </summary>
        internal static string QualityICrestFactor {
            get {
                return ResourceManager.GetString("QualityICrestFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流均方根 的本地化字符串。
        /// </summary>
        internal static string QualityIrms {
            get {
                return ResourceManager.GetString("QualityIrms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相角 的本地化字符串。
        /// </summary>
        internal static string QualityPhase {
            get {
                return ResourceManager.GetString("QualityPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率因素 的本地化字符串。
        /// </summary>
        internal static string QualityPwrFactor {
            get {
                return ResourceManager.GetString("QualityPwrFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效功率 的本地化字符串。
        /// </summary>
        internal static string QualityReactivePower {
            get {
                return ResourceManager.GetString("QualityReactivePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效功率 的本地化字符串。
        /// </summary>
        internal static string QualityTruePower {
            get {
                return ResourceManager.GetString("QualityTruePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压波峰因素 的本地化字符串。
        /// </summary>
        internal static string QualityVCrestFactor {
            get {
                return ResourceManager.GetString("QualityVCrestFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压均方根 的本地化字符串。
        /// </summary>
        internal static string QualityVrms {
            get {
                return ResourceManager.GetString("QualityVrms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纹波 的本地化字符串。
        /// </summary>
        internal static string RipplePk2Pk {
            get {
                return ResourceManager.GetString("RipplePk2Pk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已采集波形 的本地化字符串。
        /// </summary>
        internal static string SOAAcqWfms {
            get {
                return ResourceManager.GetString("SOAAcqWfms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败波形数 的本地化字符串。
        /// </summary>
        internal static string SOAFailWfms {
            get {
                return ResourceManager.GetString("SOAFailWfms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOA模板测试 的本地化字符串。
        /// </summary>
        internal static string SOATestSucceed {
            get {
                return ResourceManager.GetString("SOATestSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周期数 的本地化字符串。
        /// </summary>
        internal static string SwitchLossCycleCount {
            get {
                return ResourceManager.GetString("SwitchLossCycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导通能量损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossEnergyTConduct {
            get {
                return ResourceManager.GetString("SwitchLossEnergyTConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非导通能量损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossEnergyTNonConduct {
            get {
                return ResourceManager.GetString("SwitchLossEnergyTNonConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关断能量损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossEnergyTOff {
            get {
                return ResourceManager.GetString("SwitchLossEnergyTOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开通能量损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossEnergyTOn {
            get {
                return ResourceManager.GetString("SwitchLossEnergyTOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能量损耗总计 的本地化字符串。
        /// </summary>
        internal static string SwitchLossEnergyTotal {
            get {
                return ResourceManager.GetString("SwitchLossEnergyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导通功率损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossPowerTConduct {
            get {
                return ResourceManager.GetString("SwitchLossPowerTConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非导通功率损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossPowerTNonConduct {
            get {
                return ResourceManager.GetString("SwitchLossPowerTNonConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关断功率损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossPowerTOff {
            get {
                return ResourceManager.GetString("SwitchLossPowerTOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开通功率损耗 的本地化字符串。
        /// </summary>
        internal static string SwitchLossPowerTOn {
            get {
                return ResourceManager.GetString("SwitchLossPowerTOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率损耗总计 的本地化字符串。
        /// </summary>
        internal static string SwitchLossPowerTotal {
            get {
                return ResourceManager.GetString("SwitchLossPowerTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瞬态时间 的本地化字符串。
        /// </summary>
        internal static string Transient {
            get {
                return ResourceManager.GetString("Transient", resourceCulture);
            }
        }
    }
}
